# Convert Word/Excel to PDF

In [1]:
import os
from pathlib import Path
import subprocess
import openpyxl
from openpyxl.utils.dataframe import dataframe_to_rows
import pandas as pd
from reportlab.lib.pagesizes import letter, A4
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors

# Check for LibreOffice availability (Linux alternative)
def check_libreoffice():
    try:
        result = subprocess.run(['libreoffice', '--version'], 
                              capture_output=True, text=True, timeout=5)
        return result.returncode == 0
    except (subprocess.TimeoutExpired, FileNotFoundError):
        return False

LIBREOFFICE_AVAILABLE = check_libreoffice()
if not LIBREOFFICE_AVAILABLE:
    print("LibreOffice not found. Install with: sudo apt-get install libreoffice")

# For Excel to PDF conversion
try:
    EXCEL_PDF_AVAILABLE = True
except ImportError:
    EXCEL_PDF_AVAILABLE = False
    print("Required packages not available. Install with: pip install openpyxl pandas reportlab")

def convert_word_to_pdf(word_file_path, output_pdf_path=None):
    """
    Convert Word document to PDF using LibreOffice (Linux compatible)
    """
    if not LIBREOFFICE_AVAILABLE:
        print("LibreOffice is required for Word to PDF conversion on Linux")
        return False
    
    try:
        word_file_path = Path(word_file_path)
        if output_pdf_path is None:
            output_pdf_path = word_file_path.with_suffix('.pdf')
        else:
            output_pdf_path = Path(output_pdf_path)
        
        # Use LibreOffice headless mode for conversion
        cmd = [
            'libreoffice',
            '--headless',
            '--convert-to', 'pdf',
            '--outdir', str(output_pdf_path.parent),
            str(word_file_path)
        ]
        
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
        
        if result.returncode == 0:
            # LibreOffice creates PDF with same name as input file
            generated_pdf = output_pdf_path.parent / f"{word_file_path.stem}.pdf"
            if generated_pdf != output_pdf_path and generated_pdf.exists():
                generated_pdf.rename(output_pdf_path)
            
            print(f"Successfully converted {word_file_path} to {output_pdf_path}")
            return True
        else:
            print(f"LibreOffice conversion failed: {result.stderr}")
            return False
            
    except subprocess.TimeoutExpired:
        print("LibreOffice conversion timed out")
        return False
    except Exception as e:
        print(f"Error converting Word to PDF: {e}")
        return False

def convert_excel_to_pdf(excel_file_path, output_pdf_path=None):
    """
    Convert Excel file to PDF maintaining table structure
    """
    if not EXCEL_PDF_AVAILABLE:
        print("Required packages not available for Excel to PDF conversion")
        return False
    
    try:
        if output_pdf_path is None:
            output_pdf_path = str(Path(excel_file_path).with_suffix('.pdf'))
        
        # Read Excel file
        df = pd.read_excel(excel_file_path, sheet_name=None)  # Read all sheets
        
        # Create PDF document
        doc = SimpleDocTemplate(output_pdf_path, pagesize=A4)
        elements = []
        styles = getSampleStyleSheet()
        
        for sheet_name, sheet_df in df.items():
            # Add sheet title
            title = Paragraph(f"<b>{sheet_name}</b>", styles['Heading1'])
            elements.append(title)
            elements.append(Spacer(1, 12))
            
            # Convert dataframe to table data
            table_data = [list(sheet_df.columns)]  # Headers
            for row in sheet_df.values:
                table_data.append([str(cell) if pd.notna(cell) else '' for cell in row])
            
            # Create table
            table = Table(table_data)
            table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 10),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
                ('GRID', (0, 0), (-1, -1), 1, colors.black)
            ]))
            
            elements.append(table)
            elements.append(Spacer(1, 20))
        
        # Build PDF
        doc.build(elements)
        print(f"Successfully converted {excel_file_path} to {output_pdf_path}")
        return True
    except Exception as e:
        print(f"Error converting Excel to PDF: {e}")
        return False

def convert_file_to_pdf(file_path, output_pdf_path=None):
    """
    Auto-detect file type and convert to PDF
    """
    file_path = Path(file_path)
    file_extension = file_path.suffix.lower()
    
    if file_extension in ['.docx', '.doc']:
        return convert_word_to_pdf(file_path, output_pdf_path)
    elif file_extension in ['.xlsx', '.xls']:
        return convert_excel_to_pdf(file_path, output_pdf_path)
    else:
        print(f"Unsupported file format: {file_extension}")
        return False

# Example usage:
# convert_word_to_pdf('document.docx', 'output.pdf')
# convert_excel_to_pdf('spreadsheet.xlsx', 'output.pdf')
# convert_file_to_pdf('file.docx')  # Auto-detect and convert

# Test khi combine thành 1 file ---> chunking ----> embedding (Advanced chunking, RAG)

In [ ]:
"""
This script converts Word/Excel files to PDF. Then use LLMs to parse the PDF content.
Finally, combine the parsed content into a single Markdown file.
"""
import os
import json
import time
import subprocess
import tempfile
from pathlib import Path
from typing import List, Optional
import google.generativeai as genai
# from google import genai
from langchain.schema import Document
from langchain.text_splitter import RecursiveCharacterTextSplitter
import warnings
from config import GOOGLE_API_KEY

import pandas as pd
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
warnings.filterwarnings("ignore")
warnings.filterwarnings("ignore", category=UserWarning, module='unstructured')

class DocumentParser:
    """
    Document Parser với conversion support nâng cao cho Gemini.
    Tích hợp file_converter để hỗ trợ nhiều format conversion.
    """
    
    def __init__(self, chunk_size: int = 1000, chunk_overlap: int = 150):
        self.text_splitter = RecursiveCharacterTextSplitter(
            chunk_size=chunk_size,
            chunk_overlap=chunk_overlap,
            length_function=len,
        )
        
        # Rate limiting settings
        self.last_api_call = 0
        self.min_delay_between_calls = 10.0  # Tăng từ 5 lên 10 giây
        self.max_retries = 5  # Tăng số lần thử lại
        self.base_retry_delay = 15.0  # Tăng thời gian chờ cơ bản
        self.exponential_backoff = True  # Thêm backoff theo cấp số nhân
        
        # Thêm giới hạn số lượng request mỗi phút
        self.max_requests_per_minute = 30
        self.request_count = 0
        self.minute_window_start = time.time()
        
        # API Setup
        if not GOOGLE_API_KEY:
            raise ValueError("GOOGLE_API_KEY không được tìm thấy trong config.py")
        
        genai.configure(api_key=GOOGLE_API_KEY)
        
        try:
            self.llm_client = genai.GenerativeModel('gemini-2.0-flash')
            print("✅ Gemini client (gemini-2.0-flash) for parsing đã sẵn sàng.")
        except Exception as e:
            print(f"⚠️ Fallback to gemini-1.5-flash: {e}")
            self.llm_client = genai.GenerativeModel('gemini-1.5-flash')

        # Supported file types cho direct processing
        self.supported_direct_types = {".pdf", ".txt", ".png", ".jpg", ".jpeg", ".gif", ".webp"}
        self.convertible_types = {".docx", ".doc", ".xlsx", ".xls"}
        
        # Check system capabilities
        self.libreoffice_available = self._check_libreoffice()
        self.excel_pdf_available = self._check_excel_pdf_libs()
        
        print(f"🔧 System capabilities:")
        print(f"   - LibreOffice: {'✅' if self.libreoffice_available else '❌'}")
        print(f"   - Excel-to-PDF: {'✅' if self.excel_pdf_available else '❌'}")

    def _check_libreoffice(self) -> bool:
        """Check if LibreOffice is available for document conversion."""
        try:
            result = subprocess.run(['libreoffice', '--version'], 
                                  capture_output=True, text=True, timeout=5)
            return result.returncode == 0
        except (subprocess.TimeoutExpired, FileNotFoundError):
            return False

    def _check_excel_pdf_libs(self) -> bool:
        """Check if required libraries for Excel-to-PDF conversion are available."""
        try:
            import pandas as pd
            from reportlab.lib.pagesizes import A4
            return True
        except ImportError:
            return False

    def _convert_to_supported_format(self, file_path: Path) -> Path:
        """
        Convert unsupported files to supported format using enhanced converters.
        """
        file_extension = file_path.suffix.lower()
        
        if file_extension in [".docx", ".doc"]:
            return self._convert_word_to_pdf_enhanced(file_path)
        elif file_extension in [".xlsx", ".xls"]:
            return self._convert_excel_to_pdf_enhanced(file_path)
        else:
            raise ValueError(f"Conversion not supported for {file_extension}")

    def _convert_word_to_pdf_enhanced(self, word_path: Path) -> Path:
        """
        Enhanced Word to PDF conversion with LibreOffice support.
        """
        print(f"🔄 Converting Word to PDF: {word_path.name}")
        
        # Create temporary PDF file
        with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as tmp_file:
            pdf_path = Path(tmp_file.name)
        
        # Method 1: Try LibreOffice (preferred for Linux)
        if self.libreoffice_available:
            try:
                cmd = [
                    'libreoffice',
                    '--headless',
                    '--convert-to', 'pdf',
                    '--outdir', str(pdf_path.parent),
                    str(word_path)
                ]
                
                result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
                
                if result.returncode == 0:
                    # LibreOffice creates PDF with same name as input file
                    generated_pdf = pdf_path.parent / f"{word_path.stem}.pdf"
                    if generated_pdf.exists():
                        if generated_pdf != pdf_path:
                            generated_pdf.rename(pdf_path)
                        print(f"✅ LibreOffice conversion successful: {pdf_path}")
                        return pdf_path
                    
            except subprocess.TimeoutExpired:
                print("⚠️ LibreOffice conversion timed out")
            except Exception as e:
                print(f"⚠️ LibreOffice conversion failed: {e}")
        
        # Method 2: Fallback to text extraction
        print("🔄 Falling back to text extraction...")
        return self._extract_docx_text_to_temp_file(word_path)

    def _convert_excel_to_pdf_enhanced(self, excel_path: Path) -> Path:
        """
        Enhanced Excel to PDF conversion maintaining table structure.
        """
        print(f"🔄 Converting Excel to PDF: {excel_path.name}")
        
        if self.excel_pdf_available:
            try:
                # Create temporary PDF file
                with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as tmp_file:
                    pdf_path = Path(tmp_file.name)
                
                # Read Excel file
                df_dict = pd.read_excel(excel_path, sheet_name=None)  # Read all sheets
                
                # Create PDF document
                doc = SimpleDocTemplate(str(pdf_path), pagesize=A4)
                elements = []
                styles = getSampleStyleSheet()
                
                for sheet_name, sheet_df in df_dict.items():
                    # Add sheet title
                    title = Paragraph(f"<b>{sheet_name}</b>", styles['Heading1'])
                    elements.append(title)
                    elements.append(Spacer(1, 12))
                    
                    # Convert dataframe to table data
                    if not sheet_df.empty:
                        table_data = [list(sheet_df.columns)]  # Headers
                        for row in sheet_df.values:
                            table_data.append([str(cell) if pd.notna(cell) else '' for cell in row])
                        
                        # Create table with styling
                        table = Table(table_data)
                        table.setStyle(TableStyle([
                            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
                            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                            ('FONTSIZE', (0, 0), (-1, 0), 8),
                            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
                            ('GRID', (0, 0), (-1, -1), 1, colors.black)
                        ]))
                        
                        elements.append(table)
                        elements.append(Spacer(1, 20))
                
                # Build PDF
                doc.build(elements)
                print(f"✅ Excel-to-PDF conversion successful: {pdf_path}")
                return pdf_path
                
            except Exception as e:
                print(f"⚠️ Excel-to-PDF conversion failed: {e}")
        
        # Fallback to text extraction
        print("🔄 Falling back to text extraction...")
        return self._extract_xlsx_text_to_temp_file(excel_path)

    def _extract_docx_text_to_temp_file(self, docx_path: Path) -> Path:
        """
        Extract text from DOCX and save to temporary text file.
        """
        print(f"🔄 Extracting text from DOCX: {docx_path.name}")
        
        try:
            from docx import Document as DocxDocument
            
            doc = DocxDocument(docx_path)
            full_text = []
            
            # Extract paragraphs
            for para in doc.paragraphs:
                if para.text.strip():
                    full_text.append(para.text)
            
            # Extract tables
            for table in doc.tables:
                table_text = []
                for row in table.rows:
                    row_text = " | ".join(cell.text.strip() for cell in row.cells)
                    if row_text.strip():
                        table_text.append(row_text)
                if table_text:
                    full_text.extend(table_text)
                    full_text.append("")  # Empty line after table
            
            # Save to temporary text file
            with tempfile.NamedTemporaryFile(mode='w', suffix=".txt", delete=False, encoding='utf-8') as tmp_file:
                tmp_file.write('\n'.join(full_text))
                temp_path = Path(tmp_file.name)
            
            print(f"✅ Extracted to text file: {temp_path}")
            return temp_path
            
        except Exception as e:
            print(f"❌ Text extraction failed: {e}")
            raise

    def _extract_xlsx_text_to_temp_file(self, xlsx_path: Path) -> Path:
        """
        Extract data from XLSX and save to temporary text file.
        """
        print(f"🔄 Extracting data from XLSX: {xlsx_path.name}")
        
        try:
            # Read all sheets
            excel_file = pd.ExcelFile(xlsx_path)
            full_text = []
            
            for sheet_name in excel_file.sheet_names:
                df = pd.read_excel(excel_file, sheet_name=sheet_name)
                if not df.empty:
                    full_text.append(f"=== SHEET: {sheet_name} ===")
                    
                    # Convert to markdown-style table
                    headers = " | ".join(str(col) for col in df.columns)
                    separator = " | ".join("---" for _ in df.columns)
                    full_text.append(headers)
                    full_text.append(separator)
                    
                    for _, row in df.iterrows():
                        row_text = " | ".join(str(cell) if pd.notna(cell) else "" for cell in row)
                        full_text.append(row_text)
                    
                    full_text.append("")  # Empty line between sheets
            
            # Save to temporary text file
            with tempfile.NamedTemporaryFile(mode='w', suffix=".txt", delete=False, encoding='utf-8') as tmp_file:
                tmp_file.write('\n'.join(full_text))
                temp_path = Path(tmp_file.name)
            
            print(f"✅ Extracted to text file: {temp_path}")
            return temp_path
            
        except Exception as e:
            print(f"❌ XLSX extraction failed: {e}")
            raise
    
    def _apply_rate_limit(self):
        """Enhanced rate limiting with multiple strategies."""
        current_time = time.time()
        
        # 1. Basic delay between calls
        time_since_last_call = current_time - self.last_api_call
        if time_since_last_call < self.min_delay_between_calls:
            delay = self.min_delay_between_calls - time_since_last_call
            print(f"⏳ Basic rate limiting: Waiting {delay:.1f} seconds...")
            time.sleep(delay)
        
        # 2. Requests per minute limit
        if current_time - self.minute_window_start > 60:
            # Reset counter if we're in a new minute window
            self.request_count = 0
            self.minute_window_start = current_time
        else:
            self.request_count += 1
        
        if self.request_count >= self.max_requests_per_minute:
            time_remaining = 60 - (current_time - self.minute_window_start)
            print(f"⏳ Minute limit reached. Waiting {time_remaining:.1f} seconds...")
            time.sleep(time_remaining)
            self.request_count = 0
            self.minute_window_start = time.time()
        
        self.last_api_call = time.time()

    def _parse_with_llm_with_retry(self, file_path: Path) -> str:
        """
        Parse file với enhanced conversion support và retry printic.
        """
        original_path = file_path
        temp_file_created = False
        
        # Check if conversion is needed
        if file_path.suffix.lower() not in self.supported_direct_types:
            if file_path.suffix.lower() in self.convertible_types:
                print(f"📋 File type {file_path.suffix} không được Gemini hỗ trợ trực tiếp. Đang convert...")
                try:
                    file_path = self._convert_to_supported_format(file_path)
                    temp_file_created = True
                except Exception as conv_error:
                    print(f"❌ Conversion failed: {conv_error}")
                    return ""
            else:
                print(f"❌ File type {file_path.suffix} không được hỗ trợ.")
                return ""

        print(f"🧠 Bắt đầu parsing bằng LLM cho file: {original_path.name}...")
        
        uploaded_file = None
        
        try:
            for attempt in range(self.max_retries):
                try:
                    # Rate limiting
                    self._apply_rate_limit()
                    
                    # Upload file
                    if not uploaded_file:
                        uploaded_file = genai.upload_file(path=str(file_path), display_name=original_path.name)
                    
                    # Wait for processing
                    max_wait_time = 60
                    wait_time = 0
                    while uploaded_file.state.name == "PROCESSING" and wait_time < max_wait_time:
                        time.sleep(2)
                        wait_time += 2
                        uploaded_file = genai.get_file(uploaded_file.name)
                    
                    if uploaded_file.state.name == "FAILED":
                        print(f"❌ File upload failed: {uploaded_file.state}")
                        return ""
                    
                    # Generate content
                    self._apply_rate_limit()
                    
                    prompt = """
                    <TASK_DEFINITION>
                    You are an automated data processing engine. Your sole task is to analyze the provided file and convert its entire content into a single, clean, and well-structured Markdown string. The output must be a perfect representation of the original data, suitable for machine parsing later.

                    Follow these critical instructions precisely:

                    1.  **Analyze Layout:** First, analyze the visual layout of the document. Identify key-value pairs (e.g., a label in one cell and its value in another, potentially non-adjacent cell) and structured tables.
                    2.  **Convert Key-Value Pairs:** Represent all identified key-value pairs clearly.
                    3.  **Convert Tables:** Convert all structured tables into standard Markdown table format.
                    4.  **Preserve Content:** All text and numerical data must be preserved exactly as it appears in the original file.
                    5.  **No Extra Content:** Do not add any summaries, explanations, comments, or any text that is not present in the original document.
                    6.  **Strict Output Format:** Your entire output must be ONLY the Markdown content. Do not wrap it in ```markdown ... ``` or any other formatting.
                    </TASK_DEFINITION>

                    <OUTPUT_EXAMPLE>
                    ### A. THÔNG TIN CHUNG
                    - **Ngày thực hiện:** 4/16/2024
                    - **CusID:** 22079986
                    - **Tên Khách hàng:** CÔNG TY CỔ PHẦN MẶT DỰNG CAG
                    - **Phân khúc:** MM
                    - **Subsegment:** Dịch vụ Xây lắp, lắp đặt
                    - **XHTD:** Aa3
                    - **BBC:** (Trống)
                    - **DDA:** Vùng
                    </OUTPUT_EXAMPLE>

                    Analyze the provided file. Think step-by-step to ensure all data is captured accurately, then generate the final Markdown output.
                    """


                    response = self.llm_client.generate_content([uploaded_file, prompt])
                    print(f"✅ LLM đã parse thành công file: {original_path.name}")
                    return response.text

                except Exception as e:
                    error_message = str(e)
                    
                    if "429" in error_message or "quota" in error_message.lower():
                        retry_delay = self.base_retry_delay * (2 ** attempt)
                        print(f"  ⚠️ Gặp lỗi Rate Limit. Đang thử lại sau {retry_delay} giây... (Lần {attempt + 1}/{self.max_retries})")
                        time.sleep(retry_delay)
                        continue
                    elif "mimeType" in error_message or "not supported" in error_message:
                        print(f"❌ Lỗi MIME type không được hỗ trợ: {e}")
                        break
                    elif "503" in error_message or "Service Unavailable" in error_message:
                        retry_delay = self.base_retry_delay * (2 ** attempt)
                        print(f"  ⚠️ Gemini service unavailable. Đang thử lại sau {retry_delay} giây... (Lần {attempt + 1}/{self.max_retries})")
                        time.sleep(retry_delay)
                        continue
                    else:
                        print(f"❌ Lỗi khác khi parsing: {e}")
                        break
            
            print(f"  ❌ Đã thử lại {self.max_retries} lần nhưng vẫn gặp lỗi. Bỏ cuộc.")
            return ""
            
        finally:
            # Cleanup
            if uploaded_file:
                try:
                    genai.delete_file(uploaded_file.name)
                    print(f"🧹 Đã cleanup uploaded file: {original_path.name}")
                except:
                    pass
            
            # Remove temporary file if created
            if temp_file_created and file_path.exists():
                try:
                    os.unlink(file_path)
                    print(f"🧹 Đã xóa file tạm: {file_path}")
                except:
                    pass

    def parse_file(self, file_path: str) -> List[Document]:
        """
        Parse file với enhanced conversion support.
        """
        file_path = Path(file_path)
        
        if not file_path.exists():
            print(f"❌ File không tồn tại: {file_path}")
            return []
        
        # Parse với LLM
        full_markdown_content = self._parse_with_llm_with_retry(file_path)
        
        if not full_markdown_content or not full_markdown_content.strip():
            print(f"⚠️ LLM không trả về nội dung nào cho file {file_path.name}. Trả về danh sách rỗng.")
            return []
        return full_markdown_content

    def convert_file_to_pdf(self, file_path: str, output_pdf_path: Optional[str] = None) -> Optional[str]:
        """
        Public method to convert files to PDF format.
        
        Args:
            file_path: Path to input file
            output_pdf_path: Optional output path for PDF
            
        Returns:
            Path to converted PDF file or None if conversion failed
        """
        file_path = Path(file_path)
        file_extension = file_path.suffix.lower()
        
        if file_extension not in self.convertible_types:
            print(f"❌ Conversion không được hỗ trợ cho file type: {file_extension}")
            return None
        
        try:
            if output_pdf_path:
                output_path = Path(output_pdf_path)
            else:
                output_path = file_path.with_suffix('.pdf')
            
            if file_extension in ['.docx', '.doc']:
                converted_path = self._convert_word_to_pdf_enhanced(file_path)
                print(f"Nội dung của file PDF là : {converted_path}")
            elif file_extension in ['.xlsx', '.xls']:
                converted_path = self._convert_excel_to_pdf_enhanced(file_path)
                print(f"Nội dung của file PDF là : {converted_path}")
            else:
                return None
            
            # Move converted file to desired location if different
            if converted_path != output_path:
                converted_path.rename(output_path)
            
            return str(output_path)
            
        except Exception as e:
            print(f"❌ Conversion failed: {e}")
            return None
        
if __name__ == "__main__":
    parser = DocumentParser()
    parse_folder = Path(r'/root/chatbot1/chatbot_document/data/data2')
    combined_data = []  # Khởi tạo trước vòng lặp
    for files in list(parse_folder.glob('*')):
        if files.suffix.lower() in parser.convertible_types:
            print(f"📄 Đang parse file: {files.name}")
            doc_test = parser.parse_file(files)
            if doc_test:
                print(f"✅ Đã parse thành công: {files.name}")
                combined_data.append(doc_test)  # Thêm chuỗi vào danh sách
            else:
                print(f"❌ Không thể parse file: {files.name}")
    print(f"📄 Đã parse {len(combined_data)} documents từ thư mục {parse_folder.name}.")
    os.makedirs('output_parsing', exist_ok=True)
    with open('output_parsing/parsed_output.md', 'w', encoding='utf-8') as f:
        for doc in combined_data:
            f.write(doc + '\n\n')
    print("✅ Đã lưu kết quả parsing vào file: output_parsing/parsed_output.md")

✅ Gemini client (gemini-2.0-flash) for parsing đã sẵn sàng.
🔧 System capabilities:
   - LibreOffice: ✅
   - Excel-to-PDF: ✅
📄 Đang parse file: call-rp.xlsx
📋 File type .xlsx không được Gemini hỗ trợ trực tiếp. Đang convert...
🔄 Converting Excel to PDF: call-rp.xlsx
✅ Excel-to-PDF conversion successful: /tmp/tmpf8of1mm2.pdf
🧠 Bắt đầu parsing bằng LLM cho file: call-rp.xlsx...
⏳ Basic rate limiting: Waiting 5.0 seconds...
✅ LLM đã parse thành công file: call-rp.xlsx
🧹 Đã cleanup uploaded file: call-rp.xlsx
🧹 Đã xóa file tạm: /tmp/tmpf8of1mm2.pdf
✅ Đã parse thành công: call-rp.xlsx
📄 Đang parse file: DN HMTD CAG 2024 (1).docx
📋 File type .docx không được Gemini hỗ trợ trực tiếp. Đang convert...
🔄 Converting Word to PDF: DN HMTD CAG 2024 (1).docx
✅ LibreOffice conversion successful: /tmp/tmptoopfp1i.pdf
🧠 Bắt đầu parsing bằng LLM cho file: DN HMTD CAG 2024 (1).docx...
⏳ Basic rate limiting: Waiting 5.5 seconds...
✅ LLM đã parse thành công file: DN HMTD CAG 2024 (1).docx
🧹 Đã cleanup uploaded file: DN HMTD CAG 2024 (1).docx
🧹 Đã xóa file tạm: /tmp/tmptoopfp1i.pdf
✅ Đã parse thành công: DN HMTD CAG 2024 (1).docx
📄 Đang parse file: SO-SÁNH-DN-CÙNG-NGÀNH.docx
📋 File type .docx không được Gemini hỗ trợ trực tiếp. Đang convert...
🔄 Converting Word to PDF: SO-SÁNH-DN-CÙNG-NGÀNH.docx
✅ LibreOffice conversion successful: /tmp/tmpv5m41uic.pdf
🧠 Bắt đầu parsing bằng LLM cho file: SO-SÁNH-DN-CÙNG-NGÀNH.docx...
⏳ Basic rate limiting: Waiting 2.9 seconds...
✅ LLM đã parse thành công file: SO-SÁNH-DN-CÙNG-NGÀNH.docx
🧹 Đã cleanup uploaded file: SO-SÁNH-DN-CÙNG-NGÀNH.docx
🧹 Đã xóa file tạm: /tmp/tmpv5m41uic.pdf
✅ Đã parse thành công: SO-SÁNH-DN-CÙNG-NGÀNH.docx
📄 Đã parse 3 documents từ thư mục data2.
✅ Đã lưu kết quả parsing vào file: output_parsing/parsed_output.md

# Test chunking and embedding

## Full raw input

In [ ]:
# ==============================================================================
# MỤC ĐÍCH: CHẠY PIPELINE RAG VÀ THU THẬP KẾT QUẢ ĐỂ ĐÁNH GIÁ
# ==============================================================================

import os
import json
from pathlib import Path
from typing import List, Tuple
import time
import uuid
import numpy as np
import pandas as pd
from langchain.schema import Document
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_google_genai import ChatGoogleGenerativeAI
from sentence_transformers import CrossEncoder
from utils.api_key_manager import ApiKeyManager
from qdrant_client import QdrantClient
from qdrant_client.http.models import Distance, VectorParams, PointStruct

# --- CẤU HÌNH ---
DELAY_BETWEEN_CALLS = 10
QDRANT_HOST = "localhost"  
QDRANT_PORT = 6333      
COLLECTION_NAME = "child_chunks_eval_notebook" # Dùng collection name mới để tránh xung đột
GOOGLE_API_KEY = "AIzaSyBPglAFlDOf97drnNAplHIIsjgvsfzezsI" # Thay bằng key của bạn

# --- KHỞI TẠO CÁC MODEL ---
print("🧠 Đang khởi tạo các model RAG...")
embedding_model = HuggingFaceEmbeddings(
    model_name="jinaai/jina-embeddings-v3",
    model_kwargs={"device": "cpu", "trust_remote_code": True}
)
llm_client = ChatGoogleGenerativeAI(model="gemini-2.0-flash", google_api_key=GOOGLE_API_KEY, temperature=0)
reranker_model = CrossEncoder('BAAI/bge-reranker-large', device='cpu')
qdrant_client = QdrantClient(host=QDRANT_HOST, port=QDRANT_PORT)
print("✅ Các model RAG đã sẵn sàng.")


def clear_qdrant_collection():
    """Xóa collection để đảm bảo dữ liệu mới mỗi lần chạy."""
    try:
        qdrant_client.delete_collection(collection_name=COLLECTION_NAME)
        print(f"✅ Đã xóa collection '{COLLECTION_NAME}' (nếu tồn tại).")
    except Exception:
        pass # Bỏ qua nếu collection không tồn tại

def setup_qdrant_collection(embedding_dim: int):
    """Tạo hoặc tái tạo collection trong Qdrant."""
    try:
        qdrant_client.recreate_collection(
            collection_name=COLLECTION_NAME,
            vectors_config=VectorParams(size=embedding_dim, distance=Distance.COSINE)
        )
        print(f"✅ Đã tạo/tái tạo collection '{COLLECTION_NAME}' trong Qdrant.")
        return True
    except Exception as e:
        print(f"❌ Lỗi khi setup Qdrant collection: {e}")
        return False

def store_child_chunks_in_qdrant(child_chunks: List[Document], child_embeddings: np.ndarray):
    """Lưu child chunks và embeddings vào Qdrant."""
    points = []
    for chunk, emb in zip(child_chunks, child_embeddings):
        payload = {
            "content": chunk.page_content,
            "parent_id": chunk.metadata.get("parent_id"),
            "parent_content": chunk.metadata.get("parent_content"),
            "source": chunk.metadata.get("source", "unknown")
        }
        points.append(PointStruct(id=str(uuid.uuid4()), vector=emb.tolist(), payload=payload))
    qdrant_client.upsert(collection_name=COLLECTION_NAME, points=points, wait=True)
    print(f"✅ Đã lưu {len(points)} child chunks vào Qdrant.")

def setup_small_to_big_data_with_qdrant(markdown_content: str):
    """Chuẩn bị dữ liệu cho chiến lược Small-to-Big và lưu vào Qdrant."""
    print("--- Bước 1: Chuẩn bị dữ liệu Small-to-Big với Qdrant ---")
    parent_splitter = RecursiveCharacterTextSplitter(chunk_size=2000, chunk_overlap=200)
    child_splitter = RecursiveCharacterTextSplitter(chunk_size=400, chunk_overlap=50)
    parent_chunks = parent_splitter.create_documents([markdown_content])
    print(f"✅ Đã tạo {len(parent_chunks)} parent chunks (đoạn văn lớn).")

    all_child_chunks = []
    for i, p_chunk in enumerate(parent_chunks):
        child_texts = child_splitter.split_text(p_chunk.page_content)
        for text in child_texts:
            all_child_chunks.append(Document(page_content=text, metadata={"parent_id": i, "parent_content": p_chunk.page_content}))
    print(f"✅ Đã tạo {len(all_child_chunks)} child chunks (câu nhỏ) từ các parent.")
            
    sample_embedding = embedding_model.embed_query("test")
    if not setup_qdrant_collection(len(sample_embedding)): 
        return None, False
    
    print("🧠 Đang embedding các child chunks...")
    child_contents = [c.page_content for c in all_child_chunks]
    child_embeddings = np.array(embedding_model.embed_documents(child_contents))
    print("✅ Embedding child chunks hoàn tất!")
    
    store_child_chunks_in_qdrant(all_child_chunks, child_embeddings)
    return parent_chunks, True

# <<< CẢI TIẾN 1: Đổi tên và sửa hàm để trả về List[str] >>>
def retrieve_context_list(query: str, top_k_final: int = 3, retrieve_k_children: int = 15) -> List[str]:
    """
    Mô phỏng pipeline RAG nâng cao và trả về một DANH SÁCH các context liên quan nhất.
    """
    query_embedding = embedding_model.embed_query(query)
    search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)
    
    candidate_parents = {hit.payload["parent_content"] for hit in search_results if hit.payload and "parent_content" in hit.payload}
    
    if not candidate_parents: return [] # Trả về list rỗng
    
    parent_contents = list(candidate_parents)
    pairs = [(query, content) for content in parent_contents]
    scores = reranker_model.predict(pairs)
    reranked_results = sorted(zip(scores, parent_contents), key=lambda x: x[0], reverse=True)
    
    # <<< THAY ĐỔI: Trả về danh sách các chuỗi thay vì một chuỗi duy nhất >>>
    final_docs = [content for _, content in reranked_results[:top_k_final]]
    return final_docs
    
def answer_with_context(query: str, context_list: List[str]) -> str: # <<< Nhận vào list
    """Sử dụng LLM để trả lời câu hỏi dựa trên context được cung cấp."""
    # <<< THAY ĐỔI: Nối lại danh sách context thành một chuỗi duy nhất cho prompt >>>
    full_context_str = "\n\n---\n\n".join(context_list)
    
    prompt_template = f"""Bạn là một trợ lý AI chuyên nghiệp, chỉ trả lời dựa trên context được cung cấp.
Trả lời câu hỏi một cách ngắn gọn và chính xác. Nếu không có thông tin trong context, hãy nói "Tôi không tìm thấy thông tin trong tài liệu."

Context:
---
{full_context_str}
---

Câu hỏi: {query}

Trả lời:
"""
    response = llm_client.invoke(prompt_template)
    return response.content

# --- CHẠY PIPELINE VÀ THU THẬP DỮ LIỆU ---

generated_data_for_eval = [] 

markdown_file_path = Path("output_parsing/parsed_output.md")

if not markdown_file_path.exists():
    print(f"❌ Lỗi: Không tìm thấy file {markdown_file_path}. Vui lòng chạy bước parsing trước.")
else:
    with open(markdown_file_path, 'r', encoding='utf-8') as f:
        markdown_content = f.read()

    clear_qdrant_collection()
    parent_chunks, success = setup_small_to_big_data_with_qdrant(markdown_content)
    
    if not success:
        print("❌ Không thể setup dữ liệu với Qdrant. Dừng chương trình.")
    else:
        # Lấy câu hỏi từ file ragasdf_base.json
        with open('/root/chatbot1/chatbot_document/backend/schemas/ragasdf_base.json', 'r', encoding='utf-8') as f:
            template4_queries_data = json.load(f)
        template4_queries = [item['question'] for item in template4_queries_data]

        print(f"\n\n=== 🚀 BẮT ĐẦU CHẠY RAG VÀ THU THẬP DỮ LIỆU TRÊN {len(template4_queries)} CÂU HỎI ===")
        
        for i, query in enumerate(template4_queries, 1):
            print(f"\n--- Query {i}/{len(template4_queries)} ---")
            print(f"❓ Câu hỏi: {query}")
            
            # context = simulate_s2b_with_reranking_qdrant(query)
            context_list = retrieve_context_list(query)
            # answer = answer_with_context(query, context)
            answer = answer_with_context(query, context_list) 
            print(f"✅ Câu trả lời của hệ thống: {answer}")
            
            # Lưu kết quả vào danh sách
            generated_data_for_eval.append({
                "question": query,
                "answer": answer,
                "contexts": context_list 
            })
            
            print("-" * 40)
            if i < len(template4_queries):
                print(f"⏳ Đợi {DELAY_BETWEEN_CALLS} giây...")
                time.sleep(DELAY_BETWEEN_CALLS)

        print("\n\n✅ Đã thu thập xong toàn bộ dữ liệu (answer, context).")
        display(pd.DataFrame(generated_data_for_eval).head())
        # Lưu kết quả vào file JSON
        output_file = Path('output_parsing/generated_data_for_eval(full_raw_input).json')
        output_file.parent.mkdir(parents=True, exist_ok=True)
        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump(generated_data_for_eval, f, ensure_ascii=False, indent=4)
        print(f"✅ Đã lưu kết quả vào file: {output_file}")

In [ ]:
# ==============================================================================
# CELL MỚI: THỰC HIỆN ĐÁNH GIÁ BẰNG RAGAS
# ==============================================================================
from utils.ragas_evaluation import RagasEvaluator
import pandas as pd
from pathlib import Path
import json
# 1. Khởi tạo Evaluator
# Đảm bảo GOOGLE_API_KEY đã được định nghĩa ở cell trên
GOOGLE_API_KEYS = [ "AIzaSyAWtCSrLhJDZGF1ArOSS0o7Iy_zMG42810",
                    "AIzaSyCaKzwEjW0XxJAuZ9XdzI6rHkifHkA0eNY",
                    "AIzaSyBH8O5IfqYrJ5wtWnmUC21IfMjzJCrTm3I",
                    "AIzaSyDtBIjTSfbvuEsobNwjtdyi9gVpDrCaWPM",
                    "AIzaSyAD_58r3fQhcTOE6qQS1YlR3iJ_ZnGKy10",
                    "AIzaSyCtAz9maZ9usoxEHhhFocHW07WM4IbgOXo",
                    "AIzaSyCI8QGQrVUgr_FrFLttDs0fP4VyJyPXoec",
                    "AIzaSyBPglAFlDOf97drnNAplHIIsjgvsfzezsI",
                    "AIzaSyDNosIJZjXd2tzm7_VKxK5uFTBmoPuHXkc"]

evaluator = RagasEvaluator(list_of_api_keys=GOOGLE_API_KEYS)

# load generated data từ file JSON
generated_data_file = Path('output_parsing/generated_data_for_eval(full_raw_input).json')
if not generated_data_file.exists():
    print(f"❌ Lỗi: Không tìm thấy file {generated_data_file}. Vui lòng chạy bước thu thập dữ liệu trước.")
else:
    with open(generated_data_file, 'r', encoding='utf-8') as f:
        generated_data_for_eval = json.load(f)
        
# 2. Tải dataset cơ sở (chứa question và ground_truth)
base_data = evaluator.load_base_dataset('/root/chatbot1/chatbot_document/backend/schemas/ragasdf_base.json')

# 3. Chuẩn bị dataset hoàn chỉnh bằng cách kết hợp base_data và generated_data
eval_dataset = evaluator.prepare_evaluation_dataset(
    base_data=base_data,
    generated_data=generated_data_for_eval # Sử dụng kết quả từ cell trước
)

# 4. Xuất file dataset RAGAS hoàn chỉnh ra Excel để kiểm tra
if eval_dataset:
    ragas_df = eval_dataset.to_pandas()
    ragas_df['context_count'] = ragas_df['contexts'].apply(len)
    output_df_path = "new/ragasdf/ragas_dataset_for_evaluation(full_raw_input).xlsx"
    os.makedirs(Path(output_df_path).parent, exist_ok=True)
    ragas_df.to_excel(output_df_path, index=False)
    print(f"Đã xuất file dataset RAGAS hoàn chỉnh ra: {output_df_path}")
    print("Đây là 5 dòng đầu tiên của dataset sẽ được đánh giá:")
    display(ragas_df.head())
    
# 5. Chạy đánh giá
if eval_dataset:
    results_df = evaluator.run_evaluation(eval_dataset)

    if results_df is not None:
        # 6. Hiển thị và lưu báo cáo
        print("\n\n--- 📊 KẾT QUẢ ĐÁNH GIÁ CHI TIẾT ---")
        display(results_df)

        evaluator.save_report(results_df, "/root/chatbot1/chatbot_document/backend/new/evaluation_reports", "ragas_report(full_raw_input).xlsx")
    else:
        print("❌ Đánh giá không trả về kết quả.")
else:
    print("❌ Không thể tạo dataset để đánh giá.")

🚀 Khởi tạo RagasEvaluator (có Retry & Key Switching)...

flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.

✅ LLM và Embeddings đã sẵn sàng.
📋 Đã định nghĩa 12 metrics: ['faithfulness', 'answer_relevancy', 'context_precision', 'context_recall', 'semantic_similarity', 'answer_correctness', 'factual_correctness', 'exact_match', 'bleu_score', 'rouge_score', 'semantic_similarity', 'non_llm_string_similarity']
📁 Đã tạo thư mục báo cáo: evaluation_reports
📂 Đang tải base dataset từ: /root/chatbot1/chatbot_document/backend/schemas/ragasdf_base.json
✅ Tải thành công 40 mẫu.
🔄 Đang chuẩn bị dataset để đánh giá...
✅ Đã chuẩn hóa cột 'contexts' với kiểu dữ liệu: <class 'list'>
✅ Đã tạo thành công dataset với 40 mẫu để đánh giá.
✅ Kiểu dữ liệu của cột 'contexts' đã được xác nhận là: <class 'list'>
✅ Sau khi loại bỏ null/empty, còn 16 mẫu.
✅ Đã thêm cột 'reference' từ ground_truths.
💾 Đã xuất file dataset RAGAS hoàn chỉnh ra: new/ragasdf/ragas_dataset_for_evaluation(full_raw_input).xlsx
Đây là 5 dòng đầu tiên của dataset sẽ được đánh giá:

,question,ground_truths,answer,contexts,reference,__index_level_0__,context_count
0,Tên đầy đủ của khách hàng là gì?,[CÔNG TY CỔ PHẦN MẶT DỰNG CAG],CÔNG TY CỔ PHẦN MẶT DỰNG CAG,[Kính gửi: Ngân hàng TMCP Kỹ Thương Việt Nam –...,CÔNG TY CỔ PHẦN MẶT DỰNG CAG,0,3
1,Số giấy phép đăng ký kinh doanh của khách hàng...,[0101442420],Số 0101442420 do Phòng Đăng ký kinh doanh – Sở...,[Kính gửi: Ngân hàng TMCP Kỹ Thương Việt Nam –...,0101442420,1,3
2,ID khách hàng là gì?,[22079986],22079986,[Kính gửi: Ngân hàng TMCP Kỹ Thương Việt Nam –...,22079986,2,3
3,Phân khúc của khách hàng là gì?,[MM],Dân dụng: các tòa nhà văn phòng\nThi công trưn...,[| [Bản tiếng Việt] | [English Version] |\n|--...,MM,3,3
4,"XHTD của khách hàng là gì?, XHTD là xếp hạng t...",[Aa3],Tôi không tìm thấy thông tin trong tài liệu.,[C. TÀI SẢN BẢO ĐẢM\nĐể bảo đảm cho khoản vay/...,Aa3,8,3

✅ Dataset schema hợp lệ. Columns: ['question', 'ground_truths', 'answer', 'contexts', 'reference', '__index_level_0__']

🔬 Bắt đầu đánh giá RAGAS trên 16 mẫu với 12 metrics...
📋 Metrics: ['faithfulness', 'answer_relevancy', 'context_precision', 'context_recall', 'semantic_similarity', 'answer_correctness', 'factual_correctness', 'exact_match', 'bleu_score', 'rouge_score', 'semantic_similarity', 'non_llm_string_similarity']

--- 🔄 Đang đánh giá dòng 1/16 ---
   Q: Tên đầy đủ của khách hàng là gì?...
    🔄 Metric 1/12: faithfulness
    ✅ faithfulness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/12: answer_relevancy
    ✅ answer_relevancy: 0.4232411684411765
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/12: context_precision
    ✅ context_precision: 0.9999999999
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/12: context_recall
    ✅ context_recall: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/12: semantic_similarity
    ✅ semantic_similarity: 0.9999999999999999
    🔄 Metric 6/12: answer_correctness
    ✅ answer_correctness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 7/12: factual_correctness
    ✅ factual_correctness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 8/12: exact_match
    ✅ exact_match: 1.0
    🔄 Metric 9/12: bleu_score
    ✅ bleu_score: 1.0000000000000004
    🔄 Metric 10/12: rouge_score
    ✅ rouge_score: 1.0
    🔄 Metric 11/12: semantic_similarity
    ✅ semantic_similarity: 0.9999999999999999
    🔄 Metric 12/12: non_llm_string_similarity
    ✅ non_llm_string_similarity: 1.0
✅ Đánh giá dòng 1 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 2/16 ---
   Q: Số giấy phép đăng ký kinh doanh của khách hàng là gì?...
    🔄 Metric 1/12: faithfulness
    ✅ faithfulness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/12: answer_relevancy
    ✅ answer_relevancy: 0.7353857161272727
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/12: context_precision
    ✅ context_precision: 0.9999999999
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/12: context_recall
    ✅ context_recall: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/12: semantic_similarity
    ✅ semantic_similarity: 0.5900985813694843
    🔄 Metric 6/12: answer_correctness
    ✅ answer_correctness: 0.44752464534237113
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 7/12: factual_correctness
    ✅ factual_correctness: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 8/12: exact_match
    ✅ exact_match: 0.0
    🔄 Metric 9/12: bleu_score
    ✅ bleu_score: 0.008130350574508933
    🔄 Metric 10/12: rouge_score
    ✅ rouge_score: 0.04166666666666667
    🔄 Metric 11/12: semantic_similarity
    ✅ semantic_similarity: 0.5900985813694843
    🔄 Metric 12/12: non_llm_string_similarity
    ✅ non_llm_string_similarity: 0.06134969325153372
✅ Đánh giá dòng 2 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 3/16 ---
   Q: ID khách hàng là gì?...
    🔄 Metric 1/12: faithfulness
    ✅ faithfulness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/12: answer_relevancy
    ✅ answer_relevancy: 0.4559890154269372
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/12: context_precision
    ✅ context_precision: 0.9999999999
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/12: context_recall
    ✅ context_recall: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/12: semantic_similarity
    ✅ semantic_similarity: 1.0
    🔄 Metric 6/12: answer_correctness
    ✅ answer_correctness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 7/12: factual_correctness
    ✅ factual_correctness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 8/12: exact_match
    ✅ exact_match: 1.0
    🔄 Metric 9/12: bleu_score
    ✅ bleu_score: 0.0
    🔄 Metric 10/12: rouge_score
    ✅ rouge_score: 1.0
    🔄 Metric 11/12: semantic_similarity
    ✅ semantic_similarity: 1.0
    🔄 Metric 12/12: non_llm_string_similarity
    ✅ non_llm_string_similarity: 1.0
✅ Đánh giá dòng 3 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 4/16 ---
   Q: Phân khúc của khách hàng là gì?...
    🔄 Metric 1/12: faithfulness
    ✅ faithfulness: 0.6666666666666666
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/12: answer_relevancy
    ✅ answer_relevancy: 0.2767362475168264
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/12: context_precision
    ✅ context_precision: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/12: context_recall
    ✅ context_recall: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/12: semantic_similarity
    ✅ semantic_similarity: 0.38030646327347917
    🔄 Metric 6/12: answer_correctness
    ✅ answer_correctness: 0.09507661581836979
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 7/12: factual_correctness
    ✅ factual_correctness: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 8/12: exact_match
    ✅ exact_match: 0.0
    🔄 Metric 9/12: bleu_score
    ✅ bleu_score: 0.0
    🔄 Metric 10/12: rouge_score
    ✅ rouge_score: 0.0
    🔄 Metric 11/12: semantic_similarity
    ✅ semantic_similarity: 0.38030646327347917
    🔄 Metric 12/12: non_llm_string_similarity
    ✅ non_llm_string_similarity: 0.0
✅ Đánh giá dòng 4 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 5/16 ---
   Q: XHTD của khách hàng là gì?, XHTD là xếp hạng tín dụng của khách hàng và thường có các giá trị như Aa...
    🔄 Metric 1/12: faithfulness
    ✅ faithfulness: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/12: answer_relevancy
    ✅ answer_relevancy: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/12: context_precision
    ✅ context_precision: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/12: context_recall
    ✅ context_recall: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/12: semantic_similarity
    ✅ semantic_similarity: 0.4144482595235611
    🔄 Metric 6/12: answer_correctness
    ✅ answer_correctness: 0.10361206488089028
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 7/12: factual_correctness
    ✅ factual_correctness: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 8/12: exact_match
    ✅ exact_match: 0.0
    🔄 Metric 9/12: bleu_score
    ✅ bleu_score: 0.0
    🔄 Metric 10/12: rouge_score
    ✅ rouge_score: 0.0
    🔄 Metric 11/12: semantic_similarity
    ✅ semantic_similarity: 0.4144482595235611
    🔄 Metric 12/12: non_llm_string_similarity
    ✅ non_llm_string_similarity: 0.0
✅ Đánh giá dòng 5 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 6/16 ---
   Q: Ngày thành lập công ty là ngày nào?...
    🔄 Metric 1/12: faithfulness
    ✅ faithfulness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/12: answer_relevancy
    ✅ answer_relevancy: 0.6461790135626552
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/12: context_precision
    ✅ context_precision: 0.3333333333
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/12: context_recall
    ✅ context_recall: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/12: semantic_similarity
    ✅ semantic_similarity: 0.9999999999999998
    🔄 Metric 6/12: answer_correctness
    ✅ answer_correctness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 7/12: factual_correctness
    ✅ factual_correctness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 8/12: exact_match
    ✅ exact_match: 1.0
    🔄 Metric 9/12: bleu_score
    ✅ bleu_score: 1.0000000000000004
    🔄 Metric 10/12: rouge_score
    ✅ rouge_score: 1.0
    🔄 Metric 11/12: semantic_similarity
    ✅ semantic_similarity: 0.9999999999999998
    🔄 Metric 12/12: non_llm_string_similarity
    ✅ non_llm_string_similarity: 1.0
✅ Đánh giá dòng 6 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 7/16 ---
   Q: Địa chỉ đăng ký kinh doanh của công ty là gì?...
    🔄 Metric 1/12: faithfulness
    ✅ faithfulness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/12: answer_relevancy
    ✅ answer_relevancy: 0.632719269099672
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/12: context_precision
    ✅ context_precision: 0.3333333333
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/12: context_recall
    ✅ context_recall: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/12: semantic_similarity
    ✅ semantic_similarity: 1.0
    🔄 Metric 6/12: answer_correctness
    ✅ answer_correctness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 7/12: factual_correctness
    ✅ factual_correctness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 8/12: exact_match
    ✅ exact_match: 1.0
    🔄 Metric 9/12: bleu_score
    ✅ bleu_score: 1.0000000000000004
    🔄 Metric 10/12: rouge_score
    ✅ rouge_score: 1.0
    🔄 Metric 11/12: semantic_similarity
    ✅ semantic_similarity: 1.0
    🔄 Metric 12/12: non_llm_string_similarity
    ✅ non_llm_string_similarity: 1.0
✅ Đánh giá dòng 7 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 8/16 ---
   Q: Người đại diện theo pháp luật của công ty là ai?...
    🔄 Metric 1/12: faithfulness
    ✅ faithfulness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/12: answer_relevancy
    ✅ answer_relevancy: 0.557907366566567
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/12: context_precision
    ✅ context_precision: 0.9999999999
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/12: context_recall
    ✅ context_recall: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/12: semantic_similarity
    ✅ semantic_similarity: 0.7969774567338391
    🔄 Metric 6/12: answer_correctness
    ✅ answer_correctness: 0.6992443641834598
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 7/12: factual_correctness
    ✅ factual_correctness: 0.67
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 8/12: exact_match
    ✅ exact_match: 0.0
    🔄 Metric 9/12: bleu_score
    ✅ bleu_score: 0.12605968092174913
    🔄 Metric 10/12: rouge_score
    ✅ rouge_score: 0.4210526315789474
    🔄 Metric 11/12: semantic_similarity
    ✅ semantic_similarity: 0.7969774567338391
    🔄 Metric 12/12: non_llm_string_similarity
    ✅ non_llm_string_similarity: 0.2790697674418605
✅ Đánh giá dòng 8 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 9/16 ---
   Q: Khách hàng có kinh doanh ngành nghề có điều kiện không?...
    🔄 Metric 1/12: faithfulness
    ✅ faithfulness: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/12: answer_relevancy
    ✅ answer_relevancy: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/12: context_precision
    ✅ context_precision: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/12: context_recall
    ✅ context_recall: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/12: semantic_similarity
    ✅ semantic_similarity: 0.4436944308523454
    🔄 Metric 6/12: answer_correctness
    ✅ answer_correctness: 0.11092360771308635
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 7/12: factual_correctness
    ✅ factual_correctness: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 8/12: exact_match
    ✅ exact_match: 0.0
    🔄 Metric 9/12: bleu_score
    ✅ bleu_score: 0.0
    🔄 Metric 10/12: rouge_score
    ✅ rouge_score: 0.0
    🔄 Metric 11/12: semantic_similarity
    ✅ semantic_similarity: 0.4436944308523454
    🔄 Metric 12/12: non_llm_string_similarity
    ✅ non_llm_string_similarity: 0.0
✅ Đánh giá dòng 9 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 10/16 ---
   Q: Thông tin chi tiết về ban lãnh đạo công ty là gì. Hãy liệt kê đầy đủ tên các thành viên, chức vụ, tỉ...
    🔄 Metric 1/12: faithfulness
    ✅ faithfulness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/12: answer_relevancy
    ✅ answer_relevancy: 0.6437104633161912
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/12: context_precision
    ✅ context_precision: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/12: context_recall
    ✅ context_recall: 0.3333333333333333
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/12: semantic_similarity
    ✅ semantic_similarity: 0.7393532079972579
    🔄 Metric 6/12: answer_correctness
    ✅ answer_correctness: 0.7848383019993146
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 7/12: factual_correctness
    ✅ factual_correctness: 0.8
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 8/12: exact_match
    ✅ exact_match: 0.0
    🔄 Metric 9/12: bleu_score
    ✅ bleu_score: 0.0036317732883193897
    🔄 Metric 10/12: rouge_score
    ✅ rouge_score: 0.5384615384615384
    🔄 Metric 11/12: semantic_similarity
    ✅ semantic_similarity: 0.7393532079972579
    🔄 Metric 12/12: non_llm_string_similarity
    ✅ non_llm_string_similarity: 0.19999999999999996
✅ Đánh giá dòng 10 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 11/16 ---
   Q: Thông tin chi tiết về đầu vào sản xuất kinh doanh là gì?...
    🔄 Metric 1/12: faithfulness
    ✅ faithfulness: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/12: answer_relevancy
    ✅ answer_relevancy: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/12: context_precision
    ✅ context_precision: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/12: context_recall
    ✅ context_recall: 0.3333333333333333
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/12: semantic_similarity
    ✅ semantic_similarity: 0.3287032038185591
    🔄 Metric 6/12: answer_correctness
    ✅ answer_correctness: 0.08217580095463978
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 7/12: factual_correctness
    ✅ factual_correctness: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 8/12: exact_match
    ✅ exact_match: 0.0
    🔄 Metric 9/12: bleu_score
    ✅ bleu_score: 0.018382465348186564
    🔄 Metric 10/12: rouge_score
    ✅ rouge_score: 0.18421052631578946
    🔄 Metric 11/12: semantic_similarity
    ✅ semantic_similarity: 0.3287032038185591
    🔄 Metric 12/12: non_llm_string_similarity
    ✅ non_llm_string_similarity: 0.1497584541062802
✅ Đánh giá dòng 11 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 12/16 ---
   Q: Thông tin chi tiết về đầu ra sản xuất kinh doanh là gì?...
    🔄 Metric 1/12: faithfulness
    ✅ faithfulness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/12: answer_relevancy
    ✅ answer_relevancy: 0.3651628264294955
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/12: context_precision
    ✅ context_precision: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/12: context_recall
    ✅ context_recall: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/12: semantic_similarity
    ✅ semantic_similarity: 0.3239260980925951
    🔄 Metric 6/12: answer_correctness
    ✅ answer_correctness: 0.08098152452314877
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 7/12: factual_correctness
    ✅ factual_correctness: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 8/12: exact_match
    ✅ exact_match: 0.0
    🔄 Metric 9/12: bleu_score
    ✅ bleu_score: 0.005536354630771405
    🔄 Metric 10/12: rouge_score
    ✅ rouge_score: 0.0
    🔄 Metric 11/12: semantic_similarity
    ✅ semantic_similarity: 0.3239260980925951
    🔄 Metric 12/12: non_llm_string_similarity
    ✅ non_llm_string_similarity: 0.07207207207207211
✅ Đánh giá dòng 12 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 13/16 ---
   Q: Lĩnh vực kinh doanh của công ty là gì?...
    🔄 Metric 1/12: faithfulness
    ✅ faithfulness: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/12: answer_relevancy
    ✅ answer_relevancy: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/12: context_precision
    ✅ context_precision: 0.8333333332916666
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/12: context_recall
    ✅ context_recall: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/12: semantic_similarity
    ✅ semantic_similarity: 0.23198296325701795
    🔄 Metric 6/12: answer_correctness
    ✅ answer_correctness: 0.05799574081425449
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 7/12: factual_correctness
    ✅ factual_correctness: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 8/12: exact_match
    ✅ exact_match: 0.0
    🔄 Metric 9/12: bleu_score
    ✅ bleu_score: 0.0
    🔄 Metric 10/12: rouge_score
    ✅ rouge_score: 0.15384615384615385
    🔄 Metric 11/12: semantic_similarity
    ✅ semantic_similarity: 0.23198296325701795
    🔄 Metric 12/12: non_llm_string_similarity
    ✅ non_llm_string_similarity: 0.18181818181818177
✅ Đánh giá dòng 13 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 14/16 ---
   Q: Sản phẩm/dịch vụ của công ty là gì?...
    🔄 Metric 1/12: faithfulness
    ✅ faithfulness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/12: answer_relevancy
    ✅ answer_relevancy: 0.5773069342863197
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/12: context_precision
    ✅ context_precision: 0.9999999999
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/12: context_recall
    ✅ context_recall: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/12: semantic_similarity
    ✅ semantic_similarity: 0.8076241862524637
    🔄 Metric 6/12: answer_correctness
    ✅ answer_correctness: 0.5480598927169621
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 7/12: factual_correctness
    ✅ factual_correctness: 0.11
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 8/12: exact_match
    ✅ exact_match: 0.0
    🔄 Metric 9/12: bleu_score
    ✅ bleu_score: 0.06290147512951708
    🔄 Metric 10/12: rouge_score
    ✅ rouge_score: 0.29596412556053814
    🔄 Metric 11/12: semantic_similarity
    ✅ semantic_similarity: 0.8076241862524637
    🔄 Metric 12/12: non_llm_string_similarity
    ✅ non_llm_string_similarity: 0.12411847672778564
✅ Đánh giá dòng 14 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 15/16 ---
   Q: Đầu vào - mặt hàng là gì?...
    🔄 Metric 1/12: faithfulness
    ✅ faithfulness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/12: answer_relevancy
    ✅ answer_relevancy: 0.4807927678347899
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/12: context_precision
    ✅ context_precision: 0.3333333333
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/12: context_recall
    ✅ context_recall: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/12: semantic_similarity
    ✅ semantic_similarity: 0.6250574811910559
    🔄 Metric 6/12: answer_correctness
    ✅ answer_correctness: 0.15626437029776397
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 7/12: factual_correctness
    ✅ factual_correctness: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 8/12: exact_match
    ✅ exact_match: 0.0
    🔄 Metric 9/12: bleu_score
    ✅ bleu_score: 0.018089024246571755
    🔄 Metric 10/12: rouge_score
    ✅ rouge_score: 0.1643835616438356
    🔄 Metric 11/12: semantic_similarity
    ✅ semantic_similarity: 0.6250574811910559
    🔄 Metric 12/12: non_llm_string_similarity
    ✅ non_llm_string_similarity: 0.10752688172043012
✅ Đánh giá dòng 15 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 16/16 ---
   Q: Đầu vào - chi tiết là gì?...
    🔄 Metric 1/12: faithfulness
    ✅ faithfulness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/12: answer_relevancy
    ✅ answer_relevancy: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/12: context_precision
    ✅ context_precision: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/12: context_recall
    ✅ context_recall: 0.5
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/12: semantic_similarity
    ✅ semantic_similarity: 0.7186967970446236
    🔄 Metric 6/12: answer_correctness
    ✅ answer_correctness: 0.3732225863579301
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 7/12: factual_correctness
    ✅ factual_correctness: 0.28
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 8/12: exact_match
    ✅ exact_match: 0.0

,faithfulness,answer_relevancy,context_precision,context_recall,semantic_similarity,answer_correctness,factual_correctness,exact_match,bleu_score,rouge_score(mode=fmeasure),non_llm_string_similarity
0,1.000000,0.423241,1.000000,1.000000,1.000000,1.000000,1.00,1.0,1.000000,1.000000,1.000000
1,1.000000,0.735386,1.000000,1.000000,0.590099,0.447525,0.00,0.0,0.008130,0.041667,0.061350
2,1.000000,0.455989,1.000000,1.000000,1.000000,1.000000,1.00,1.0,0.000000,1.000000,1.000000
3,0.666667,0.276736,0.000000,0.000000,0.380306,0.095077,0.00,0.0,0.000000,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.000000,0.414448,0.103612,0.00,0.0,0.000000,0.000000,0.000000
5,1.000000,0.646179,0.333333,1.000000,1.000000,1.000000,1.00,1.0,1.000000,1.000000,1.000000
6,1.000000,0.632719,0.333333,1.000000,1.000000,1.000000,1.00,1.0,1.000000,1.000000,1.000000
7,1.000000,0.557907,1.000000,1.000000,0.796977,0.699244,0.67,0.0,0.126060,0.421053,0.279070
8,0.000000,0.000000,0.000000,0.000000,0.443694,0.110924,0.00,0.0,0.000000,0.000000,0.000000
9,1.000000,0.643710,0.000000,0.333333,0.739353,0.784838,0.80,0.0,0.003632,0.538462,0.200000
10,0.000000,0.000000,0.000000,0.333333,0.328703,0.082176,0.00,0.0,0.018382,0.184211,0.149758
11,1.000000,0.365163,0.000000,0.000000,0.323926,0.080982,0.00,0.0,0.005536,0.000000,0.072072
12,0.000000,0.000000,0.833333,1.000000,0.231983,0.057996,0.00,0.0,0.000000,0.153846,0.181818
13,1.000000,0.577307,1.000000,1.000000,0.807624,0.548060,0.11,0.0,0.062901,0.295964,0.124118
14,1.000000,0.480793,0.333333,1.000000,0.625057,0.156264,0.00,0.0,0.018089,0.164384,0.107527
15,1.000000,0.000000,0.000000,0.500000,0.718697,0.373223,0.28,0.0,0.009216,0.227273,0.138639

📁 Đã đảm bảo thư mục tồn tại: /root/chatbot1/chatbot_document/backend/new/evaluation_reports
📊 Tìm thấy 12 metrics trong kết quả: ['faithfulness', 'answer_relevancy', 'context_precision', 'context_recall', 'semantic_similarity', 'answer_correctness', 'factual_correctness', 'exact_match', 'bleu_score', 'rouge_score(mode=fmeasure)', 'semantic_similarity', 'non_llm_string_similarity']
📊 Báo cáo đã được lưu tại: /root/chatbot1/chatbot_document/backend/new/evaluation_reports/ragas_report(full_raw_input).xlsx
📋 Điểm số trung bình:
   faithfulness: 0.7292
   answer_relevancy: 0.3622
   context_precision: 0.4271
   context_recall: 0.6354
   semantic_similarity: 0.6501
   answer_correctness: 0.4712
   factual_correctness: 0.3663
   exact_match: 0.2500
   bleu_score: 0.2032
   rouge_score(mode=fmeasure): 0.3767
   non_llm_string_similarity: 0.3321

## Full stack + claude parsing

In [6]:
# ==============================================================================
# MỤC ĐÍCH: CHẠY PIPELINE RAG VÀ THU THẬP KẾT QUẢ ĐỂ ĐÁNH GIÁ
# ==============================================================================

import os
import json
from pathlib import Path
from typing import List, Tuple
import time
import uuid
import numpy as np
import pandas as pd
from langchain.schema import Document
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_google_genai import ChatGoogleGenerativeAI
from sentence_transformers import CrossEncoder
from utils.api_key_manager import ApiKeyManager
from qdrant_client import QdrantClient
from qdrant_client.http.models import Distance, VectorParams, PointStruct

# --- CẤU HÌNH ---
DELAY_BETWEEN_CALLS = 10
QDRANT_HOST = "localhost"  
QDRANT_PORT = 6333      
COLLECTION_NAME = "child_chunks_eval_notebook" # Dùng collection name mới để tránh xung đột
GOOGLE_API_KEY = "AIzaSyBPglAFlDOf97drnNAplHIIsjgvsfzezsI" # Thay bằng key của bạn

# --- KHỞI TẠO CÁC MODEL ---
print("🧠 Đang khởi tạo các model RAG...")
embedding_model = HuggingFaceEmbeddings(
    model_name="jinaai/jina-embeddings-v3",
    model_kwargs={"device": "cpu", "trust_remote_code": True}
)
llm_client = ChatGoogleGenerativeAI(model="gemini-2.0-flash", google_api_key=GOOGLE_API_KEY, temperature=0)
reranker_model = CrossEncoder('BAAI/bge-reranker-large', device='cpu')
qdrant_client = QdrantClient(host=QDRANT_HOST, port=QDRANT_PORT)
print("✅ Các model RAG đã sẵn sàng.")


def clear_qdrant_collection():
    """Xóa collection để đảm bảo dữ liệu mới mỗi lần chạy."""
    try:
        qdrant_client.delete_collection(collection_name=COLLECTION_NAME)
        print(f"✅ Đã xóa collection '{COLLECTION_NAME}' (nếu tồn tại).")
    except Exception:
        pass # Bỏ qua nếu collection không tồn tại

def setup_qdrant_collection(embedding_dim: int):
    """Tạo hoặc tái tạo collection trong Qdrant."""
    try:
        qdrant_client.recreate_collection(
            collection_name=COLLECTION_NAME,
            vectors_config=VectorParams(size=embedding_dim, distance=Distance.COSINE)
        )
        print(f"✅ Đã tạo/tái tạo collection '{COLLECTION_NAME}' trong Qdrant.")
        return True
    except Exception as e:
        print(f"❌ Lỗi khi setup Qdrant collection: {e}")
        return False

def store_child_chunks_in_qdrant(child_chunks: List[Document], child_embeddings: np.ndarray):
    """Lưu child chunks và embeddings vào Qdrant."""
    points = []
    for chunk, emb in zip(child_chunks, child_embeddings):
        payload = {
            "content": chunk.page_content,
            "parent_id": chunk.metadata.get("parent_id"),
            "parent_content": chunk.metadata.get("parent_content"),
            "source": chunk.metadata.get("source", "unknown")
        }
        points.append(PointStruct(id=str(uuid.uuid4()), vector=emb.tolist(), payload=payload))
    qdrant_client.upsert(collection_name=COLLECTION_NAME, points=points, wait=True)
    print(f"✅ Đã lưu {len(points)} child chunks vào Qdrant.")

def setup_small_to_big_data_with_qdrant(markdown_content: str):
    """Chuẩn bị dữ liệu cho chiến lược Small-to-Big và lưu vào Qdrant."""
    print("--- Bước 1: Chuẩn bị dữ liệu Small-to-Big với Qdrant ---")
    parent_splitter = RecursiveCharacterTextSplitter(chunk_size=2000, chunk_overlap=200)
    child_splitter = RecursiveCharacterTextSplitter(chunk_size=400, chunk_overlap=50)
    parent_chunks = parent_splitter.create_documents([markdown_content])
    print(f"✅ Đã tạo {len(parent_chunks)} parent chunks (đoạn văn lớn).")

    all_child_chunks = []
    for i, p_chunk in enumerate(parent_chunks):
        child_texts = child_splitter.split_text(p_chunk.page_content)
        for text in child_texts:
            all_child_chunks.append(Document(page_content=text, metadata={"parent_id": i, "parent_content": p_chunk.page_content}))
    print(f"✅ Đã tạo {len(all_child_chunks)} child chunks (câu nhỏ) từ các parent.")
            
    sample_embedding = embedding_model.embed_query("test")
    if not setup_qdrant_collection(len(sample_embedding)): 
        return None, False
    
    print("🧠 Đang embedding các child chunks...")
    child_contents = [c.page_content for c in all_child_chunks]
    child_embeddings = np.array(embedding_model.embed_documents(child_contents))
    print("✅ Embedding child chunks hoàn tất!")
    
    store_child_chunks_in_qdrant(all_child_chunks, child_embeddings)
    return parent_chunks, True

# <<< CẢI TIẾN 1: Đổi tên và sửa hàm để trả về List[str] >>>
def retrieve_context_list(query: str, top_k_final: int = 3, retrieve_k_children: int = 15) -> List[str]:
    """
    Mô phỏng pipeline RAG nâng cao và trả về một DANH SÁCH các context liên quan nhất.
    """
    query_embedding = embedding_model.embed_query(query)
    search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)
    
    candidate_parents = {hit.payload["parent_content"] for hit in search_results if hit.payload and "parent_content" in hit.payload}
    
    if not candidate_parents: return [] # Trả về list rỗng
    
    parent_contents = list(candidate_parents)
    pairs = [(query, content) for content in parent_contents]
    scores = reranker_model.predict(pairs)
    reranked_results = sorted(zip(scores, parent_contents), key=lambda x: x[0], reverse=True)
    
    # <<< THAY ĐỔI: Trả về danh sách các chuỗi thay vì một chuỗi duy nhất >>>
    final_docs = [content for _, content in reranked_results[:top_k_final]]
    return final_docs
    
def answer_with_context(query: str, context_list: List[str]) -> str: # <<< Nhận vào list
    """Sử dụng LLM để trả lời câu hỏi dựa trên context được cung cấp."""
    # <<< THAY ĐỔI: Nối lại danh sách context thành một chuỗi duy nhất cho prompt >>>
    full_context_str = "\n\n---\n\n".join(context_list)
    
    prompt_template = f"""Bạn là một trợ lý AI chuyên nghiệp, chỉ trả lời dựa trên context được cung cấp.
Trả lời câu hỏi một cách ngắn gọn và chính xác. Nếu không có thông tin trong context, hãy nói "Tôi không tìm thấy thông tin trong tài liệu."

Context:
---
{full_context_str}
---

Câu hỏi: {query}

Trả lời:
"""
    response = llm_client.invoke(prompt_template)
    return response.content

# --- CHẠY PIPELINE VÀ THU THẬP DỮ LIỆU ---

generated_data_for_eval = [] 

markdown_file_path = Path("output_parsing/claude_raw_input.md")

if not markdown_file_path.exists():
    print(f"❌ Lỗi: Không tìm thấy file {markdown_file_path}. Vui lòng chạy bước parsing trước.")
else:
    with open(markdown_file_path, 'r', encoding='utf-8') as f:
        markdown_content = f.read()

    clear_qdrant_collection()
    parent_chunks, success = setup_small_to_big_data_with_qdrant(markdown_content)
    
    if not success:
        print("❌ Không thể setup dữ liệu với Qdrant. Dừng chương trình.")
    else:
        # Lấy câu hỏi từ file ragasdf_base.json
        with open('/root/chatbot1/chatbot_document/backend/schemas/ragasdf_base.json', 'r', encoding='utf-8') as f:
            template4_queries_data = json.load(f)
        template4_queries = [item['question'] for item in template4_queries_data]

        print(f"\n\n=== 🚀 BẮT ĐẦU CHẠY RAG VÀ THU THẬP DỮ LIỆU TRÊN {len(template4_queries)} CÂU HỎI ===")
        
        for i, query in enumerate(template4_queries, 1):
            print(f"\n--- Query {i}/{len(template4_queries)} ---")
            print(f"❓ Câu hỏi: {query}")
            
            # context = simulate_s2b_with_reranking_qdrant(query)
            context_list = retrieve_context_list(query)
            # answer = answer_with_context(query, context)
            answer = answer_with_context(query, context_list) 
            print(f"✅ Câu trả lời của hệ thống: {answer}")
            
            # Lưu kết quả vào danh sách
            generated_data_for_eval.append({
                "question": query,
                "answer": answer,
                "contexts": context_list 
            })
            
            print("-" * 40)
            if i < len(template4_queries):
                print(f"⏳ Đợi {DELAY_BETWEEN_CALLS} giây...")
                time.sleep(DELAY_BETWEEN_CALLS)

        print("\n\n✅ Đã thu thập xong toàn bộ dữ liệu (answer, context).")
        display(pd.DataFrame(generated_data_for_eval).head())
        # Lưu kết quả vào file JSON
        output_file = Path('output_parsing/generated_data_for_eval(full_raw_input_claude_parsing).json')
        output_file.parent.mkdir(parents=True, exist_ok=True)
        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump(generated_data_for_eval, f, ensure_ascii=False, indent=4)
        print(f"✅ Đã lưu kết quả vào file: {output_file}")

🧠 Đang khởi tạo các model RAG...

WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
/tmp/ipykernel_6711/1089340801.py:37: UserWarning: Qdrant client version 1.15.1 is incompatible with server version 1.7.2. Major versions should match and minor version difference must not exceed 1. Set check_compatibility=False to skip version check.
  qdrant_client = QdrantClient(host=QDRANT_HOST, port=QDRANT_PORT)

✅ Các model RAG đã sẵn sàng.
✅ Đã xóa collection 'child_chunks_eval_notebook' (nếu tồn tại).
--- Bước 1: Chuẩn bị dữ liệu Small-to-Big với Qdrant ---
✅ Đã tạo 19 parent chunks (đoạn văn lớn).
✅ Đã tạo 102 child chunks (câu nhỏ) từ các parent.

/tmp/ipykernel_6711/1089340801.py:52: DeprecationWarning: `recreate_collection` method is deprecated and will be removed in the future. Use `collection_exists` to check collection existence and `create_collection` instead.
  qdrant_client.recreate_collection(

✅ Đã tạo/tái tạo collection 'child_chunks_eval_notebook' trong Qdrant.
🧠 Đang embedding các child chunks...
✅ Embedding child chunks hoàn tất!
✅ Đã lưu 102 child chunks vào Qdrant.


=== 🚀 BẮT ĐẦU CHẠY RAG VÀ THU THẬP DỮ LIỆU TRÊN 40 CÂU HỎI ===

--- Query 1/40 ---
❓ Câu hỏi: Tên đầy đủ của khách hàng là gì?

/tmp/ipykernel_6711/1089340801.py:109: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: CÔNG TY CỔ PHẦN MẶT DỰNG CAG
----------------------------------------
⏳ Đợi 10 giây...

--- Query 2/40 ---
❓ Câu hỏi: Số giấy phép đăng ký kinh doanh của khách hàng là gì?

/tmp/ipykernel_6711/1089340801.py:109: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Số 0101442420 do Phòng Đăng ký kinh doanh -- Sở Kế hoạch và Đầu tư thành phố Hà Nội cấp, đăng ký lần đầu ngày 19/01/2004, đăng ký thay đổi lần thứ 8 ngày 12/04/2023
----------------------------------------
⏳ Đợi 10 giây...

--- Query 3/40 ---
❓ Câu hỏi: ID khách hàng là gì?

/tmp/ipykernel_6711/1089340801.py:109: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: ID khách hàng: 22079986
----------------------------------------
⏳ Đợi 10 giây...

--- Query 4/40 ---
❓ Câu hỏi: Phân khúc của khách hàng là gì?

/tmp/ipykernel_6711/1089340801.py:109: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Dân dụng: các tòa nhà văn phòng, trung tâm thương mại.
Ngân sách nhà nước: các tòa nhà ủy ban, trung tâm hành chính, hội nghị, văn hóa của các tỉnh thành phố.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 5/40 ---
❓ Câu hỏi: Loại khách hàng là gì?

/tmp/ipykernel_6711/1089340801.py:109: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: CAG
----------------------------------------
⏳ Đợi 10 giây...

--- Query 6/40 ---
❓ Câu hỏi: Ngành nghề hoạt động kinh doanh của khách hàng là gì?

/tmp/ipykernel_6711/1089340801.py:109: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Sản xuất xây dựng (SXXD).
----------------------------------------
⏳ Đợi 10 giây...

--- Query 7/40 ---
❓ Câu hỏi: Mục đích báo cáo là gì?

/tmp/ipykernel_6711/1089340801.py:109: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 8/40 ---
❓ Câu hỏi: Kết quả phân luồng của khách hàng là gì?

/tmp/ipykernel_6711/1089340801.py:109: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 9/40 ---
❓ Câu hỏi: XHTD của khách hàng là gì?, XHTD là xếp hạng tín dụng của khách hàng và thường có các giá trị như Aa3, Baa2, v.v.

/tmp/ipykernel_6711/1089340801.py:109: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 10/40 ---
❓ Câu hỏi: Ngày thành lập công ty là ngày nào?

/tmp/ipykernel_6711/1089340801.py:109: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Ngày 19 tháng 01 năm 2004.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 11/40 ---
❓ Câu hỏi: Địa chỉ đăng ký kinh doanh của công ty là gì?

/tmp/ipykernel_6711/1089340801.py:109: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Lô CN4 - 2.1, KCN Thạch Thất, Thị Trấn Quốc Oai, Huyện Quốc Oai, Thành phố Hà Nội, Việt Nam
----------------------------------------
⏳ Đợi 10 giây...

--- Query 12/40 ---
❓ Câu hỏi: Người đại diện theo pháp luật của công ty là ai?

/tmp/ipykernel_6711/1089340801.py:109: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Họ và tên: ĐÀO CÔNG DUY
Chức danh: Tổng giám đốc
----------------------------------------
⏳ Đợi 10 giây...

--- Query 13/40 ---
❓ Câu hỏi: Khách hàng có kinh doanh ngành nghề có điều kiện không?

/tmp/ipykernel_6711/1089340801.py:109: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 14/40 ---
❓ Câu hỏi: Thông tin chi tiết về ban lãnh đạo công ty là gì. Hãy liệt kê đầy đủ tên các thành viên, chức vụ, tỉ lệ góp vốn nếu có?

/tmp/ipykernel_6711/1089340801.py:109: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: - Đào Công Duy, Tổng giám đốc, 90%
- Thái Thị Kim Dung, 8%
- Đào Công Dũng, 2%
----------------------------------------
⏳ Đợi 10 giây...

--- Query 15/40 ---
❓ Câu hỏi: Thông tin chi tiết về đầu vào sản xuất kinh doanh là gì?

/tmp/ipykernel_6711/1089340801.py:109: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Nhôm thanh:
- Các mã kích thước nhỏ: có thể nhập hàng sản xuất trong nước
- Các mã kích thước lớn: trong nước ko sản xuất => hàng nhập khẩu Trung Quốc
Phôi kính:
- Với hàng nguồn gốc nhập khẩu, công ty thường mua thông qua các đơn vị chuyên nhập phôi kính do nếu nhập khẩu trực tiếp sẽ không đáp ứng về chi phí & tiến độ
- Kính không màu: có thể nhập hàng sản xuất trong nước
----------------------------------------
⏳ Đợi 10 giây...

--- Query 16/40 ---
❓ Câu hỏi: Thông tin chi tiết về đầu ra sản xuất kinh doanh là gì?

/tmp/ipykernel_6711/1089340801.py:109: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 17/40 ---
❓ Câu hỏi: Nhận xét về thông tin khách hàng là gì?

/tmp/ipykernel_6711/1089340801.py:109: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Khách hàng là CÔNG TY CỔ PHẦN MẶT DỰNG CAG, ID khách hàng là 22079986. Công ty có Giấy CNĐKDN số 0101442420, đăng ký lần đầu ngày 19/01/2004, đăng ký thay đổi lần thứ 8 ngày 12/04/2023. Địa chỉ liên hệ tại Lô CN4 -- 2.1, KCN Thạch Thất, thị trấn Quốc Oai, huyện Quốc Oai, thành phố Hà Nội. Người đại diện theo pháp luật là ông ĐÀO CÔNG DUY, chức vụ Tổng Giám đốc.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 18/40 ---
❓ Câu hỏi: Nhận xét về pháp lý/GPKD có điều kiện là gì?

/tmp/ipykernel_6711/1089340801.py:109: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 19/40 ---
❓ Câu hỏi: Nhận xét về chủ doanh nghiệp/ban lãnh đạo là gì?

/tmp/ipykernel_6711/1089340801.py:109: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 20/40 ---
❓ Câu hỏi: Nhận xét về KYC là gì?

/tmp/ipykernel_6711/1089340801.py:109: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 21/40 ---
❓ Câu hỏi: Lĩnh vực kinh doanh của công ty là gì?

/tmp/ipykernel_6711/1089340801.py:109: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 22/40 ---
❓ Câu hỏi: Sản phẩm/dịch vụ của công ty là gì?

/tmp/ipykernel_6711/1089340801.py:109: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 23/40 ---
❓ Câu hỏi: Tỷ trọng doanh thu năm N-1 (%) là bao nhiêu?

/tmp/ipykernel_6711/1089340801.py:109: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 24/40 ---
❓ Câu hỏi: Tỷ trọng doanh thu năm N (%) là bao nhiêu?

/tmp/ipykernel_6711/1089340801.py:109: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 25/40 ---
❓ Câu hỏi: Nhóm mặt hàng của công ty là gì?

/tmp/ipykernel_6711/1089340801.py:109: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 26/40 ---
❓ Câu hỏi: Tỷ trọng doanh thu năm 2023 là bao nhiêu?

/tmp/ipykernel_6711/1089340801.py:109: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 27/40 ---
❓ Câu hỏi: Tỷ trọng doanh thu 10T/2024 là bao nhiêu?

/tmp/ipykernel_6711/1089340801.py:109: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 28/40 ---
❓ Câu hỏi: Mô tả chung về sản phẩm của công ty là gì?

/tmp/ipykernel_6711/1089340801.py:109: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Khách hàng có 3 nhà máy, lắp ráp & thi công vách kính mặt dựng tại các tòa nhà cao tầng. Nhôm thanh được nhập về => cắt theo kích thước khung kính => lắp ráp & bắt vít khung nhôm => bơm keo => đóng gói chuyển ra công trường. Tại công trường: lắp đặt bản mã sau khi thi công => lắp đặt các unit được chuyển từ nhà máy vào bản mã đặt sẵn tại công trình.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 29/40 ---
❓ Câu hỏi: Mô tả lợi thế cạnh tranh của công ty là gì?

/tmp/ipykernel_6711/1089340801.py:109: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 30/40 ---
❓ Câu hỏi: Mô tả năng lực đấu thầu của công ty là gì?

/tmp/ipykernel_6711/1089340801.py:109: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Công ty ít ký hợp đồng với tư cách nhà thầu phụ, phần lớn ký trực tiếp với chủ đầu tư, một số trường hợp ký với tổng thầu & CAG là nhà thầu do CĐT chỉ định.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 31/40 ---
❓ Câu hỏi: Quy trình vận hành (tóm tắt) của công ty là gì?

/tmp/ipykernel_6711/1089340801.py:109: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 32/40 ---
❓ Câu hỏi: Đầu vào - mặt hàng là gì?

/tmp/ipykernel_6711/1089340801.py:109: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Đầu vào là nhôm thanh và phôi kính.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 33/40 ---
❓ Câu hỏi: Đầu vào - chi tiết là gì?

/tmp/ipykernel_6711/1089340801.py:109: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Đầu vào:
- Các nhà máy sản xuất nhôm thanh & kính không màu trong nước
- Các công ty thương mại chuyên nhập khẩu nhôm thanh (các mã kích thước lớn không sản xuất trong nước) và kính màu (trong nước chưa sản xuất được)
- **Nhôm thanh:**
  - Các mã kích thước nhỏ: có thể nhập hàng sản xuất trong nước
  - Các mã kích thước lớn: trong nước ko sản xuất => hàng nhập khẩu Trung Quốc
- **Phôi kính:**
  - Với hàng nguồn gốc nhập khẩu, công ty thường mua thông qua các đơn vị chuyên nhập phôi kính do nếu nhập khẩu trực tiếp sẽ không đáp ứng về chi phí & tiến độ
  - Kính không màu: có thể nhập hàng sản xuất trong nước
----------------------------------------
⏳ Đợi 10 giây...

--- Query 34/40 ---
❓ Câu hỏi: Đầu vào - phương thức thanh toán là gì?

/tmp/ipykernel_6711/1089340801.py:109: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 35/40 ---
❓ Câu hỏi: Đầu ra - kênh phân phối là gì?

/tmp/ipykernel_6711/1089340801.py:109: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Phần lớn ký trực tiếp với chủ đầu tư, một số trường hợp ký với tổng thầu & CAG là nhà thầu do CĐT chỉ định. Công ty ít ký hợp đồng với tư cách nhà thầu phụ. Dân dụng: các tòa nhà văn phòng, trung tâm thương mại. Ngân sách nhà nước: các tòa nhà ủy ban, trung tâm hành chính, hội nghị, văn hóa của các tỉnh thành phố.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 36/40 ---
❓ Câu hỏi: Đầu ra - tỷ trọng là bao nhiêu?

/tmp/ipykernel_6711/1089340801.py:109: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 37/40 ---
❓ Câu hỏi: Đầu ra - phương thức thanh toán là gì?

/tmp/ipykernel_6711/1089340801.py:109: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 38/40 ---
❓ Câu hỏi: Nhận xét tổng quan về hoạt động kinh doanh là gì?

/tmp/ipykernel_6711/1089340801.py:109: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Khách hàng có 3 nhà máy, lắp ráp & thi công vách kính mặt dựng tại các tòa nhà cao tầng. Nhôm thanh được nhập về => cắt theo kích thước khung kính => lắp ráp & bắt vít khung nhôm => bơm keo => đóng gói chuyển ra công trường. Tại công trường: lắp đặt bản mã sau khi thi công => lắp đặt các unit được chuyển từ nhà máy vào bản mã đặt sẵn tại công trình. Phần lớn ký trực tiếp với chủ đầu tư, một số trường hợp ký với tổng thầu & CAG là nhà thầu do CĐT chỉ định. Công ty ít ký hợp đồng với tư cách nhà thầu phụ.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 39/40 ---
❓ Câu hỏi: Phân tích cung cầu ngành là gì?

/tmp/ipykernel_6711/1089340801.py:109: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 40/40 ---
❓ Câu hỏi: Nhận xét về thông tin ngành là gì?

/tmp/ipykernel_6711/1089340801.py:109: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Khách hàng có 3 nhà máy lắp ráp & thi công vách kính mặt dựng tại các tòa nhà cao tầng. Nhôm thanh được nhập về, cắt theo kích thước khung kính, lắp ráp & bắt vít khung nhôm, bơm keo, đóng gói chuyển ra công trường. Tại công trường, lắp đặt bản mã sau khi thi công, lắp đặt các unit được chuyển từ nhà máy vào bản mã đặt sẵn tại công trình. Các nhà máy sản xuất nhôm thanh & kính không màu trong nước. Các công ty thương mại chuyên nhập khẩu nhôm thanh (các mã kích thước lớn không sản xuất trong nước) và kính màu (trong nước chưa sản xuất được). Phần lớn ký trực tiếp với chủ đầu tư, một số trường hợp ký với tổng thầu & CAG là nhà thầu do CĐT chỉ định. Dân dụng: các tòa nhà văn phòng, trung tâm thương mại. Ngân sách nhà nước: các tòa nhà ủy ban, trung tâm hành chính, hội nghị, văn hóa của các tỉnh thành phố. Các mã kích thước nhỏ: có thể nhập hàng sản xuất trong nước. Các mã kích thước lớn: trong nước ko sản xuất => hàng nhập khẩu Trung Quốc. Với hàng nguồn gốc nhập khẩu, công ty thường mua thông qua các đơn vị chuyên nhập phôi kính do nếu nhập khẩu trực tiếp sẽ không đáp ứng về chi phí & tiến độ. Kính không màu: có thể nhập hàng sản xuất trong nước.
----------------------------------------


✅ Đã thu thập xong toàn bộ dữ liệu (answer, context).

,question,answer,contexts
0,Tên đầy đủ của khách hàng là gì?,CÔNG TY CỔ PHẦN MẶT DỰNG CAG,[*(Áp dụng cho khoản tín dụng món/hạn mức tín ...
1,Số giấy phép đăng ký kinh doanh của khách hàng...,Số 0101442420 do Phòng Đăng ký kinh doanh -- S...,[*(Áp dụng cho khoản tín dụng món/hạn mức tín ...
2,ID khách hàng là gì?,ID khách hàng: 22079986,[*(Áp dụng cho khoản tín dụng món/hạn mức tín ...
3,Phân khúc của khách hàng là gì?,"Dân dụng: các tòa nhà văn phòng, trung tâm thư...","[---\n\n**Hà Nội, Ngày 09 tháng 04 năm 2024**\..."
4,Loại khách hàng là gì?,CAG,[**Nhà máy miền Nam:**\n- Địa điểm: Đồng Nai\n...

✅ Đã lưu kết quả vào file: output_parsing/generated_data_for_eval(full_raw_input_claude_parsing).json

In [ ]:
# ==============================================================================
# CELL MỚI: THỰC HIỆN ĐÁNH GIÁ BẰNG RAGAS
# ==============================================================================
from utils.ragas_evaluation import RagasEvaluator
import pandas as pd
from pathlib import Path
import json
# 1. Khởi tạo Evaluator
# Đảm bảo GOOGLE_API_KEY đã được định nghĩa ở cell trên
GOOGLE_API_KEYS = [ "AIzaSyAWtCSrLhJDZGF1ArOSS0o7Iy_zMG42810",
                    "AIzaSyCaKzwEjW0XxJAuZ9XdzI6rHkifHkA0eNY",
                    "AIzaSyBH8O5IfqYrJ5wtWnmUC21IfMjzJCrTm3I",
                    "AIzaSyDtBIjTSfbvuEsobNwjtdyi9gVpDrCaWPM",
                    "AIzaSyAD_58r3fQhcTOE6qQS1YlR3iJ_ZnGKy10",
                    "AIzaSyCtAz9maZ9usoxEHhhFocHW07WM4IbgOXo",
                    "AIzaSyCI8QGQrVUgr_FrFLttDs0fP4VyJyPXoec",
                    "AIzaSyBPglAFlDOf97drnNAplHIIsjgvsfzezsI",
                    "AIzaSyDNosIJZjXd2tzm7_VKxK5uFTBmoPuHXkc"]

# GOOGLE_API_KEYS = ["AIzaSyCaKzwEjW0XxJAuZ9XdzI6rHkifHkA0eNY"]  

evaluator = RagasEvaluator(list_of_api_keys=GOOGLE_API_KEYS)

# load generated data từ file JSON
generated_data_file = Path('output_parsing/generated_data_for_eval(full_raw_input_claude_parsing).json')
if not generated_data_file.exists():
    print(f"❌ Lỗi: Không tìm thấy file {generated_data_file}. Vui lòng chạy bước thu thập dữ liệu trước.")
else:
    with open(generated_data_file, 'r', encoding='utf-8') as f:
        generated_data_for_eval = json.load(f)
        
# 2. Tải dataset cơ sở (chứa question và ground_truth)
base_data = evaluator.load_base_dataset('/root/chatbot1/chatbot_document/backend/schemas/ragasdf_base.json')

# 3. Chuẩn bị dataset hoàn chỉnh bằng cách kết hợp base_data và generated_data
eval_dataset = evaluator.prepare_evaluation_dataset(
    base_data=base_data,
    generated_data=generated_data_for_eval # Sử dụng kết quả từ cell trước
)

# 4. Xuất file dataset RAGAS hoàn chỉnh ra Excel để kiểm tra
if eval_dataset:
    ragas_df = eval_dataset.to_pandas()
    ragas_df['context_count'] = ragas_df['contexts'].apply(len)
    output_df_path = "new/ragasdf/ragas_dataset_for_evaluation(full_raw_input_claude_parsing).xlsx"
    os.makedirs(Path(output_df_path).parent, exist_ok=True)
    ragas_df.to_excel(output_df_path, index=False)
    print(f"💾 Đã xuất file dataset RAGAS hoàn chỉnh ra: {output_df_path}")
    print("Đây là 5 dòng đầu tiên của dataset sẽ được đánh giá:")
    display(ragas_df.head())
    
# 5. Chạy đánh giá
if eval_dataset:
    results_df = evaluator.run_evaluation(eval_dataset)

    if results_df is not None:
        # 6. Hiển thị và lưu báo cáo
        print("\n\n--- 📊 KẾT QUẢ ĐÁNH GIÁ CHI TIẾT ---")
        display(results_df)

        evaluator.save_report(results_df, "/root/chatbot1/chatbot_document/backend/new/evaluation_reports", "ragas_report(full_raw_input_claude_parsing).xlsx")
    else:
        print("❌ Đánh giá không trả về kết quả.")
else:
    print("❌ Không thể tạo dataset để đánh giá.")

🚀 Khởi tạo RagasEvaluator (có Retry & Key Switching)...

flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.

✅ LLM và Embeddings đã sẵn sàng.
📋 Đã định nghĩa 5 metrics: ['faithfulness', 'context_precision', 'context_recall', 'answer_correctness', 'semantic_similarity']
📁 Đã tạo thư mục báo cáo: evaluation_reports
📂 Đang tải base dataset từ: /root/chatbot1/chatbot_document/backend/schemas/ragasdf_base.json
✅ Tải thành công 40 mẫu.
🔄 Đang chuẩn bị dataset để đánh giá...
✅ Đã chuẩn hóa cột 'contexts' với kiểu dữ liệu: <class 'list'>
✅ Đã tạo thành công dataset với 40 mẫu để đánh giá.
✅ Kiểu dữ liệu của cột 'contexts' đã được xác nhận là: <class 'list'>
✅ Sau khi loại bỏ null/empty, còn 15 mẫu.
✅ Đã thêm cột 'reference' từ ground_truths.
💾 Đã xuất file dataset RAGAS hoàn chỉnh ra: new/ragasdf/ragas_dataset_for_evaluation(full_raw_input_claude_parsing).xlsx
Đây là 5 dòng đầu tiên của dataset sẽ được đánh giá:

,question,ground_truths,answer,contexts,reference,__index_level_0__,context_count
0,Tên đầy đủ của khách hàng là gì?,[CÔNG TY CỔ PHẦN MẶT DỰNG CAG],CÔNG TY CỔ PHẦN MẶT DỰNG CAG,[*(Áp dụng cho khoản tín dụng món/hạn mức tín ...,CÔNG TY CỔ PHẦN MẶT DỰNG CAG,0,3
1,Số giấy phép đăng ký kinh doanh của khách hàng...,[0101442420],Số 0101442420 do Phòng Đăng ký kinh doanh -- S...,[*(Áp dụng cho khoản tín dụng món/hạn mức tín ...,0101442420,1,3
2,ID khách hàng là gì?,[22079986],ID khách hàng: 22079986,[*(Áp dụng cho khoản tín dụng món/hạn mức tín ...,22079986,2,3
3,Phân khúc của khách hàng là gì?,[MM],"Dân dụng: các tòa nhà văn phòng, trung tâm thư...","[---\n\n**Hà Nội, Ngày 09 tháng 04 năm 2024**\...",MM,3,3
4,"XHTD của khách hàng là gì?, XHTD là xếp hạng t...",[Aa3],Tôi không tìm thấy thông tin trong tài liệu.,[*(Áp dụng cho khoản tín dụng món/hạn mức tín ...,Aa3,8,3

✅ Dataset schema hợp lệ. Columns: ['question', 'ground_truths', 'answer', 'contexts', 'reference', '__index_level_0__']

🔬 Bắt đầu đánh giá RAGAS trên 15 mẫu với 5 metrics...
📋 Metrics: ['faithfulness', 'context_precision', 'context_recall', 'answer_correctness', 'semantic_similarity']

--- 🔄 Đang đánh giá dòng 1/15 ---
   Q: Tên đầy đủ của khách hàng là gì?...
   A: CÔNG TY CỔ PHẦN MẶT DỰNG CAG...
    🔄 Metric 1/5: faithfulness
    ✅ faithfulness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/5: context_precision
    ✅ context_precision: 0.9999999999
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/5: context_recall
    ✅ context_recall: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/5: answer_correctness
    ✅ answer_correctness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/5: semantic_similarity
    ✅ semantic_similarity: 0.9999999999999999
✅ Đánh giá dòng 1 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 2/15 ---
   Q: Số giấy phép đăng ký kinh doanh của khách hàng là gì?...
   A: Số 0101442420 do Phòng Đăng ký kinh doanh -- Sở Kế hoạch và Đầu tư thành phố Hà Nội cấp, đăng ký lần...
    🔄 Metric 1/5: faithfulness
    ✅ faithfulness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/5: context_precision
    ✅ context_precision: 0.99999999995
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/5: context_recall
    ✅ context_recall: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/5: answer_correctness
    ✅ answer_correctness: 0.44655785458834957
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/5: semantic_similarity
    ✅ semantic_similarity: 0.5862314183533981
✅ Đánh giá dòng 2 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 3/15 ---
   Q: ID khách hàng là gì?...
   A: ID khách hàng: 22079986...
    🔄 Metric 1/5: faithfulness
    ✅ faithfulness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/5: context_precision
    ✅ context_precision: 0.9999999999
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/5: context_recall
    ✅ context_recall: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/5: answer_correctness
    ✅ answer_correctness: 0.9328599038371919
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/5: semantic_similarity
    ✅ semantic_similarity: 0.7314396153487673
✅ Đánh giá dòng 3 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 4/15 ---
   Q: Phân khúc của khách hàng là gì?...
   A: Dân dụng: các tòa nhà văn phòng, trung tâm thương mại.
Ngân sách nhà nước: các tòa nhà ủy ban, trung...
    🔄 Metric 1/5: faithfulness
    ✅ faithfulness: 0.875
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/5: context_precision
    ✅ context_precision: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/5: context_recall
    ✅ context_recall: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/5: answer_correctness
    ✅ answer_correctness: 0.07807420887423747
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/5: semantic_similarity
    ✅ semantic_similarity: 0.31229683549694986
✅ Đánh giá dòng 4 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 5/15 ---
   Q: XHTD của khách hàng là gì?, XHTD là xếp hạng tín dụng của khách hàng và thường có các giá trị như Aa...
   A: Tôi không tìm thấy thông tin trong tài liệu....
    🔄 Metric 1/5: faithfulness
    ✅ faithfulness: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/5: context_precision
    ✅ context_precision: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/5: context_recall
    ✅ context_recall: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/5: answer_correctness
    ✅ answer_correctness: 0.10361206488089028
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/5: semantic_similarity
    ✅ semantic_similarity: 0.4144482595235611
✅ Đánh giá dòng 5 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 6/15 ---
   Q: Ngày thành lập công ty là ngày nào?...
   A: Ngày 19 tháng 01 năm 2004....
    🔄 Metric 1/5: faithfulness
    ✅ faithfulness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/5: context_precision
    ✅ context_precision: 0.9999999999
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/5: context_recall
    ✅ context_recall: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/5: answer_correctness
    ✅ answer_correctness: 0.9737606697663505
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/5: semantic_similarity
    ✅ semantic_similarity: 0.8950426790654017
✅ Đánh giá dòng 6 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 7/15 ---
   Q: Địa chỉ đăng ký kinh doanh của công ty là gì?...
   A: Lô CN4 - 2.1, KCN Thạch Thất, Thị Trấn Quốc Oai, Huyện Quốc Oai, Thành phố Hà Nội, Việt Nam...
    🔄 Metric 1/5: faithfulness
    ✅ faithfulness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/5: context_precision
    ✅ context_precision: 0.99999999995
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/5: context_recall
    ✅ context_recall: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/5: answer_correctness
    ✅ answer_correctness: 0.9276087497584726
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/5: semantic_similarity
    ✅ semantic_similarity: 0.9831622717611634
✅ Đánh giá dòng 7 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 8/15 ---
   Q: Người đại diện theo pháp luật của công ty là ai?...
   A: Họ và tên: ĐÀO CÔNG DUY
Chức danh: Tổng giám đốc...
    🔄 Metric 1/5: faithfulness
    ✅ faithfulness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/5: context_precision
    ✅ context_precision: 0.9999999999666667
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/5: context_recall
    ✅ context_recall: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/5: answer_correctness
    ✅ answer_correctness: 0.703861721443023
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/5: semantic_similarity
    ✅ semantic_similarity: 0.8154468857720916
✅ Đánh giá dòng 8 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 9/15 ---
   Q: Khách hàng có kinh doanh ngành nghề có điều kiện không?...
   A: Tôi không tìm thấy thông tin trong tài liệu....
    🔄 Metric 1/5: faithfulness
    ✅ faithfulness: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/5: context_precision
    ✅ context_precision: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/5: context_recall
    ✅ context_recall: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/5: answer_correctness
    ✅ answer_correctness: 0.11092360771308635
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/5: semantic_similarity
    ✅ semantic_similarity: 0.4436944308523454
✅ Đánh giá dòng 9 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 10/15 ---
   Q: Thông tin chi tiết về ban lãnh đạo công ty là gì. Hãy liệt kê đầy đủ tên các thành viên, chức vụ, tỉ...
   A: - Đào Công Duy, Tổng giám đốc, 90%
- Thái Thị Kim Dung, 8%
- Đào Công Dũng, 2%...
    🔄 Metric 1/5: faithfulness
    ✅ faithfulness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/5: context_precision
    ✅ context_precision: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/5: context_recall
    ✅ context_recall: 0.3333333333333333
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/5: answer_correctness
    ✅ answer_correctness: 0.7839211373812809
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/5: semantic_similarity
    ✅ semantic_similarity: 0.7356845495251232
✅ Đánh giá dòng 10 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 11/15 ---
   Q: Thông tin chi tiết về đầu vào sản xuất kinh doanh là gì?...
   A: Nhôm thanh:
- Các mã kích thước nhỏ: có thể nhập hàng sản xuất trong nước
- Các mã kích thước lớn: t...
    🔄 Metric 1/5: faithfulness
    ✅ faithfulness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/5: context_precision
    ✅ context_precision: 0.9999999999
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/5: context_recall
    ✅ context_recall: 0.6666666666666666
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/5: answer_correctness
    ✅ answer_correctness: 0.6290004117284875
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/5: semantic_similarity
    ✅ semantic_similarity: 0.8796380105503141
✅ Đánh giá dòng 11 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 12/15 ---
   Q: Lĩnh vực kinh doanh của công ty là gì?...
   A: Tôi không tìm thấy thông tin trong tài liệu....
    🔄 Metric 1/5: faithfulness
    ✅ faithfulness: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/5: context_precision
    ✅ context_precision: 0.99999999995
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/5: context_recall
    ✅ context_recall: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/5: answer_correctness
    ✅ answer_correctness: 0.05799574081425449
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/5: semantic_similarity
    ✅ semantic_similarity: 0.23198296325701795
✅ Đánh giá dòng 12 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 13/15 ---
   Q: Sản phẩm/dịch vụ của công ty là gì?...
   A: Tôi không tìm thấy thông tin trong tài liệu....
    🔄 Metric 1/5: faithfulness
    ✅ faithfulness: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/5: context_precision
    ✅ context_precision: 0.9999999999
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/5: context_recall
    ✅ context_recall: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/5: answer_correctness
    ✅ answer_correctness: 0.06317551361254023
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/5: semantic_similarity
    ✅ semantic_similarity: 0.2527020544501609
✅ Đánh giá dòng 13 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 14/15 ---
   Q: Đầu vào - mặt hàng là gì?...
   A: Đầu vào là nhôm thanh và phôi kính....
    🔄 Metric 1/5: faithfulness
    ✅ faithfulness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/5: context_precision
    ✅ context_precision: 0.9999999999
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/5: context_recall
    ✅ context_recall: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/5: answer_correctness
    ✅ answer_correctness: 0.9538063013613666
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/5: semantic_similarity
    ✅ semantic_similarity: 0.8152252054454664
✅ Đánh giá dòng 14 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 15/15 ---
   Q: Đầu vào - chi tiết là gì?...
   A: Đầu vào:
- Các nhà máy sản xuất nhôm thanh & kính không màu trong nước
- Các công ty thương mại chuy...
    🔄 Metric 1/5: faithfulness
    ✅ faithfulness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/5: context_precision
    ✅ context_precision: 0.9999999999
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/5: context_recall
    ✅ context_recall: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/5: answer_correctness
    ✅ answer_correctness: 0.6137464304981955
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/5: semantic_similarity
    ✅ semantic_similarity: 0.8186220856291458
✅ Đánh giá dòng 15 hoàn tất.

--- ✅ Tất cả các dòng đã được đánh giá. Tổng hợp kết quả... ---
📊 Kết quả có 15 dòng và 5 cột metrics.


--- 📊 KẾT QUẢ ĐÁNH GIÁ CHI TIẾT ---

,faithfulness,context_precision,context_recall,answer_correctness,semantic_similarity
0,1.000,1.0,1.000000,1.000000,1.000000
1,1.000,1.0,1.000000,0.446558,0.586231
2,1.000,1.0,1.000000,0.932860,0.731440
3,0.875,0.0,0.000000,0.078074,0.312297
4,0.000,0.0,1.000000,0.103612,0.414448
5,1.000,1.0,1.000000,0.973761,0.895043
6,1.000,1.0,1.000000,0.927609,0.983162
7,1.000,1.0,1.000000,0.703862,0.815447
8,0.000,0.0,0.000000,0.110924,0.443694
9,1.000,0.0,0.333333,0.783921,0.735685
10,1.000,1.0,0.666667,0.629000,0.879638
11,0.000,1.0,1.000000,0.057996,0.231983
12,0.000,1.0,0.000000,0.063176,0.252702
13,1.000,1.0,1.000000,0.953806,0.815225
14,1.000,1.0,1.000000,0.613746,0.818622

📁 Đã đảm bảo thư mục tồn tại: /root/chatbot1/chatbot_document/backend/new/evaluation_reports
📊 Tìm thấy 5 metrics trong kết quả: ['faithfulness', 'context_precision', 'context_recall', 'answer_correctness', 'semantic_similarity']
📊 Báo cáo đã được lưu tại: /root/chatbot1/chatbot_document/backend/new/evaluation_reports/ragas_report(full_raw_input_claude_parsing).xlsx
📋 Điểm số trung bình:
   faithfulness: 0.7250
   context_precision: 0.7333
   context_recall: 0.7333
   answer_correctness: 0.5586
   semantic_similarity: 0.6610

## Full + deepseek + claude parsing

In [ ]:
# ==============================================================================
# MỤC ĐÍCH: CHẠY PIPELINE RAG VÀ THU THẬP KẾT QUẢ ĐỂ ĐÁNH GIÁ
# ==============================================================================

import os
import json
from pathlib import Path
from typing import List, Tuple
import time
import uuid
import numpy as np
import pandas as pd
from langchain.schema import Document
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_google_genai import ChatGoogleGenerativeAI
from sentence_transformers import CrossEncoder
from utils.api_key_manager import ApiKeyManager
from qdrant_client import QdrantClient
from qdrant_client.http.models import Distance, VectorParams, PointStruct
from langchain_openai import ChatOpenAI 
# --- CẤU HÌNH ---
DELAY_BETWEEN_CALLS = 10
QDRANT_HOST = "localhost"  
QDRANT_PORT = 6333      
COLLECTION_NAME = "child_chunks_eval_notebook" # Dùng collection name mới để tránh xung đột
GOOGLE_API_KEY = "AIzaSyBPglAFlDOf97drnNAplHIIsjgvsfzezsI" # Thay bằng key của bạn

# --- KHỞI TẠO CÁC MODEL ---
print("🧠 Đang khởi tạo các model RAG...")
embedding_model = HuggingFaceEmbeddings(
    model_name="jinaai/jina-embeddings-v3",
    model_kwargs={"device": "cpu", "trust_remote_code": True}
)
# llm_client = ChatGoogleGenerativeAI(model="gemini-2.0-flash", google_api_key=GOOGLE_API_KEY, temperature=0)
try:
    deepseek_llm_client = ChatOpenAI(
        model="deepseek-chat",  
        api_key='',
        base_url="https://api.deepseek.com/v1",
        temperature=0.3,    
    )
    print("✅ DeepSeek client đã sẵn sàng.")
except Exception as e:
    print(f"❌ Lỗi khi khởi tạo DeepSeek client: {e}")
    deepseek_llm_client = None

reranker_model = CrossEncoder('BAAI/bge-reranker-large', device='cpu')
qdrant_client = QdrantClient(host=QDRANT_HOST, port=QDRANT_PORT)
print("✅ Các model RAG đã sẵn sàng.")


def clear_qdrant_collection():
    """Xóa collection để đảm bảo dữ liệu mới mỗi lần chạy."""
    try:
        qdrant_client.delete_collection(collection_name=COLLECTION_NAME)
        print(f"✅ Đã xóa collection '{COLLECTION_NAME}' (nếu tồn tại).")
    except Exception:
        pass # Bỏ qua nếu collection không tồn tại

def setup_qdrant_collection(embedding_dim: int):
    """Tạo hoặc tái tạo collection trong Qdrant."""
    try:
        qdrant_client.recreate_collection(
            collection_name=COLLECTION_NAME,
            vectors_config=VectorParams(size=embedding_dim, distance=Distance.COSINE)
        )
        print(f"✅ Đã tạo/tái tạo collection '{COLLECTION_NAME}' trong Qdrant.")
        return True
    except Exception as e:
        print(f"❌ Lỗi khi setup Qdrant collection: {e}")
        return False

def store_child_chunks_in_qdrant(child_chunks: List[Document], child_embeddings: np.ndarray):
    """Lưu child chunks và embeddings vào Qdrant."""
    points = []
    for chunk, emb in zip(child_chunks, child_embeddings):
        payload = {
            "content": chunk.page_content,
            "parent_id": chunk.metadata.get("parent_id"),
            "parent_content": chunk.metadata.get("parent_content"),
            "source": chunk.metadata.get("source", "unknown")
        }
        points.append(PointStruct(id=str(uuid.uuid4()), vector=emb.tolist(), payload=payload))
    qdrant_client.upsert(collection_name=COLLECTION_NAME, points=points, wait=True)
    print(f"✅ Đã lưu {len(points)} child chunks vào Qdrant.")

def setup_small_to_big_data_with_qdrant(markdown_content: str):
    """Chuẩn bị dữ liệu cho chiến lược Small-to-Big và lưu vào Qdrant."""
    print("--- Bước 1: Chuẩn bị dữ liệu Small-to-Big với Qdrant ---")
    parent_splitter = RecursiveCharacterTextSplitter(chunk_size=2000, chunk_overlap=200)
    child_splitter = RecursiveCharacterTextSplitter(chunk_size=400, chunk_overlap=50)
    parent_chunks = parent_splitter.create_documents([markdown_content])
    print(f"✅ Đã tạo {len(parent_chunks)} parent chunks (đoạn văn lớn).")

    all_child_chunks = []
    for i, p_chunk in enumerate(parent_chunks):
        child_texts = child_splitter.split_text(p_chunk.page_content)
        for text in child_texts:
            all_child_chunks.append(Document(page_content=text, metadata={"parent_id": i, "parent_content": p_chunk.page_content}))
    print(f"✅ Đã tạo {len(all_child_chunks)} child chunks (câu nhỏ) từ các parent.")
            
    sample_embedding = embedding_model.embed_query("test")
    if not setup_qdrant_collection(len(sample_embedding)): 
        return None, False
    
    print("🧠 Đang embedding các child chunks...")
    child_contents = [c.page_content for c in all_child_chunks]
    child_embeddings = np.array(embedding_model.embed_documents(child_contents))
    print("✅ Embedding child chunks hoàn tất!")
    
    store_child_chunks_in_qdrant(all_child_chunks, child_embeddings)
    return parent_chunks, True

# <<< CẢI TIẾN 1: Đổi tên và sửa hàm để trả về List[str] >>>
def retrieve_context_list(query: str, top_k_final: int = 3, retrieve_k_children: int = 15) -> List[str]:
    """
    Mô phỏng pipeline RAG nâng cao và trả về một DANH SÁCH các context liên quan nhất.
    """
    query_embedding = embedding_model.embed_query(query)
    search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)
    
    candidate_parents = {hit.payload["parent_content"] for hit in search_results if hit.payload and "parent_content" in hit.payload}
    
    if not candidate_parents: return [] # Trả về list rỗng
    
    parent_contents = list(candidate_parents)
    pairs = [(query, content) for content in parent_contents]
    scores = reranker_model.predict(pairs)
    reranked_results = sorted(zip(scores, parent_contents), key=lambda x: x[0], reverse=True)
    
    # <<< THAY ĐỔI: Trả về danh sách các chuỗi thay vì một chuỗi duy nhất >>>
    final_docs = [content for _, content in reranked_results[:top_k_final]]
    return final_docs
    
def answer_with_context(query: str, context_list: List[str]) -> str: # <<< Nhận vào list
    """Sử dụng LLM để trả lời câu hỏi dựa trên context được cung cấp."""
    # <<< THAY ĐỔI: Nối lại danh sách context thành một chuỗi duy nhất cho prompt >>>
    full_context_str = "\n\n---\n\n".join(context_list)
    
    prompt_template = f"""Bạn là một trợ lý AI chuyên nghiệp, chỉ trả lời dựa trên context được cung cấp.
Trả lời câu hỏi một cách ngắn gọn và chính xác. Nếu không có thông tin trong context, hãy nói "Tôi không tìm thấy thông tin trong tài liệu."

Context:
---
{full_context_str}
---

Câu hỏi: {query}

Trả lời:
"""
    response = deepseek_llm_client.invoke(prompt_template)
    return response.content

# --- CHẠY PIPELINE VÀ THU THẬP DỮ LIỆU ---

generated_data_for_eval = [] 

markdown_file_path = Path("output_parsing/claude_raw_input.md")

if not markdown_file_path.exists():
    print(f"❌ Lỗi: Không tìm thấy file {markdown_file_path}. Vui lòng chạy bước parsing trước.")
else:
    with open(markdown_file_path, 'r', encoding='utf-8') as f:
        markdown_content = f.read()

    clear_qdrant_collection()
    parent_chunks, success = setup_small_to_big_data_with_qdrant(markdown_content)
    
    if not success:
        print("❌ Không thể setup dữ liệu với Qdrant. Dừng chương trình.")
    else:
        # Lấy câu hỏi từ file ragasdf_base.json
        with open('/root/chatbot1/chatbot_document/backend/schemas/ragasdf_base.json', 'r', encoding='utf-8') as f:
            template4_queries_data = json.load(f)
        template4_queries = [item['question'] for item in template4_queries_data]

        print(f"\n\n=== 🚀 BẮT ĐẦU CHẠY RAG VÀ THU THẬP DỮ LIỆU TRÊN {len(template4_queries)} CÂU HỎI ===")
        
        for i, query in enumerate(template4_queries, 1):
            print(f"\n--- Query {i}/{len(template4_queries)} ---")
            print(f"❓ Câu hỏi: {query}")
            
            # context = simulate_s2b_with_reranking_qdrant(query)
            context_list = retrieve_context_list(query)
            # answer = answer_with_context(query, context)
            answer = answer_with_context(query, context_list) 
            print(f"✅ Câu trả lời của hệ thống: {answer}")
            
            # Lưu kết quả vào danh sách
            generated_data_for_eval.append({
                "question": query,
                "answer": answer,
                "contexts": context_list 
            })
            
            print("-" * 40)
            if i < len(template4_queries):
                print(f"⏳ Đợi {DELAY_BETWEEN_CALLS} giây...")
                time.sleep(DELAY_BETWEEN_CALLS)

        print("\n\n✅ Đã thu thập xong toàn bộ dữ liệu (answer, context).")
        display(pd.DataFrame(generated_data_for_eval).head())
        # Lưu kết quả vào file JSON
        output_file = Path('output_parsing/generated_data_for_eval(full_raw_input_claude_parsing_deepseek).json')
        output_file.parent.mkdir(parents=True, exist_ok=True)
        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump(generated_data_for_eval, f, ensure_ascii=False, indent=4)
        print(f"✅ Đã lưu kết quả vào file: {output_file}")

🧠 Đang khởi tạo các model RAG...

WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.

✅ DeepSeek client đã sẵn sàng.

/tmp/ipykernel_6711/3513921100.py:50: UserWarning: Qdrant client version 1.15.1 is incompatible with server version 1.7.2. Major versions should match and minor version difference must not exceed 1. Set check_compatibility=False to skip version check.
  qdrant_client = QdrantClient(host=QDRANT_HOST, port=QDRANT_PORT)

✅ Các model RAG đã sẵn sàng.
✅ Đã xóa collection 'child_chunks_eval_notebook' (nếu tồn tại).
--- Bước 1: Chuẩn bị dữ liệu Small-to-Big với Qdrant ---
✅ Đã tạo 19 parent chunks (đoạn văn lớn).
✅ Đã tạo 102 child chunks (câu nhỏ) từ các parent.

/tmp/ipykernel_6711/3513921100.py:65: DeprecationWarning: `recreate_collection` method is deprecated and will be removed in the future. Use `collection_exists` to check collection existence and `create_collection` instead.
  qdrant_client.recreate_collection(

✅ Đã tạo/tái tạo collection 'child_chunks_eval_notebook' trong Qdrant.
🧠 Đang embedding các child chunks...
✅ Embedding child chunks hoàn tất!
✅ Đã lưu 102 child chunks vào Qdrant.


=== 🚀 BẮT ĐẦU CHẠY RAG VÀ THU THẬP DỮ LIỆU TRÊN 40 CÂU HỎI ===

--- Query 1/40 ---
❓ Câu hỏi: Tên đầy đủ của khách hàng là gì?

/tmp/ipykernel_6711/3513921100.py:122: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Tên đầy đủ của khách hàng là **CÔNG TY CỔ PHẦN MẶT DỰNG CAG**.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 2/40 ---
❓ Câu hỏi: Số giấy phép đăng ký kinh doanh của khách hàng là gì?

/tmp/ipykernel_6711/3513921100.py:122: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Số giấy phép đăng ký kinh doanh của khách hàng là **0101442420**.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 3/40 ---
❓ Câu hỏi: ID khách hàng là gì?

/tmp/ipykernel_6711/3513921100.py:122: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: ID khách hàng là **22079986**.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 4/40 ---
❓ Câu hỏi: Phân khúc của khách hàng là gì?

/tmp/ipykernel_6711/3513921100.py:122: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Phân khúc khách hàng của các doanh nghiệp được đề cập trong context bao gồm:
- **Sunspace**: Chủ yếu thi công các dự án của Vingroup và các tổng thầu lớn (Hòa Bình, BIM group).
- **CAG**: Khách hàng từ ngân sách nhà nước (Bộ ban ngành, ACV, TKV, bệnh viện) và chủ đầu tư tư nhân.
- **Eurowindow**: Khách hàng từ ngân sách nhà nước (Bộ ban ngành, trụ sở cơ quan các tỉnh, ACV, bệnh viện) và chủ đầu tư tư nhân.
- **BM Windows**: Chủ yếu chủ đầu tư tư nhân và dự án ngoài nước.

Nếu cần phân khúc cụ thể hơn cho một doanh nghiệp nào đó, vui lòng chỉ rõ.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 5/40 ---
❓ Câu hỏi: Loại khách hàng là gì?

/tmp/ipykernel_6711/3513921100.py:122: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Loại khách hàng của CÔNG TY CỔ PHẦN MẶT DỰNG CAG là:
- NSNN: Bộ ban ngành, ACV, TKV, bệnh viện
- CĐT tư nhân
----------------------------------------
⏳ Đợi 10 giây...

--- Query 6/40 ---
❓ Câu hỏi: Ngành nghề hoạt động kinh doanh của khách hàng là gì?

/tmp/ipykernel_6711/3513921100.py:122: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Ngành nghề hoạt động kinh doanh của khách hàng là sản xuất và thi công các sản phẩm nhôm kính, bao gồm vách kính mặt dựng, cửa nhôm, cabin tắm, lan can kính, cửa nhựa uPVC, cửa kính tự động, cửa cuốn, và các hệ thống khác liên quan đến nhôm kính.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 7/40 ---
❓ Câu hỏi: Mục đích báo cáo là gì?

/tmp/ipykernel_6711/3513921100.py:122: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 8/40 ---
❓ Câu hỏi: Kết quả phân luồng của khách hàng là gì?

/tmp/ipykernel_6711/3513921100.py:122: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 9/40 ---
❓ Câu hỏi: XHTD của khách hàng là gì?, XHTD là xếp hạng tín dụng của khách hàng và thường có các giá trị như Aa3, Baa2, v.v.

/tmp/ipykernel_6711/3513921100.py:122: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 10/40 ---
❓ Câu hỏi: Ngày thành lập công ty là ngày nào?

/tmp/ipykernel_6711/3513921100.py:122: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Ngày thành lập công ty là ngày 19 tháng 01 năm 2004.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 11/40 ---
❓ Câu hỏi: Địa chỉ đăng ký kinh doanh của công ty là gì?

/tmp/ipykernel_6711/3513921100.py:122: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Địa chỉ đăng ký kinh doanh của công ty là: Lô CN4 - 2.1, KCN Thạch Thất, Thị Trấn Quốc Oai, Huyện Quốc Oai, Thành phố Hà Nội, Việt Nam.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 12/40 ---
❓ Câu hỏi: Người đại diện theo pháp luật của công ty là ai?

/tmp/ipykernel_6711/3513921100.py:122: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Người đại diện theo pháp luật của công ty là **ĐÀO CÔNG DUY**, chức danh Tổng giám đốc.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 13/40 ---
❓ Câu hỏi: Khách hàng có kinh doanh ngành nghề có điều kiện không?

/tmp/ipykernel_6711/3513921100.py:122: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 14/40 ---
❓ Câu hỏi: Thông tin chi tiết về ban lãnh đạo công ty là gì. Hãy liệt kê đầy đủ tên các thành viên, chức vụ, tỉ lệ góp vốn nếu có?

/tmp/ipykernel_6711/3513921100.py:122: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Thông tin ban lãnh đạo công ty từ context:

1. **Đào Công Duy**
   - Chức vụ: Tổng giám đốc
   - Tỷ lệ góp vốn: 90%
   - CCCD: 034067001074

2. **Thái Thị Kim Dung**
   - Tỷ lệ góp vốn: 8%
   - CCCD: 040174000053

3. **Đào Công Dũng**
   - Tỷ lệ góp vốn: 2%
   - CMND: 017368377

*Lưu ý: Context không đề cập chức vụ cụ thể của Thái Thị Kim Dung và Đào Công Dũng trong ban lãnh đạo.*
----------------------------------------
⏳ Đợi 10 giây...

--- Query 15/40 ---
❓ Câu hỏi: Thông tin chi tiết về đầu vào sản xuất kinh doanh là gì?

/tmp/ipykernel_6711/3513921100.py:122: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Thông tin chi tiết về đầu vào sản xuất kinh doanh bao gồm:

1. **Nhôm thanh:**
   - Các mã kích thước nhỏ: nhập hàng sản xuất trong nước.
   - Các mã kích thước lớn: nhập khẩu từ Trung Quốc (trong nước không sản xuất).

2. **Phôi kính:**
   - Kính không màu: có thể nhập hàng sản xuất trong nước.
   - Kính màu: nhập khẩu (trong nước chưa sản xuất được), thường mua thông qua các đơn vị chuyên nhập khẩu do không đáp ứng được chi phí và tiến độ nếu nhập trực tiếp.

Nguồn cung cấp:
- Các nhà máy sản xuất nhôm thanh và kính không màu trong nước.
- Các công ty thương mại chuyên nhập khẩu nhôm thanh và kính màu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 16/40 ---
❓ Câu hỏi: Thông tin chi tiết về đầu ra sản xuất kinh doanh là gì?

/tmp/ipykernel_6711/3513921100.py:122: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 17/40 ---
❓ Câu hỏi: Nhận xét về thông tin khách hàng là gì?

/tmp/ipykernel_6711/3513921100.py:122: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Thông tin khách hàng CÔNG TY CỔ PHẦN MẶT DỰNG CAG được cung cấp đầy đủ và chi tiết, bao gồm:
- **Tên, ID khách hàng, giấy CNĐKDN, địa chỉ liên hệ.**
- **Người đại diện theo pháp luật:** Tổng Giám đốc Đào Công Duy (không có người đại diện ủy quyền).
- **Cổ đông chính:** Đào Công Duy (90%), Thái Thị Kim Dung (8%), Đào Công Dũng (2%).
- **Không có thông tin về bên bảo đảm hoặc người có liên quan.**

Thông tin rõ ràng, phù hợp với hồ sơ tín dụng.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 18/40 ---
❓ Câu hỏi: Nhận xét về pháp lý/GPKD có điều kiện là gì?

/tmp/ipykernel_6711/3513921100.py:122: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 19/40 ---
❓ Câu hỏi: Nhận xét về chủ doanh nghiệp/ban lãnh đạo là gì?

/tmp/ipykernel_6711/3513921100.py:122: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Chủ doanh nghiệp (Tổng giám đốc Đào Công Duy) có kinh nghiệm trên 10 năm (sinh năm 1967, đăng ký doanh nghiệp từ năm 2004), đáp ứng tiêu chí **Khuyến khích (KK)** theo bảng tiêu chí về kinh nghiệm quản lý (giám đốc trên 10 năm). Thông tin không đề cập đến kinh nghiệm của trưởng phòng kế hoạch, kỹ thuật hoặc kế toán trưởng.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 20/40 ---
❓ Câu hỏi: Nhận xét về KYC là gì?

/tmp/ipykernel_6711/3513921100.py:122: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 21/40 ---
❓ Câu hỏi: Lĩnh vực kinh doanh của công ty là gì?

/tmp/ipykernel_6711/3513921100.py:122: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Dựa trên context, các công ty được đề cập hoạt động trong lĩnh vực sản xuất và cung cấp các sản phẩm liên quan đến nhôm kính, mặt dựng, cửa, vách kính, và các hệ thống xây dựng khác. Cụ thể:

- **Sunspace**: Sản xuất vách kính, mặt dựng, cửa nhôm, cabin tắm, lan can kính, cửa nhựa uPVC, cửa kính tự động, cửa cuốn.
- **CAG**: Sản xuất mặt dựng kính, tấm ốp Alu, cửa kính (tự động, mở quay, đi lùa), cửa sổ, lam chắn nắng, cầu thang kính.
- **Eurowindow**: Sản xuất cửa uPVC, cửa gỗ, nội thất, cửa cuốn, cửa chống cháy, cửa nhôm, hệ vách nhôm kính, kính.
- **BM Windows**: Sản xuất mặt dựng nhôm kính và hệ thống cửa.

Lĩnh vực kinh doanh chung là **sản xuất và cung cấp vật liệu xây dựng, đặc biệt là hệ nhôm kính và các sản phẩm liên quan**.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 22/40 ---
❓ Câu hỏi: Sản phẩm/dịch vụ của công ty là gì?

/tmp/ipykernel_6711/3513921100.py:122: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Dựa trên context, sản phẩm/dịch vụ của các công ty được liệt kê như sau:

**Sunspace:**
- Hệ thống vách kính mặt dựng
- Hệ thống cửa nhôm – vách kính
- Hệ thống cabin tắm và lan can kính
- Hệ thống cửa nhựa uPVC
- Hệ thống cửa kính tự động
- Hệ thống cửa cuốn

**CAG:**
- Hệ thống mặt dựng kính
- Tấm ốp Alu
- Hệ thống cửa kính (tự động, mở quay, đi lùa), cửa sổ (mở quay, mở hắt)
- Lam chắn nắng, cầu thang kính

**Eurowindow:**
- Cửa uPVC
- Cửa gỗ, nội thất, cửa cuốn, cửa chống cháy
- Cửa nhôm và hệ vách nhôm kính lớn
- Kính

**BM Windows:**
- Mặt dựng nhôm kính
- Hệ thống cửa
----------------------------------------
⏳ Đợi 10 giây...

--- Query 23/40 ---
❓ Câu hỏi: Tỷ trọng doanh thu năm N-1 (%) là bao nhiêu?

/tmp/ipykernel_6711/3513921100.py:122: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 24/40 ---
❓ Câu hỏi: Tỷ trọng doanh thu năm N (%) là bao nhiêu?

/tmp/ipykernel_6711/3513921100.py:122: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 25/40 ---
❓ Câu hỏi: Nhóm mặt hàng của công ty là gì?

/tmp/ipykernel_6711/3513921100.py:122: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 26/40 ---
❓ Câu hỏi: Tỷ trọng doanh thu năm 2023 là bao nhiêu?

/tmp/ipykernel_6711/3513921100.py:122: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 27/40 ---
❓ Câu hỏi: Tỷ trọng doanh thu 10T/2024 là bao nhiêu?

/tmp/ipykernel_6711/3513921100.py:122: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 28/40 ---
❓ Câu hỏi: Mô tả chung về sản phẩm của công ty là gì?

/tmp/ipykernel_6711/3513921100.py:122: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Sản phẩm của các công ty trong ngành nhôm kính bao gồm:
- **Sunspace**: Hệ thống vách kính mặt dựng, cửa nhôm, cabin tắm, lan can kính, cửa nhựa uPVC, cửa kính tự động, cửa cuốn.
- **CAG**: Mặt dựng kính, tấm ốp Alu, cửa kính (tự động, mở quay, lùa), cửa sổ, lam chắn nắng, cầu thang kính.
- **Eurowindow**: Cửa uPVC, cửa gỗ, nội thất, cửa cuốn, cửa chống cháy, cửa nhôm, hệ vách nhôm kính lớn, kính.
- **BM Windows**: Mặt dựng nhôm kính, hệ thống cửa.

*(Tùy vào công ty cụ thể được đề cập trong câu hỏi chi tiết hơn, câu trả lời có thể điều chỉnh phù hợp.)*
----------------------------------------
⏳ Đợi 10 giây...

--- Query 29/40 ---
❓ Câu hỏi: Mô tả lợi thế cạnh tranh của công ty là gì?

/tmp/ipykernel_6711/3513921100.py:122: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 30/40 ---
❓ Câu hỏi: Mô tả năng lực đấu thầu của công ty là gì?

/tmp/ipykernel_6711/3513921100.py:122: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Công ty chủ yếu ký hợp đồng trực tiếp với chủ đầu tư, một số trường hợp ký với tổng thầu và CAG là nhà thầu do chủ đầu tư chỉ định. Công ty ít ký hợp đồng với tư cách nhà thầu phụ.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 31/40 ---
❓ Câu hỏi: Quy trình vận hành (tóm tắt) của công ty là gì?

/tmp/ipykernel_6711/3513921100.py:122: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 32/40 ---
❓ Câu hỏi: Đầu vào - mặt hàng là gì?

/tmp/ipykernel_6711/3513921100.py:122: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Đầu vào - mặt hàng bao gồm:
1. **Nhôm thanh**:
   - Các mã kích thước nhỏ: sản xuất trong nước.
   - Các mã kích thước lớn: nhập khẩu từ Trung Quốc.
2. **Phôi kính**:
   - Kính không màu: sản xuất trong nước.
   - Kính màu: nhập khẩu thông qua các đơn vị chuyên nhập phôi kính.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 33/40 ---
❓ Câu hỏi: Đầu vào - chi tiết là gì?

/tmp/ipykernel_6711/3513921100.py:122: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Đầu vào của khách hàng bao gồm:
1. **Nhôm thanh**:
   - Các mã kích thước nhỏ: sản xuất trong nước.
   - Các mã kích thước lớn: nhập khẩu từ Trung Quốc.
2. **Phôi kính**:
   - Kính không màu: sản xuất trong nước.
   - Kính màu: nhập khẩu thông qua các đơn vị trung gian do hạn chế về chi phí và tiến độ nếu nhập trực tiếp.

Ngoài ra, khách hàng còn nhập nguyên liệu từ các công ty thương mại chuyên nhập khẩu nhôm thanh và kính màu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 34/40 ---
❓ Câu hỏi: Đầu vào - phương thức thanh toán là gì?

/tmp/ipykernel_6711/3513921100.py:122: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 35/40 ---
❓ Câu hỏi: Đầu ra - kênh phân phối là gì?

/tmp/ipykernel_6711/3513921100.py:122: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Đầu ra - kênh phân phối của công ty bao gồm:
1. Phần lớn ký trực tiếp với chủ đầu tư.
2. Một số trường hợp ký với tổng thầu và CAG là nhà thầu do chủ đầu tư chỉ định.
3. Công ty ít ký hợp đồng với tư cách nhà thầu phụ.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 36/40 ---
❓ Câu hỏi: Đầu ra - tỷ trọng là bao nhiêu?

/tmp/ipykernel_6711/3513921100.py:122: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Tỷ trọng doanh thu với nhóm đầu ra chính được phân loại như sau:
- Khuyến khích (KK): X ≥ 70%
- Bình thường (BT): 50% ≤ X < 70%
- Thận trọng (TT): 30% ≤ X < 50%
- Hạn chế (HC): X < 30%
----------------------------------------
⏳ Đợi 10 giây...

--- Query 37/40 ---
❓ Câu hỏi: Đầu ra - phương thức thanh toán là gì?

/tmp/ipykernel_6711/3513921100.py:122: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Phương thức thanh toán không được đề cập cụ thể trong tài liệu. Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 38/40 ---
❓ Câu hỏi: Nhận xét tổng quan về hoạt động kinh doanh là gì?

/tmp/ipykernel_6711/3513921100.py:122: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Hoạt động kinh doanh của công ty bao gồm sản xuất và lắp ráp vách kính mặt dựng tại các tòa nhà cao tầng với 3 nhà máy ở Hà Nội và Đồng Nai. Công ty chủ yếu ký hợp đồng trực tiếp với chủ đầu tư hoặc tổng thầu, tập trung vào các dự án dân dụng và ngân sách nhà nước. Đầu vào gồm nhôm thanh và phôi kính, một phần nhập khẩu từ Trung Quốc. Dự kiến doanh thu đạt 950 tỷ đồng với lợi nhuận 55 tỷ đồng.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 39/40 ---
❓ Câu hỏi: Phân tích cung cầu ngành là gì?

/tmp/ipykernel_6711/3513921100.py:122: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 40/40 ---
❓ Câu hỏi: Nhận xét về thông tin ngành là gì?

/tmp/ipykernel_6711/3513921100.py:122: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(collection_name=COLLECTION_NAME, query_vector=query_embedding, limit=retrieve_k_children, with_payload=True)

✅ Câu trả lời của hệ thống: Thông tin ngành trong context bao gồm các tiêu chí đánh giá doanh nghiệp sản xuất gỗ (SX Gỗ) và sản xuất xây dựng (SXXD), cụ thể:

1. **SX Gỗ**:
   - Phân loại doanh nghiệp theo doanh thu, điều kiện nhà xưởng/kho hàng, năng lực quản lý và tổ chức sản xuất.
   - Các mức độ từ Khuyến khích (KK) đến Hạn chế (HC) tùy thuộc vào từng tiêu chí.

2. **SXXD**:
   - Định hướng tỷ lệ tài sản đảm bảo cho các dự án dân dụng và công nghiệp, phân theo nhóm 1-4.
   - Thông tin về người góp vốn và người có liên quan (nếu có).

3. **Phương án sử dụng vốn và hiệu quả kinh doanh**:
   - Nhu cầu vốn, dự kiến doanh thu, lợi nhuận, phương án trả nợ.
   - Chi tiết về tài sản bảo đảm và hoạt động kinh doanh (ví dụ: nhà máy, đầu vào/đầu ra sản phẩm).

Nhận xét chung: Thông tin ngành được trình bày chi tiết, có hệ thống, giúp đánh giá rủi ro và tiềm năng của doanh nghiệp trong lĩnh vực sản xuất gỗ và xây dựng.
----------------------------------------


✅ Đã thu thập xong toàn bộ dữ liệu (answer, context).

,question,answer,contexts
0,Tên đầy đủ của khách hàng là gì?,Tên đầy đủ của khách hàng là **CÔNG TY CỔ PHẦN...,[*(Áp dụng cho khoản tín dụng món/hạn mức tín ...
1,Số giấy phép đăng ký kinh doanh của khách hàng...,Số giấy phép đăng ký kinh doanh của khách hàng...,[*(Áp dụng cho khoản tín dụng món/hạn mức tín ...
2,ID khách hàng là gì?,ID khách hàng là **22079986**.,[*(Áp dụng cho khoản tín dụng món/hạn mức tín ...
3,Phân khúc của khách hàng là gì?,Phân khúc khách hàng của các doanh nghiệp được...,"[---\n\n**Hà Nội, Ngày 09 tháng 04 năm 2024**\..."
4,Loại khách hàng là gì?,Loại khách hàng của CÔNG TY CỔ PHẦN MẶT DỰNG C...,[**Nhà máy miền Nam:**\n- Địa điểm: Đồng Nai\n...

✅ Đã lưu kết quả vào file: output_parsing/generated_data_for_eval(full_raw_input_claude_parsing_deepseek).json

In [ ]:
# ==============================================================================
# CELL MỚI: THỰC HIỆN ĐÁNH GIÁ BẰNG RAGAS
# ==============================================================================
from utils.ragas_evaluation import RagasEvaluator
import pandas as pd
from pathlib import Path
import json

# 1. Khởi tạo Evaluator
# Đảm bảo GOOGLE_API_KEY đã được định nghĩa ở cell trên
GOOGLE_API_KEYS = [ "AIzaSyAWtCSrLhJDZGF1ArOSS0o7Iy_zMG42810",
                    "AIzaSyCaKzwEjW0XxJAuZ9XdzI6rHkifHkA0eNY",
                    "AIzaSyBH8O5IfqYrJ5wtWnmUC21IfMjzJCrTm3I",
                    "AIzaSyDtBIjTSfbvuEsobNwjtdyi9gVpDrCaWPM",
                    "AIzaSyAD_58r3fQhcTOE6qQS1YlR3iJ_ZnGKy10",
                    "AIzaSyCtAz9maZ9usoxEHhhFocHW07WM4IbgOXo",
                    "AIzaSyCI8QGQrVUgr_FrFLttDs0fP4VyJyPXoec",
                    "AIzaSyBPglAFlDOf97drnNAplHIIsjgvsfzezsI",
                    "AIzaSyDNosIJZjXd2tzm7_VKxK5uFTBmoPuHXkc"]


evaluator = RagasEvaluator(list_of_api_keys=GOOGLE_API_KEYS)

# load generated data từ file JSON
generated_data_file = Path('output_parsing/generated_data_for_eval(full_raw_input_claude_parsing_deepseek).json')
if not generated_data_file.exists():
    print(f"❌ Lỗi: Không tìm thấy file {generated_data_file}. Vui lòng chạy bước thu thập dữ liệu trước.")
else:
    with open(generated_data_file, 'r', encoding='utf-8') as f:
        generated_data_for_eval = json.load(f)
        
# 2. Tải dataset cơ sở (chứa question và ground_truth)
base_data = evaluator.load_base_dataset('/root/chatbot1/chatbot_document/backend/schemas/ragasdf_base.json')

# 3. Chuẩn bị dataset hoàn chỉnh bằng cách kết hợp base_data và generated_data
eval_dataset = evaluator.prepare_evaluation_dataset(
    base_data=base_data,
    generated_data=generated_data_for_eval # Sử dụng kết quả từ cell trước
)

# 4. Xuất file dataset RAGAS hoàn chỉnh ra Excel để kiểm tra
if eval_dataset:
    ragas_df = eval_dataset.to_pandas()
    ragas_df['context_count'] = ragas_df['contexts'].apply(len)
    output_df_path = "new/ragasdf/ragas_dataset_for_evaluation(full_raw_input_claude_parsing_deepseek).xlsx"
    os.makedirs(Path(output_df_path).parent, exist_ok=True)
    ragas_df.to_excel(output_df_path, index=False)
    print(f"💾 Đã xuất file dataset RAGAS hoàn chỉnh ra: {output_df_path}")
    print("Đây là 5 dòng đầu tiên của dataset sẽ được đánh giá:")
    display(ragas_df.head())
    
# 5. Chạy đánh giá
if eval_dataset:
    results_df = evaluator.run_evaluation(eval_dataset)

    if results_df is not None:
        # 6. Hiển thị và lưu báo cáo
        print("\n\n--- 📊 KẾT QUẢ ĐÁNH GIÁ CHI TIẾT ---")
        display(results_df)

        evaluator.save_report(results_df, "/root/chatbot1/chatbot_document/backend/new/evaluation_reports", "ragas_report(full_raw_input_claude_parsing_deepseek).xlsx")
    else:
        print("❌ Đánh giá không trả về kết quả.")
else:
    print("❌ Không thể tạo dataset để đánh giá.")

🚀 Khởi tạo RagasEvaluator (có Retry & Key Switching)...

flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.

✅ LLM và Embeddings đã sẵn sàng.
📋 Đã định nghĩa 5 metrics: ['faithfulness', 'context_precision', 'context_recall', 'answer_correctness', 'semantic_similarity']
📁 Đã tạo thư mục báo cáo: evaluation_reports
📂 Đang tải base dataset từ: /root/chatbot1/chatbot_document/backend/schemas/ragasdf_base.json
✅ Tải thành công 40 mẫu.
🔄 Đang chuẩn bị dataset để đánh giá...
✅ Đã chuẩn hóa cột 'contexts' với kiểu dữ liệu: <class 'list'>
✅ Đã tạo thành công dataset với 40 mẫu để đánh giá.
✅ Kiểu dữ liệu của cột 'contexts' đã được xác nhận là: <class 'list'>
✅ Sau khi loại bỏ null/empty, còn 16 mẫu.
✅ Đã thêm cột 'reference' từ ground_truths.
💾 Đã xuất file dataset RAGAS hoàn chỉnh ra: new/ragasdf/ragas_dataset_for_evaluation(full_raw_input_claude_parsing_deepseek).xlsx
Đây là 5 dòng đầu tiên của dataset sẽ được đánh giá:

,question,ground_truths,answer,contexts,reference,__index_level_0__,context_count
0,Tên đầy đủ của khách hàng là gì?,[CÔNG TY CỔ PHẦN MẶT DỰNG CAG],Tên đầy đủ của khách hàng là **CÔNG TY CỔ PHẦN...,[*(Áp dụng cho khoản tín dụng món/hạn mức tín ...,CÔNG TY CỔ PHẦN MẶT DỰNG CAG,0,3
1,Số giấy phép đăng ký kinh doanh của khách hàng...,[0101442420],Số giấy phép đăng ký kinh doanh của khách hàng...,[*(Áp dụng cho khoản tín dụng món/hạn mức tín ...,0101442420,1,3
2,ID khách hàng là gì?,[22079986],ID khách hàng là **22079986**.,[*(Áp dụng cho khoản tín dụng món/hạn mức tín ...,22079986,2,3
3,Phân khúc của khách hàng là gì?,[MM],Phân khúc khách hàng của các doanh nghiệp được...,"[---\n\n**Hà Nội, Ngày 09 tháng 04 năm 2024**\...",MM,3,3
4,"XHTD của khách hàng là gì?, XHTD là xếp hạng t...",[Aa3],Tôi không tìm thấy thông tin trong tài liệu.,[*(Áp dụng cho khoản tín dụng món/hạn mức tín ...,Aa3,8,3

✅ Dataset schema hợp lệ. Columns: ['question', 'ground_truths', 'answer', 'contexts', 'reference', '__index_level_0__']

🔬 Bắt đầu đánh giá RAGAS trên 16 mẫu với 5 metrics...
📋 Metrics: ['faithfulness', 'context_precision', 'context_recall', 'answer_correctness', 'semantic_similarity']

--- 🔄 Đang đánh giá dòng 1/16 ---
   Q: Tên đầy đủ của khách hàng là gì?...
   A: Tên đầy đủ của khách hàng là **CÔNG TY CỔ PHẦN MẶT DỰNG CAG**....
    🔄 Metric 1/5: faithfulness
    ✅ faithfulness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/5: context_precision
    ✅ context_precision: 0.9999999999
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/5: context_recall
    ✅ context_recall: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/5: answer_correctness
    ✅ answer_correctness: 0.970742430373841
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/5: semantic_similarity
    ✅ semantic_similarity: 0.8829697214953638
✅ Đánh giá dòng 1 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 2/16 ---
   Q: Số giấy phép đăng ký kinh doanh của khách hàng là gì?...
   A: Số giấy phép đăng ký kinh doanh của khách hàng là **0101442420**....
    🔄 Metric 1/5: faithfulness
    ✅ faithfulness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/5: context_precision
    ✅ context_precision: 0.99999999995
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/5: context_recall
    ✅ context_recall: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/5: answer_correctness
    ✅ answer_correctness: 0.8886192990637152
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/5: semantic_similarity
    ✅ semantic_similarity: 0.5544771962548607
✅ Đánh giá dòng 2 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 3/16 ---
   Q: ID khách hàng là gì?...
   A: ID khách hàng là **22079986**....
    🔄 Metric 1/5: faithfulness
    ✅ faithfulness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/5: context_precision
    ✅ context_precision: 0.9999999999
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/5: context_recall
    ✅ context_recall: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/5: answer_correctness
    ✅ answer_correctness: 0.9233569289284917
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/5: semantic_similarity
    ✅ semantic_similarity: 0.6934277157139668
✅ Đánh giá dòng 3 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 4/16 ---
   Q: Phân khúc của khách hàng là gì?...
   A: Phân khúc khách hàng của các doanh nghiệp được đề cập trong context bao gồm:
- **Sunspace**: Chủ y...
    🔄 Metric 1/5: faithfulness
    ✅ faithfulness: 0.8888888888888888
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/5: context_precision
    ✅ context_precision: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/5: context_recall
    ✅ context_recall: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/5: answer_correctness
    ✅ answer_correctness: 0.09759436704983243
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/5: semantic_similarity
    ✅ semantic_similarity: 0.3903774681993297
✅ Đánh giá dòng 4 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 5/16 ---
   Q: XHTD của khách hàng là gì?, XHTD là xếp hạng tín dụng của khách hàng và thường có các giá trị như Aa...
   A: Tôi không tìm thấy thông tin trong tài liệu....
    🔄 Metric 1/5: faithfulness
    ✅ faithfulness: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/5: context_precision
    ✅ context_precision: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/5: context_recall
    ✅ context_recall: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/5: answer_correctness
    ✅ answer_correctness: 0.10361206488089028
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/5: semantic_similarity
    ✅ semantic_similarity: 0.4144482595235611
✅ Đánh giá dòng 5 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 6/16 ---
   Q: Ngày thành lập công ty là ngày nào?...
   A: Ngày thành lập công ty là ngày 19 tháng 01 năm 2004....
    🔄 Metric 1/5: faithfulness
    ✅ faithfulness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/5: context_precision
    ✅ context_precision: 0.9999999999
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/5: context_recall
    ✅ context_recall: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/5: answer_correctness
    ✅ answer_correctness: 0.8966982397619427
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/5: semantic_similarity
    ✅ semantic_similarity: 0.5867929590477707
✅ Đánh giá dòng 6 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 7/16 ---
   Q: Địa chỉ đăng ký kinh doanh của công ty là gì?...
   A: Địa chỉ đăng ký kinh doanh của công ty là: Lô CN4 - 2.1, KCN Thạch Thất, Thị Trấn Quốc Oai, Huyện Qu...
    🔄 Metric 1/5: faithfulness
    ✅ faithfulness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/5: context_precision
    ✅ context_precision: 0.99999999995
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/5: context_recall
    ✅ context_recall: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/5: answer_correctness
    ✅ answer_correctness: 0.9628113641592873
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/5: semantic_similarity
    ✅ semantic_similarity: 0.8512454566371492
✅ Đánh giá dòng 7 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 8/16 ---
   Q: Người đại diện theo pháp luật của công ty là ai?...
   A: Người đại diện theo pháp luật của công ty là **ĐÀO CÔNG DUY**, chức danh Tổng giám đốc....
    🔄 Metric 1/5: faithfulness
    ✅ faithfulness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/5: context_precision
    ✅ context_precision: 0.9999999999666667
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/5: context_recall
    ✅ context_recall: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/5: answer_correctness
    ✅ answer_correctness: 0.6536272475647146
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/5: semantic_similarity
    ✅ semantic_similarity: 0.6145089902588583
✅ Đánh giá dòng 8 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 9/16 ---
   Q: Khách hàng có kinh doanh ngành nghề có điều kiện không?...
   A: Tôi không tìm thấy thông tin trong tài liệu....
    🔄 Metric 1/5: faithfulness
    ✅ faithfulness: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/5: context_precision
    ✅ context_precision: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/5: context_recall
    ✅ context_recall: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/5: answer_correctness
    ✅ answer_correctness: 0.11092360771308635
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/5: semantic_similarity
    ✅ semantic_similarity: 0.4436944308523454
✅ Đánh giá dòng 9 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 10/16 ---
   Q: Thông tin chi tiết về ban lãnh đạo công ty là gì. Hãy liệt kê đầy đủ tên các thành viên, chức vụ, tỉ...
   A: Thông tin ban lãnh đạo công ty từ context:

1. **Đào Công Duy**
   - Chức vụ: Tổng giám đốc
  ...
    🔄 Metric 1/5: faithfulness
    ✅ faithfulness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/5: context_precision
    ✅ context_precision: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/5: context_recall
    ✅ context_recall: 0.3333333333333333
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/5: answer_correctness
    ✅ answer_correctness: 0.6415092247328258
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/5: semantic_similarity
    ✅ semantic_similarity: 0.656945989840394
✅ Đánh giá dòng 10 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 11/16 ---
   Q: Thông tin chi tiết về đầu vào sản xuất kinh doanh là gì?...
   A: Thông tin chi tiết về đầu vào sản xuất kinh doanh bao gồm:

1. **Nhôm thanh:**
   - Các mã kích ...
    🔄 Metric 1/5: faithfulness
    ✅ faithfulness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/5: context_precision
    ✅ context_precision: 0.9999999999
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/5: context_recall
    ✅ context_recall: 0.6666666666666666
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/5: answer_correctness
    ✅ answer_correctness: 0.48473661791753997
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/5: semantic_similarity
    ✅ semantic_similarity: 0.7960893288130172
✅ Đánh giá dòng 11 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 12/16 ---
   Q: Thông tin chi tiết về đầu ra sản xuất kinh doanh là gì?...
   A: Tôi không tìm thấy thông tin trong tài liệu....
    🔄 Metric 1/5: faithfulness
    ✅ faithfulness: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/5: context_precision
    ✅ context_precision: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/5: context_recall
    ✅ context_recall: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/5: answer_correctness
    ✅ answer_correctness: 0.1173345671643542
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/5: semantic_similarity
    ✅ semantic_similarity: 0.4693382686574168
✅ Đánh giá dòng 12 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 13/16 ---
   Q: Lĩnh vực kinh doanh của công ty là gì?...
   A: Dựa trên context, các công ty được đề cập hoạt động trong lĩnh vực sản xuất và cung cấp các sản phẩm...
    🔄 Metric 1/5: faithfulness
    ✅ faithfulness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/5: context_precision
    ✅ context_precision: 0.99999999995
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/5: context_recall
    ✅ context_recall: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/5: answer_correctness
    ✅ answer_correctness: 0.13199306031364946
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/5: semantic_similarity
    ✅ semantic_similarity: 0.5279722412545979
✅ Đánh giá dòng 13 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 14/16 ---
   Q: Sản phẩm/dịch vụ của công ty là gì?...
   A: Dựa trên context, sản phẩm/dịch vụ của các công ty được liệt kê như sau:

**Sunspace:**
- Hệ thống v...
    🔄 Metric 1/5: faithfulness
    ✅ faithfulness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/5: context_precision
    ✅ context_precision: 0.9999999999
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/5: context_recall
    ✅ context_recall: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/5: answer_correctness
    ✅ answer_correctness: 0.9245841156489389
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/5: semantic_similarity
    ✅ semantic_similarity: 0.7840507483100416
✅ Đánh giá dòng 14 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 15/16 ---
   Q: Đầu vào - mặt hàng là gì?...
   A: Đầu vào - mặt hàng bao gồm:
1. **Nhôm thanh**:
   - Các mã kích thước nhỏ: sản xuất trong nước.
   ...
    🔄 Metric 1/5: faithfulness
    ✅ faithfulness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/5: context_precision
    ✅ context_precision: 0.9999999999
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/5: context_recall
    ✅ context_recall: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/5: answer_correctness
    ✅ answer_correctness: 0.5633320660766633
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/5: semantic_similarity
    ✅ semantic_similarity: 0.7533282643066533
✅ Đánh giá dòng 15 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 16/16 ---
   Q: Đầu vào - chi tiết là gì?...
   A: Đầu vào của khách hàng bao gồm:
1. **Nhôm thanh**:
   - Các mã kích thước nhỏ: sản xuất trong nư...
    🔄 Metric 1/5: faithfulness
    ✅ faithfulness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/5: context_precision
    ✅ context_precision: 0.9999999999
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/5: context_recall
    ✅ context_recall: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/5: answer_correctness
    ✅ answer_correctness: 0.30850004334116155
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/5: semantic_similarity
    ✅ semantic_similarity: 0.8054287447932176
✅ Đánh giá dòng 16 hoàn tất.

--- ✅ Tất cả các dòng đã được đánh giá. Tổng hợp kết quả... ---
📊 Kết quả có 16 dòng và 5 cột metrics.


--- 📊 KẾT QUẢ ĐÁNH GIÁ CHI TIẾT ---

,faithfulness,context_precision,context_recall,answer_correctness,semantic_similarity
0,1.000000,1.0,1.000000,0.970742,0.882970
1,1.000000,1.0,1.000000,0.888619,0.554477
2,1.000000,1.0,1.000000,0.923357,0.693428
3,0.888889,0.0,0.000000,0.097594,0.390377
4,0.000000,0.0,1.000000,0.103612,0.414448
5,1.000000,1.0,1.000000,0.896698,0.586793
6,1.000000,1.0,1.000000,0.962811,0.851245
7,1.000000,1.0,1.000000,0.653627,0.614509
8,0.000000,0.0,0.000000,0.110924,0.443694
9,1.000000,0.0,0.333333,0.641509,0.656946
10,1.000000,1.0,0.666667,0.484737,0.796089
11,0.000000,0.0,0.000000,0.117335,0.469338
12,1.000000,1.0,1.000000,0.131993,0.527972
13,1.000000,1.0,0.000000,0.924584,0.784051
14,1.000000,1.0,1.000000,0.563332,0.753328
15,1.000000,1.0,1.000000,0.308500,0.805429

📁 Đã đảm bảo thư mục tồn tại: /root/chatbot1/chatbot_document/backend/new/evaluation_reports
📊 Tìm thấy 5 metrics trong kết quả: ['faithfulness', 'context_precision', 'context_recall', 'answer_correctness', 'semantic_similarity']
📊 Báo cáo đã được lưu tại: /root/chatbot1/chatbot_document/backend/new/evaluation_reports/ragas_report(full_raw_input_claude_parsing_deepseek).xlsx
📋 Điểm số trung bình:
   faithfulness: 0.8056
   context_precision: 0.6875
   context_recall: 0.6875
   answer_correctness: 0.5487
   semantic_similarity: 0.6391

## No child/parent chunking no reranking

In [ ]:
# ==============================================================================
# MỤC ĐÍCH: CHẠY PIPELINE RAG VỚI NAIVE CHUNKING NO RERANKING
# ==============================================================================

import os
import json
from pathlib import Path
from typing import List, Tuple
import time
import uuid
import numpy as np
import pandas as pd
from langchain.schema import Document
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_google_genai import ChatGoogleGenerativeAI
from sentence_transformers import CrossEncoder
from qdrant_client import QdrantClient
from qdrant_client.http.models import Distance, VectorParams, PointStruct

# --- CẤU HÌNH ---
DELAY_BETWEEN_CALLS = 10
QDRANT_HOST = "localhost"  
QDRANT_PORT = 6333      
COLLECTION_NAME = "naive_chunking_collection" # Đổi tên collection cho rõ ràng
GOOGLE_API_KEY = "AIzaSyDtBIjTSfbvuEsobNwjtdyi9gVpDrCaWPM"

# --- KHỞI TẠO CÁC MODEL ---
print("🧠 Đang khởi tạo các model RAG...")
embedding_model = HuggingFaceEmbeddings(
    model_name="jinaai/jina-embeddings-v3",
    model_kwargs={"device": "cpu", "trust_remote_code": True}
)
llm_client = ChatGoogleGenerativeAI(model="gemini-2.0-flash", google_api_key=GOOGLE_API_KEY, temperature=0)
qdrant_client = QdrantClient(host=QDRANT_HOST, port=QDRANT_PORT)
print("✅ Các model RAG đã sẵn sàng.")


def clear_qdrant_collection():
    try:
        qdrant_client.delete_collection(collection_name=COLLECTION_NAME)
        print(f"✅ Đã xóa collection '{COLLECTION_NAME}' (nếu tồn tại).")
    except Exception:
        pass

def setup_qdrant_collection(embedding_dim: int):
    try:
        qdrant_client.recreate_collection(
            collection_name=COLLECTION_NAME,
            vectors_config=VectorParams(size=embedding_dim, distance=Distance.COSINE)
        ); return True
    except Exception as e:
        print(f"❌ Lỗi khi setup Qdrant collection: {e}"); return False

# <<< SỬ DỤNG HÀM MỚI CHO NAIVE CHUNKING >>>
def setup_naive_chunking_with_qdrant(markdown_content: str):
    """
    Chuẩn bị dữ liệu bằng cách chunking đơn giản (kích thước cố định) và lưu vào Qdrant.
    """
    print("--- Bước 1: Chuẩn bị dữ liệu bằng Naive Chunking ---")
    text_splitter = RecursiveCharacterTextSplitter(chunk_size=800, chunk_overlap=150)
    chunks = text_splitter.create_documents([markdown_content])
    print(f"✅ Đã tạo {len(chunks)} chunks đơn giản (size=800).")

    sample_embedding = embedding_model.embed_query("test")
    if not setup_qdrant_collection(len(sample_embedding)): 
        return None, False
    
    print("🧠 Đang embedding các chunks...")
    chunk_contents = [c.page_content for c in chunks]
    chunk_embeddings = np.array(embedding_model.embed_documents(chunk_contents))
    print("✅ Embedding hoàn tất!")
    
    points = []
    for chunk, emb in zip(chunks, chunk_embeddings):
        payload = {"content": chunk.page_content}
        points.append(PointStruct(id=str(uuid.uuid4()), vector=emb.tolist(), payload=payload))
    qdrant_client.upsert(collection_name=COLLECTION_NAME, points=points, wait=True)
    print(f"✅ Đã lưu {len(points)} chunks vào Qdrant.")
    return chunks, True

# <<< SỬ DỤNG HÀM MỚI ĐỂ RETRIEVE >>>
def retrieve_naive_chunks(query: str, top_k: int = 3) -> List[str]:
    """
    Thực hiện tìm kiếm vector đơn giản và trả về nội dung của các chunk top-k.
    """
    query_embedding = embedding_model.embed_query(query)
    search_results = qdrant_client.search(
        collection_name=COLLECTION_NAME,
        query_vector=query_embedding,
        limit=top_k,
        with_payload=True
    )
    contexts = [hit.payload["content"] for hit in search_results if hit.payload and "content" in hit.payload]
    return contexts

def answer_with_context(query: str, context_list: List[str]) -> str:
    """Sử dụng LLM để trả lời câu hỏi dựa trên context được cung cấp."""
    full_context_str = "\n\n---\n\n".join(context_list)
    prompt_template = f"""Bạn là một trợ lý AI chuyên nghiệp, chỉ trả lời dựa trên context được cung cấp.
Trả lời câu hỏi một cách ngắn gọn và chính xác. Nếu không có thông tin trong context, hãy nói "Tôi không tìm thấy thông tin trong tài liệu."
Context:\n---\n{full_context_str}\n---\nCâu hỏi: {query}\nTrả lời:"""
    response = llm_client.invoke(prompt_template)
    return response.content

# --- CHẠY PIPELINE VÀ THU THẬP DỮ LIỆU ---
generated_data_for_eval = [] 
markdown_file_path = Path('output_parsing/parsed_output.md')

if not markdown_file_path.exists():
    print(f"❌ Lỗi: Không tìm thấy file {markdown_file_path}. Vui lòng chạy bước parsing trước.")
else:
    with open(markdown_file_path, 'r', encoding='utf-8') as f:
        markdown_content = f.read()

    clear_qdrant_collection()
    # <<< GỌI HÀM SETUP MỚI >>>
    _, success = setup_naive_chunking_with_qdrant(markdown_content)
    
    if not success:
        print("❌ Không thể setup dữ liệu với Qdrant. Dừng chương trình.")
    else:
        with open('/root/chatbot1/chatbot_document/backend/schemas/ragasdf_base.json', 'r', encoding='utf-8') as f:
            template4_queries_data = json.load(f)
        template4_queries = [item['question'] for item in template4_queries_data]

        print(f"\n\n=== 🚀 BẮT ĐẦU CHẠY RAG (NAIVE CHUNKING) TRÊN {len(template4_queries)} CÂU HỎI ===")
        
        for i, query in enumerate(template4_queries, 1):
            print(f"\n--- Query {i}/{len(template4_queries)} ---")
            print(f"❓ Câu hỏi: {query}")
            
            # <<< GỌI HÀM RETRIEVE MỚI >>>
            context_list = retrieve_naive_chunks(query)
            answer = answer_with_context(query, context_list)
            
            print(f"✅ Câu trả lời của hệ thống: {answer}")
            
            generated_data_for_eval.append({
                "question": query,
                "answer": answer,
                "contexts": context_list
            })
            
            print("-" * 40)
            if i < len(template4_queries):
                print(f"⏳ Đợi {DELAY_BETWEEN_CALLS} giây...")
                time.sleep(DELAY_BETWEEN_CALLS)

        print("\n\n✅ Đã thu thập xong toàn bộ dữ liệu (answer, context).")
        display(pd.DataFrame(generated_data_for_eval).head())
        output_file = Path('new/output_parsing_new/generated_data_for_eval(naive_norerank).json')
        output_file.parent.mkdir(parents=True, exist_ok=True)
        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump(generated_data_for_eval, f, ensure_ascii=False, indent=4)
        print(f"✅ Đã lưu kết quả vào file: {output_file}")

🧠 Đang khởi tạo các model RAG...

flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
/tmp/ipykernel_10906/266588018.py:37: UserWarning: Qdrant client version 1.15.1 is incompatible with server version 1.7.2. Major versions should match and minor version difference must not exceed 1. Set check_compatibility=False to skip version check.
  qdrant_client = QdrantClient(host=QDRANT_HOST, port=QDRANT_PORT)

✅ Các model RAG đã sẵn sàng.
✅ Đã xóa collection 'naive_chunking_collection' (nếu tồn tại).
--- Bước 1: Chuẩn bị dữ liệu bằng Naive Chunking ---
✅ Đã tạo 18 chunks đơn giản (size=800).

/tmp/ipykernel_10906/266588018.py:50: DeprecationWarning: `recreate_collection` method is deprecated and will be removed in the future. Use `collection_exists` to check collection existence and `create_collection` instead.
  qdrant_client.recreate_collection(

🧠 Đang embedding các chunks...
✅ Embedding hoàn tất!
✅ Đã lưu 18 chunks vào Qdrant.


=== 🚀 BẮT ĐẦU CHẠY RAG (NAIVE CHUNKING) TRÊN 40 CÂU HỎI ===

--- Query 1/40 ---
❓ Câu hỏi: Tên đầy đủ của khách hàng là gì?

/tmp/ipykernel_10906/266588018.py:90: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: CÔNG TY CỔ PHẦN MẶT DỰNG CAG
----------------------------------------
⏳ Đợi 10 giây...

--- Query 2/40 ---
❓ Câu hỏi: Số giấy phép đăng ký kinh doanh của khách hàng là gì?

/tmp/ipykernel_10906/266588018.py:90: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: 0101442420
----------------------------------------
⏳ Đợi 10 giây...

--- Query 3/40 ---
❓ Câu hỏi: ID khách hàng là gì?

/tmp/ipykernel_10906/266588018.py:90: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: 22079986
----------------------------------------
⏳ Đợi 10 giây...

--- Query 4/40 ---
❓ Câu hỏi: Phân khúc của khách hàng là gì?

/tmp/ipykernel_10906/266588018.py:90: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Trung - cao cấp
----------------------------------------
⏳ Đợi 10 giây...

--- Query 5/40 ---
❓ Câu hỏi: Loại khách hàng là gì?

/tmp/ipykernel_10906/266588018.py:90: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: CÔNG TY CỔ PHẦN MẶT DỰNG CAG
----------------------------------------
⏳ Đợi 10 giây...

--- Query 6/40 ---
❓ Câu hỏi: Ngành nghề hoạt động kinh doanh của khách hàng là gì?

/tmp/ipykernel_10906/266588018.py:90: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Sản xuất và lắp đặt hệ thống mặt dựng kính, tấm ốp Alu, hệ thống cửa kính, cửa sổ, lam chắn nắng, cầu thang kính;  chuyên về nhôm + sơn và hoàn thiện sản phẩm.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 7/40 ---
❓ Câu hỏi: Mục đích báo cáo là gì?

/tmp/ipykernel_10906/266588018.py:90: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 8/40 ---
❓ Câu hỏi: Kết quả phân luồng của khách hàng là gì?

/tmp/ipykernel_10906/266588018.py:90: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 9/40 ---
❓ Câu hỏi: XHTD của khách hàng là gì?, XHTD là xếp hạng tín dụng của khách hàng và thường có các giá trị như Aa3, Baa2, v.v.

/tmp/ipykernel_10906/266588018.py:90: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Aa3
----------------------------------------
⏳ Đợi 10 giây...

--- Query 10/40 ---
❓ Câu hỏi: Ngày thành lập công ty là ngày nào?

/tmp/ipykernel_10906/266588018.py:90: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: 19/01/2004
----------------------------------------
⏳ Đợi 10 giây...

--- Query 11/40 ---
❓ Câu hỏi: Địa chỉ đăng ký kinh doanh của công ty là gì?

/tmp/ipykernel_10906/266588018.py:90: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Lô CN4 – 2.1, KCN Thạch Thất, thị trấn Quốc Oai, huyện Quốc Oai, thành phố Hà Nội
----------------------------------------
⏳ Đợi 10 giây...

--- Query 12/40 ---
❓ Câu hỏi: Người đại diện theo pháp luật của công ty là ai?

/tmp/ipykernel_10906/266588018.py:90: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Đào Công Duy
----------------------------------------
⏳ Đợi 10 giây...

--- Query 13/40 ---
❓ Câu hỏi: Khách hàng có kinh doanh ngành nghề có điều kiện không?

/tmp/ipykernel_10906/266588018.py:90: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 14/40 ---
❓ Câu hỏi: Thông tin chi tiết về ban lãnh đạo công ty là gì. Hãy liệt kê đầy đủ tên các thành viên, chức vụ, tỉ lệ góp vốn nếu có?

/tmp/ipykernel_10906/266588018.py:90: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tổng Giám đốc: Đào Công Duy (tỷ lệ góp vốn: 90%)
Tôi không tìm thấy thông tin chi tiết về các thành viên ban lãnh đạo khác.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 15/40 ---
❓ Câu hỏi: Thông tin chi tiết về đầu vào sản xuất kinh doanh là gì?

/tmp/ipykernel_10906/266588018.py:90: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin chi tiết về đầu vào sản xuất kinh doanh.  Chỉ có thông tin về số lượng công nhân (60 người) và một số khách hàng (Bộ ban ngành, ACV, TKV, bệnh viện, CĐT tư nhân).
----------------------------------------
⏳ Đợi 10 giây...

--- Query 16/40 ---
❓ Câu hỏi: Thông tin chi tiết về đầu ra sản xuất kinh doanh là gì?

/tmp/ipykernel_10906/266588018.py:90: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Bộ ban ngành, ACV, TKV, bệnh viện và CĐT tư nhân.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 17/40 ---
❓ Câu hỏi: Nhận xét về thông tin khách hàng là gì?

/tmp/ipykernel_10906/266588018.py:90: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Công ty Cổ phần Mặt Dựng CAG được thành lập năm 2004, có doanh thu năm 2023 là 944 tỷ đồng.  Sản phẩm chính là hệ thống mặt dựng kính, tấm ốp Alu, hệ thống cửa kính và lam chắn nắng.  Công ty nhập khẩu nguyên vật liệu như nhôm, kính màu và phôi kính từ Trung Quốc.  Sản phẩm của công ty thuộc phân khúc trung - cao cấp.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 18/40 ---
❓ Câu hỏi: Nhận xét về pháp lý/GPKD có điều kiện là gì?

/tmp/ipykernel_10906/266588018.py:90: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 19/40 ---
❓ Câu hỏi: Nhận xét về chủ doanh nghiệp/ban lãnh đạo là gì?

/tmp/ipykernel_10906/266588018.py:90: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Đào Công Duy là Tổng Giám đốc kiêm cổ đông lớn nhất (90% cổ phần).  Thái Thị Kim Dung và Đào Công Dũng cũng là cổ đông.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 20/40 ---
❓ Câu hỏi: Nhận xét về KYC là gì?

/tmp/ipykernel_10906/266588018.py:90: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 21/40 ---
❓ Câu hỏi: Lĩnh vực kinh doanh của công ty là gì?

/tmp/ipykernel_10906/266588018.py:90: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Sản xuất và lắp đặt hệ thống mặt dựng kính, tấm ốp Alu, hệ thống cửa kính, lam chắn nắng, cầu thang kính; gia công khung nhôm.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 22/40 ---
❓ Câu hỏi: Sản phẩm/dịch vụ của công ty là gì?

/tmp/ipykernel_10906/266588018.py:90: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Hệ thống mặt dựng kính, tấm ốp Alu, hệ thống cửa kính (cửa tự động, cửa mở quay, cửa đi lùa), cửa số (mở quay, mở hắt), lam chắn nắng, cầu thang kính, và gia công khung nhôm.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 23/40 ---
❓ Câu hỏi: Tỷ trọng doanh thu năm N-1 (%) là bao nhiêu?

/tmp/ipykernel_10906/266588018.py:90: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 24/40 ---
❓ Câu hỏi: Tỷ trọng doanh thu năm N (%) là bao nhiêu?

/tmp/ipykernel_10906/266588018.py:90: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 25/40 ---
❓ Câu hỏi: Nhóm mặt hàng của công ty là gì?

/tmp/ipykernel_10906/266588018.py:90: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Hệ thống mặt dựng kính, tấm ốp Alu, hệ thống cửa kính (cửa tự động, cửa mở quay, cửa đi lùa), cửa sổ (mở quay, mở hắt), lam chắn nắng, cầu thang kính.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 26/40 ---
❓ Câu hỏi: Tỷ trọng doanh thu năm 2023 là bao nhiêu?

/tmp/ipykernel_10906/266588018.py:90: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: 944 tỷ đồng
----------------------------------------
⏳ Đợi 10 giây...

--- Query 27/40 ---
❓ Câu hỏi: Tỷ trọng doanh thu 10T/2024 là bao nhiêu?

/tmp/ipykernel_10906/266588018.py:90: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 28/40 ---
❓ Câu hỏi: Mô tả chung về sản phẩm của công ty là gì?

/tmp/ipykernel_10906/266588018.py:90: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Công ty sản xuất hệ thống mặt dựng kính, tấm ốp Alu, hệ thống cửa kính (cửa tự động, cửa mở quay, cửa đi lùa), cửa sổ (mở quay, mở hắt), lam chắn nắng, cầu thang kính và gia công khung nhôm.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 29/40 ---
❓ Câu hỏi: Mô tả lợi thế cạnh tranh của công ty là gì?

/tmp/ipykernel_10906/266588018.py:90: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 30/40 ---
❓ Câu hỏi: Mô tả năng lực đấu thầu của công ty là gì?

/tmp/ipykernel_10906/266588018.py:90: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 31/40 ---
❓ Câu hỏi: Quy trình vận hành (tóm tắt) của công ty là gì?

/tmp/ipykernel_10906/266588018.py:90: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 32/40 ---
❓ Câu hỏi: Đầu vào - mặt hàng là gì?

/tmp/ipykernel_10906/266588018.py:90: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Nhôm thanh, phôi kính, kính không màu, kính màu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 33/40 ---
❓ Câu hỏi: Đầu vào - chi tiết là gì?

/tmp/ipykernel_10906/266588018.py:90: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 34/40 ---
❓ Câu hỏi: Đầu vào - phương thức thanh toán là gì?

/tmp/ipykernel_10906/266588018.py:90: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 35/40 ---
❓ Câu hỏi: Đầu ra - kênh phân phối là gì?

/tmp/ipykernel_10906/266588018.py:90: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Bộ ban ngành, ACV, TKV, bệnh viện; CĐT tư nhân
----------------------------------------
⏳ Đợi 10 giây...

--- Query 36/40 ---
❓ Câu hỏi: Đầu ra - tỷ trọng là bao nhiêu?

/tmp/ipykernel_10906/266588018.py:90: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 37/40 ---
❓ Câu hỏi: Đầu ra - phương thức thanh toán là gì?

/tmp/ipykernel_10906/266588018.py:90: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 38/40 ---
❓ Câu hỏi: Nhận xét tổng quan về hoạt động kinh doanh là gì?

/tmp/ipykernel_10906/266588018.py:90: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Công ty Cổ phần Mặt Dựng CAG được thành lập năm 2004, có doanh thu 944 tỷ đồng năm 2023.  Sản phẩm chính là hệ thống mặt dựng kính, tấm ốp Alu, hệ thống cửa kính và lam chắn nắng. Khách hàng bao gồm các bộ ban ngành, ACV, TKV, bệnh viện và các chủ đầu tư tư nhân. Công ty có 60 công nhân.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 39/40 ---
❓ Câu hỏi: Phân tích cung cầu ngành là gì?

/tmp/ipykernel_10906/266588018.py:90: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 40/40 ---
❓ Câu hỏi: Nhận xét về thông tin ngành là gì?

/tmp/ipykernel_10906/266588018.py:90: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------


✅ Đã thu thập xong toàn bộ dữ liệu (answer, context).

,question,answer,contexts
0,Tên đầy đủ của khách hàng là gì?,CÔNG TY CỔ PHẦN MẶT DỰNG CAG,[1. Thông tin khách hàng\nTên khách hàng: | CÔ...
1,Số giấy phép đăng ký kinh doanh của khách hàng...,0101442420,[1. Thông tin khách hàng\nTên khách hàng: | CÔ...
2,ID khách hàng là gì?,22079986,[1. Thông tin khách hàng\nTên khách hàng: | CÔ...
3,Phân khúc của khách hàng là gì?,Trung - cao cấp,"[| | • Diện tích: 10,000 ..."
4,Loại khách hàng là gì?,CÔNG TY CỔ PHẦN MẶT DỰNG CAG,[1. Thông tin khách hàng\nTên khách hàng: | CÔ...

✅ Đã lưu kết quả vào file: output_parsing/generated_data_for_eval(reranking).json

In [ ]:
# ==============================================================================
# CELL MỚI: THỰC HIỆN ĐÁNH GIÁ BẰNG RAGAS
# ==============================================================================
from utils.ragas_evaluation import RagasEvaluator
import pandas as pd
from pathlib import Path
import json
# 1. Khởi tạo Evaluator
# Đảm bảo GOOGLE_API_KEY đã được định nghĩa ở cell trên
GOOGLE_API_KEYS = ["AIzaSyBH8O5IfqYrJ5wtWnmUC21IfMjzJCrTm3I",
                    "AIzaSyDtBIjTSfbvuEsobNwjtdyi9gVpDrCaWPM",
                    "AIzaSyAD_58r3fQhcTOE6qQS1YlR3iJ_ZnGKy10",
                    "AIzaSyAWtCSrLhJDZGF1ArOSS0o7Iy_zMG42810",
                    "AIzaSyCtAz9maZ9usoxEHhhFocHW07WM4IbgOXo",
                    "AIzaSyCI8QGQrVUgr_FrFLttDs0fP4VyJyPXoec",
                    "AIzaSyBPglAFlDOf97drnNAplHIIsjgvsfzezsI",
                    "AIzaSyCaKzwEjW0XxJAuZ9XdzI6rHkifHkA0eNY",
                    "AIzaSyDNosIJZjXd2tzm7_VKxK5uFTBmoPuHXkc"]

# GOOGLE_API_KEYS = ["AIzaSyDNosIJZjXd2tzm7_VKxK5uFTBmoPuHXkc"]  

evaluator = RagasEvaluator(list_of_api_keys=GOOGLE_API_KEYS)

# load generated data từ file JSON
generated_data_file = Path('new/output_parsing_new/generated_data_for_eval(naive_norerank).json')
if not generated_data_file.exists():
    print(f"❌ Lỗi: Không tìm thấy file {generated_data_file}. Vui lòng chạy bước thu thập dữ liệu trước.")
else:
    with open(generated_data_file, 'r', encoding='utf-8') as f:
        generated_data_for_eval = json.load(f)
        
# 2. Tải dataset cơ sở (chứa question và ground_truth)
base_data = evaluator.load_base_dataset('/root/chatbot1/chatbot_document/backend/schemas/ragasdf_base.json')

# 3. Chuẩn bị dataset hoàn chỉnh bằng cách kết hợp base_data và generated_data
eval_dataset = evaluator.prepare_evaluation_dataset(
    base_data=base_data,
    generated_data=generated_data_for_eval # Sử dụng kết quả từ cell trước
)

# 4. Xuất file dataset RAGAS hoàn chỉnh ra Excel để kiểm tra
if eval_dataset:
    ragas_df = eval_dataset.to_pandas()
    ragas_df['context_count'] = ragas_df['contexts'].apply(len)
    output_df_path = "new/ragasdf_new/ragas_dataset_for_evaluation(naive_norerank).xlsx"
    os.makedirs(Path(output_df_path).parent, exist_ok=True)
    ragas_df.to_excel(output_df_path, index=False)
    print(f"💾 Đã xuất file dataset RAGAS hoàn chỉnh ra: {output_df_path}")
    print("Đây là 5 dòng đầu tiên của dataset sẽ được đánh giá:")
    display(ragas_df.head())
    
# 5. Chạy đánh giá
if eval_dataset:
    results_df = evaluator.run_evaluation(eval_dataset)

    if results_df is not None:
        # 6. Hiển thị và lưu báo cáo
        print("\n\n--- 📊 KẾT QUẢ ĐÁNH GIÁ CHI TIẾT ---")
        display(results_df)

        evaluator.save_report(results_df, "/root/chatbot1/chatbot_document/backend/new/evaluation_reports", "ragas_report(naive_norerank).xlsx")
    else:
        print("❌ Đánh giá không trả về kết quả.")
else:
    print("❌ Không thể tạo dataset để đánh giá.")

🚀 Khởi tạo RagasEvaluator (có Retry & Key Switching)...

flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.

✅ LLM và Embeddings đã sẵn sàng.
📋 Đã định nghĩa 12 metrics: ['faithfulness', 'answer_relevancy', 'context_precision', 'context_recall', 'semantic_similarity', 'answer_correctness', 'factual_correctness', 'exact_match', 'bleu_score', 'rouge_score', 'semantic_similarity', 'non_llm_string_similarity']
📂 Đang tải base dataset từ: /root/chatbot1/chatbot_document/backend/schemas/ragasdf_base.json
✅ Tải thành công 40 mẫu.
🔄 Đang chuẩn bị dataset để đánh giá...
✅ Đã chuẩn hóa cột 'contexts' với kiểu dữ liệu: <class 'list'>
✅ Đã tạo thành công dataset với 40 mẫu để đánh giá.
✅ Kiểu dữ liệu của cột 'contexts' đã được xác nhận là: <class 'list'>
💾 Đã xuất file dataset RAGAS hoàn chỉnh ra: ragasdf/ragas_dataset_for_evaluation(naive_norerank).xlsx
Đây là 5 dòng đầu tiên của dataset sẽ được đánh giá:

,question,ground_truths,answer,contexts,context_count
0,Tên đầy đủ của khách hàng là gì?,[CÔNG TY CỔ PHẦN MẶT DỰNG CAG],CÔNG TY CỔ PHẦN MẶT DỰNG CAG,[1. Thông tin khách hàng\nTên khách hàng: | CÔ...,5
1,Số giấy phép đăng ký kinh doanh của khách hàng...,[0101442420],0101442420,[1. Thông tin khách hàng\nTên khách hàng: | CÔ...,5
2,ID khách hàng là gì?,[22079986],22079986,[1. Thông tin khách hàng\nTên khách hàng: | CÔ...,5
3,Phân khúc của khách hàng là gì?,[MM],Trung - cao cấp,"[| | • Diện tích: 10,000 ...",5
4,Loại khách hàng là gì?,[],CÔNG TY CỔ PHẦN MẶT DỰNG CAG,[1. Thông tin khách hàng\nTên khách hàng: | CÔ...,5

⚠️ Dataset thiếu các cột tùy chọn (sẽ được tạo tự động): ['reference']
✅ Dataset schema hợp lệ. Columns: ['question', 'ground_truths', 'answer', 'contexts']
⚠️ Giới hạn dataset từ 40 xuống 8 samples để tránh rate limit

🔬 Bắt đầu đánh giá RAGAS trên 8 mẫu với 12 metrics...
📋 Metrics: ['faithfulness', 'answer_relevancy', 'context_precision', 'context_recall', 'semantic_similarity', 'answer_correctness', 'factual_correctness', 'exact_match', 'bleu_score', 'rouge_score', 'semantic_similarity', 'non_llm_string_similarity']

--- 🔄 Đang đánh giá dòng 1/8 ---
   Q: Tên đầy đủ của khách hàng là gì?...
    🔄 Metric 1/12: faithfulness
    ✅ faithfulness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/12: answer_relevancy
    ✅ answer_relevancy: 0.5950106611044355
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/12: context_precision
    ✅ context_precision: 0.8333333332916666
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/12: context_recall
    ✅ context_recall: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/12: semantic_similarity
    ✅ semantic_similarity: 0.9999999999999999
    🔄 Metric 6/12: answer_correctness
    ✅ answer_correctness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 7/12: factual_correctness
    ✅ factual_correctness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 8/12: exact_match
    ✅ exact_match: 1.0
    🔄 Metric 9/12: bleu_score
    ✅ bleu_score: 1.0000000000000004
    🔄 Metric 10/12: rouge_score
    ✅ rouge_score: 1.0
    🔄 Metric 11/12: semantic_similarity
    ✅ semantic_similarity: 0.9999999999999999
    🔄 Metric 12/12: non_llm_string_similarity
    ✅ non_llm_string_similarity: 1.0
✅ Đánh giá dòng 1 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 2/8 ---
   Q: Số giấy phép đăng ký kinh doanh của khách hàng là gì?...
    🔄 Metric 1/12: faithfulness
    ✅ faithfulness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/12: answer_relevancy
    ✅ answer_relevancy: 0.5427868576139967
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/12: context_precision
    ✅ context_precision: 0.9999999999
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/12: context_recall
    ✅ context_recall: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/12: semantic_similarity
    ✅ semantic_similarity: 1.0000000000000002
    🔄 Metric 6/12: answer_correctness
    ✅ answer_correctness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 7/12: factual_correctness
    ✅ factual_correctness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 8/12: exact_match
    ✅ exact_match: 1.0
    🔄 Metric 9/12: bleu_score
    ✅ bleu_score: 0.0
    🔄 Metric 10/12: rouge_score
    ✅ rouge_score: 1.0
    🔄 Metric 11/12: semantic_similarity
    ✅ semantic_similarity: 1.0000000000000002
    🔄 Metric 12/12: non_llm_string_similarity
    ✅ non_llm_string_similarity: 1.0
✅ Đánh giá dòng 2 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 3/8 ---
   Q: ID khách hàng là gì?...
    🔄 Metric 1/12: faithfulness
    ✅ faithfulness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/12: answer_relevancy
    ✅ answer_relevancy: 0.2241125251783769
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/12: context_precision
    ✅ context_precision: 0.8333333332916666
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/12: context_recall
    ✅ context_recall: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/12: semantic_similarity
    ✅ semantic_similarity: 1.0
    🔄 Metric 6/12: answer_correctness
    ✅ answer_correctness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 7/12: factual_correctness
    ✅ factual_correctness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 8/12: exact_match
    ✅ exact_match: 1.0
    🔄 Metric 9/12: bleu_score
    ✅ bleu_score: 0.0
    🔄 Metric 10/12: rouge_score
    ✅ rouge_score: 1.0
    🔄 Metric 11/12: semantic_similarity
    ✅ semantic_similarity: 1.0
    🔄 Metric 12/12: non_llm_string_similarity
    ✅ non_llm_string_similarity: 1.0
✅ Đánh giá dòng 3 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 4/8 ---
   Q: Phân khúc của khách hàng là gì?...
    🔄 Metric 1/12: faithfulness
    ✅ faithfulness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/12: answer_relevancy
    ✅ answer_relevancy: 0.34222758774422396
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/12: context_precision
    ✅ context_precision: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/12: context_recall
    ✅ context_recall: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/12: semantic_similarity
    ✅ semantic_similarity: 0.511388865439378
    🔄 Metric 6/12: answer_correctness
    ✅ answer_correctness: 0.1278472163598445
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 7/12: factual_correctness
    ✅ factual_correctness: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 8/12: exact_match
    ✅ exact_match: 0.0
    🔄 Metric 9/12: bleu_score
    ✅ bleu_score: 0.0
    🔄 Metric 10/12: rouge_score
    ✅ rouge_score: 0.0
    🔄 Metric 11/12: semantic_similarity
    ✅ semantic_similarity: 0.511388865439378
    🔄 Metric 12/12: non_llm_string_similarity
    ✅ non_llm_string_similarity: 0.0
✅ Đánh giá dòng 4 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 5/8 ---
   Q: Loại khách hàng là gì?...
    🔄 Metric 1/12: faithfulness
    ✅ faithfulness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/12: answer_relevancy
    ✅ answer_relevancy: 0.364334772020474
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/12: context_precision
    ✅ context_precision: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/12: context_recall
    ✅ context_recall: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/12: semantic_similarity
    ✅ semantic_similarity: 0.4178238442792015
    🔄 Metric 6/12: answer_correctness
    ✅ answer_correctness: 0.10445596106980037
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 7/12: factual_correctness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 15
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 16
}
].

    ✅ factual_correctness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 8/12: exact_match
    ✅ exact_match: 0.0
    🔄 Metric 9/12: bleu_score
    ✅ bleu_score: 0.0
    🔄 Metric 10/12: rouge_score
    ✅ rouge_score: 0
    🔄 Metric 11/12: semantic_similarity
    ✅ semantic_similarity: 0.4178238442792015
    🔄 Metric 12/12: non_llm_string_similarity
    ✅ non_llm_string_similarity: 0.0
✅ Đánh giá dòng 5 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 6/8 ---
   Q: Ngành nghề hoạt động kinh doanh của khách hàng là gì?...
    🔄 Metric 1/12: faithfulness
    ✅ faithfulness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/12: answer_relevancy
    ✅ answer_relevancy: 0.5629774805306138
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/12: context_precision
    ✅ context_precision: 0.249999999975
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/12: context_recall
    ✅ context_recall: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/12: semantic_similarity
    ✅ semantic_similarity: 0.3589056159725956
    🔄 Metric 6/12: answer_correctness
    ✅ answer_correctness: 0.0897264039931489
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 7/12: factual_correctness
    ✅ factual_correctness: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 8/12: exact_match
    ✅ exact_match: 0.0
    🔄 Metric 9/12: bleu_score
    ✅ bleu_score: 0.0
    🔄 Metric 10/12: rouge_score
    ✅ rouge_score: 0
    🔄 Metric 11/12: semantic_similarity
    ✅ semantic_similarity: 0.3589056159725956
    🔄 Metric 12/12: non_llm_string_similarity
    ✅ non_llm_string_similarity: 0.0
✅ Đánh giá dòng 6 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 7/8 ---
   Q: Mục đích báo cáo là gì?...
    🔄 Metric 1/12: faithfulness
    ✅ faithfulness: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/12: answer_relevancy
    ✅ answer_relevancy: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/12: context_precision
    ✅ context_precision: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/12: context_recall
    ✅ context_recall: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/12: semantic_similarity
    ✅ semantic_similarity: 0.4338374439860875
    🔄 Metric 6/12: answer_correctness
    ✅ answer_correctness: 0.10845936099652187
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 7/12: factual_correctness
    ✅ factual_correctness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 8/12: exact_match
    ✅ exact_match: 0.0
    🔄 Metric 9/12: bleu_score
    ✅ bleu_score: 0.0
    🔄 Metric 10/12: rouge_score
    ✅ rouge_score: 0
    🔄 Metric 11/12: semantic_similarity
    ✅ semantic_similarity: 0.4338374439860875
    🔄 Metric 12/12: non_llm_string_similarity
    ✅ non_llm_string_similarity: 0.0
✅ Đánh giá dòng 7 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 8/8 ---
   Q: Kết quả phân luồng của khách hàng là gì?...
    🔄 Metric 1/12: faithfulness
    ✅ faithfulness: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/12: answer_relevancy
    ✅ answer_relevancy: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/12: context_precision
    ✅ context_precision: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/12: context_recall
    ✅ context_recall: 0.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/12: semantic_similarity
    ✅ semantic_similarity: 0.4338374439860875
    🔄 Metric 6/12: answer_correctness
    ✅ answer_correctness: 0.10845936099652187
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 7/12: factual_correctness
    ✅ factual_correctness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 8/12: exact_match
    ✅ exact_match: 0.0
    🔄 Metric 9/12: bleu_score
    ✅ bleu_score: 0.0
    🔄 Metric 10/12: rouge_score
    ✅ rouge_score: 0
    🔄 Metric 11/12: semantic_similarity
    ✅ semantic_similarity: 0.4338374439860875
    🔄 Metric 12/12: non_llm_string_similarity
    ✅ non_llm_string_similarity: 0.0
✅ Đánh giá dòng 8 hoàn tất.

--- ✅ Tất cả các dòng đã được đánh giá. Tổng hợp kết quả... ---
📊 Kết quả có 8 dòng và 11 cột metrics.


--- 📊 KẾT QUẢ ĐÁNH GIÁ CHI TIẾT ---

,faithfulness,answer_relevancy,context_precision,context_recall,semantic_similarity,answer_correctness,factual_correctness,exact_match,bleu_score,rouge_score(mode=fmeasure),non_llm_string_similarity
0,1.0,0.595011,0.833333,1.0,1.000000,1.000000,1.0,1.0,1.0,1.0,1.0
1,1.0,0.542787,1.000000,1.0,1.000000,1.000000,1.0,1.0,0.0,1.0,1.0
2,1.0,0.224113,0.833333,1.0,1.000000,1.000000,1.0,1.0,0.0,1.0,1.0
3,1.0,0.342228,0.000000,0.0,0.511389,0.127847,0.0,0.0,0.0,0.0,0.0
4,1.0,0.364335,0.000000,0.0,0.417824,0.104456,1.0,0.0,0.0,0.0,0.0
5,1.0,0.562977,0.250000,0.0,0.358906,0.089726,0.0,0.0,0.0,0.0,0.0
6,0.0,0.000000,0.000000,0.0,0.433837,0.108459,1.0,0.0,0.0,0.0,0.0
7,0.0,0.000000,0.000000,0.0,0.433837,0.108459,1.0,0.0,0.0,0.0,0.0

📊 Tìm thấy 12 metrics trong kết quả: ['faithfulness', 'answer_relevancy', 'context_precision', 'context_recall', 'semantic_similarity', 'answer_correctness', 'factual_correctness', 'exact_match', 'bleu_score', 'rouge_score(mode=fmeasure)', 'semantic_similarity', 'non_llm_string_similarity']
📊 Báo cáo đã được lưu tại: /root/chatbot1/chatbot_document/backend/evaluation_reports/ragas_report(naive_norerank).xlsx
📋 Điểm số trung bình:
   faithfulness: 0.7500
   answer_relevancy: 0.3289
   context_precision: 0.3646
   context_recall: 0.3750
   semantic_similarity: 0.6445
   answer_correctness: 0.4424
   factual_correctness: 0.7500
   exact_match: 0.3750
   bleu_score: 0.1250
   rouge_score(mode=fmeasure): 0.3750
   non_llm_string_similarity: 0.3750

## Only reranking + naive chunking

In [ ]:
# ==============================================================================
# MỤC ĐÍCH: CHẠY PIPELINE RAG VỚI NAIVE CHUNKING + RERANKING
# ==============================================================================

import os
import json
from pathlib import Path
from typing import List, Tuple
import time
import uuid
import numpy as np
import pandas as pd
from langchain.schema import Document
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_google_genai import ChatGoogleGenerativeAI
from sentence_transformers import CrossEncoder
# from utils.api_key_manager import ApiKeyManager
from qdrant_client import QdrantClient
from qdrant_client.http.models import Distance, VectorParams, PointStruct

# --- CẤU HÌNH ---
DELAY_BETWEEN_CALLS = 10
QDRANT_HOST = "localhost"  
QDRANT_PORT = 6333      
COLLECTION_NAME = "rerank_naive_chunking_collection" 
GOOGLE_API_KEY = "AIzaSyDNosIJZjXd2tzm7_VKxK5uFTBmoPuHXkc"

# --- KHỞI TẠO CÁC MODEL ---
print("🧠 Đang khởi tạo các model RAG...")
embedding_model = HuggingFaceEmbeddings(
    model_name="jinaai/jina-embeddings-v3",
    model_kwargs={"device": "cpu", "trust_remote_code": True}
)
llm_client = ChatGoogleGenerativeAI(model="gemini-2.5-flash-lite", google_api_key=GOOGLE_API_KEY, temperature=0)
# <<< THAY ĐỔI 1: GIỮ LẠI RERANKER MODEL >>>
reranker_model = CrossEncoder('BAAI/bge-reranker-large', device='cpu')
qdrant_client = QdrantClient(host=QDRANT_HOST, port=QDRANT_PORT)
print("✅ Các model RAG đã sẵn sàng.")

def clear_qdrant_collection():
    try: qdrant_client.delete_collection(collection_name=COLLECTION_NAME)
    except Exception: pass

def setup_qdrant_collection(embedding_dim: int):
    try:
        qdrant_client.recreate_collection(
            collection_name=COLLECTION_NAME,
            vectors_config=VectorParams(size=embedding_dim, distance=Distance.COSINE)
        ); return True
    except Exception as e:
        print(f"❌ Lỗi khi setup Qdrant collection: {e}"); return False

def setup_naive_chunking_with_qdrant(markdown_content: str):
    """
    Hàm này giữ nguyên: chunking đơn giản và lưu vào Qdrant.
    """
    print("--- Bước 1: Chuẩn bị dữ liệu bằng Naive Chunking ---")
    text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=150)
    chunks = text_splitter.create_documents([markdown_content])
    print(f"✅ Đã tạo {len(chunks)} chunks đơn giản (size=1000).")

    sample_embedding = embedding_model.embed_query("test")
    if not setup_qdrant_collection(len(sample_embedding)): 
        return None, False
    
    print("🧠 Đang embedding các chunks...")
    chunk_contents = [c.page_content for c in chunks]
    chunk_embeddings = np.array(embedding_model.embed_documents(chunk_contents))
    print("✅ Embedding hoàn tất!")
    
    points = [PointStruct(id=str(uuid.uuid4()), vector=emb.tolist(), payload={"content": chunk.page_content}) for chunk, emb in zip(chunks, chunk_embeddings)]
    qdrant_client.upsert(collection_name=COLLECTION_NAME, points=points, wait=True)
    print(f"✅ Đã lưu {len(points)} chunks vào Qdrant.")
    return chunks, True

# <<< THAY ĐỔI 2: HÀM RETRIEVE MỚI KẾT HỢP RERANKER >>>
def retrieve_and_rerank_naive_chunks(query: str, top_k_final: int = 3, retrieve_k_initial: int = 20) -> List[str]:
    """
    Lấy ra các chunk ứng viên bằng vector search, sau đó dùng reranker để xếp hạng lại.
    """
    # 1. Vector search để lấy ra một lượng lớn ứng viên (retrieve_k_initial)
    query_embedding = embedding_model.embed_query(query)
    search_results = qdrant_client.search(
        collection_name=COLLECTION_NAME,
        query_vector=query_embedding,
        limit=retrieve_k_initial,
        with_payload=True
    )
    
    candidate_docs = [hit.payload["content"] for hit in search_results if hit.payload and "content" in hit.payload]
    if not candidate_docs:
        return []

    # 2. Dùng reranker để chấm điểm và sắp xếp lại các ứng viên
    print(f"   reranking trên {len(candidate_docs)} chunks ứng viên...")
    pairs = [(query, doc) for doc in candidate_docs]
    scores = reranker_model.predict(pairs)
    
    reranked_results = sorted(zip(scores, candidate_docs), key=lambda x: x[0], reverse=True)
    
    # 3. Trả về top_k_final chunks có điểm cao nhất
    final_docs = [doc for score, doc in reranked_results[:top_k_final]]
    return final_docs

def answer_with_context(query: str, context_list: List[str]) -> str:
    """Hàm này giữ nguyên."""
    full_context_str = "\n\n---\n\n".join(context_list)
    prompt_template = f"""Bạn là một trợ lý AI chuyên nghiệp, chỉ trả lời dựa trên context được cung cấp.
Trả lời câu hỏi một cách ngắn gọn và chính xác. Nếu không có thông tin trong context, hãy nói "Tôi không tìm thấy thông tin trong tài liệu."
Context:\n---\n{full_context_str}\n---\nCâu hỏi: {query}\nTrả lời:"""
    response = llm_client.invoke(prompt_template)
    return response.content

# --- CHẠY PIPELINE VÀ THU THẬP DỮ LIỆU ---
generated_data_for_eval = [] 
markdown_file_path = Path('output_parsing/parsed_output.md')

if not markdown_file_path.exists():
    print(f"❌ Lỗi: Không tìm thấy file {markdown_file_path}. Vui lòng chạy bước parsing trước.")
else:
    with open(markdown_file_path, 'r', encoding='utf-8') as f:
        markdown_content = f.read()

    clear_qdrant_collection()
    _, success = setup_naive_chunking_with_qdrant(markdown_content)
    
    if not success:
        print("❌ Không thể setup dữ liệu với Qdrant. Dừng chương trình.")
    else:
        with open('/root/chatbot1/chatbot_document/backend/schemas/ragasdf_base.json', 'r', encoding='utf-8') as f:
            template4_queries_data = json.load(f)
        template4_queries = [item['question'] for item in template4_queries_data]

        print(f"\n\n=== 🚀 BẮT ĐẦU CHẠY RAG (NAIVE CHUNKING + RERANKING) TRÊN {len(template4_queries)} CÂU HỎI ===")
        
        for i, query in enumerate(template4_queries, 1):
            print(f"\n--- Query {i}/{len(template4_queries)} ---")
            print(f"❓ Câu hỏi: {query}")
            
            # <<< THAY ĐỔI 3: GỌI HÀM RETRIEVE CÓ RERANKER >>>
            context_list = retrieve_and_rerank_naive_chunks(query)
            answer = answer_with_context(query, context_list)
            
            print(f"✅ Câu trả lời của hệ thống: {answer}")
            
            generated_data_for_eval.append({
                "question": query, "answer": answer, "contexts": context_list
            })
            
            print("-" * 40)
            if i < len(template4_queries):
                print(f"⏳ Đợi {DELAY_BETWEEN_CALLS} giây...")
                time.sleep(DELAY_BETWEEN_CALLS)

        print("\n\n✅ Đã thu thập xong toàn bộ dữ liệu.")
        display(pd.DataFrame(generated_data_for_eval).head())
        
        output_file = Path('new/output_parsing/generated_data_for_eval(naive_rerank).json')
        output_file.parent.mkdir(parents=True, exist_ok=True)
        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump(generated_data_for_eval, f, ensure_ascii=False, indent=4)
        print(f"✅ Đã lưu kết quả vào file: {output_file}")

🧠 Đang khởi tạo các model RAG...

flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
/tmp/ipykernel_59379/595062362.py:38: UserWarning: Qdrant client version 1.15.1 is incompatible with server version 1.7.2. Major versions should match and minor version difference must not exceed 1. Set check_compatibility=False to skip version check.
  qdrant_client = QdrantClient(host=QDRANT_HOST, port=QDRANT_PORT)

✅ Các model RAG đã sẵn sàng.
--- Bước 1: Chuẩn bị dữ liệu bằng Naive Chunking ---
✅ Đã tạo 20 chunks đơn giản (size=1000).

/tmp/ipykernel_59379/595062362.py:47: DeprecationWarning: `recreate_collection` method is deprecated and will be removed in the future. Use `collection_exists` to check collection existence and `create_collection` instead.
  qdrant_client.recreate_collection(

🧠 Đang embedding các chunks...
✅ Embedding hoàn tất!
✅ Đã lưu 20 chunks vào Qdrant.


=== 🚀 BẮT ĐẦU CHẠY RAG (NAIVE CHUNKING + RERANKING) TRÊN 40 CÂU HỎI ===

--- Query 1/40 ---
❓ Câu hỏi: Tên đầy đủ của khách hàng là gì?

/tmp/ipykernel_59379/595062362.py:84: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

   reranking trên 20 chunks ứng viên...
✅ Câu trả lời của hệ thống: CÔNG TY CỔ PHẦN MẶT DỰNG CAG
----------------------------------------
⏳ Đợi 10 giây...

--- Query 2/40 ---
❓ Câu hỏi: Số giấy phép đăng ký kinh doanh của khách hàng là gì?

/tmp/ipykernel_59379/595062362.py:84: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

   reranking trên 20 chunks ứng viên...
✅ Câu trả lời của hệ thống: Số 0101442420 do Phòng Đăng ký kinh doanh – Sở Kế hoạch và Đầu tư thành phố Hà Nội cấp, đăng ký lần đầu ngày 19/01/2004, đăng ký thay đổi lần thứ 8 ngày 12/04/2023
----------------------------------------
⏳ Đợi 10 giây...

--- Query 3/40 ---
❓ Câu hỏi: ID khách hàng là gì?

/tmp/ipykernel_59379/595062362.py:84: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

   reranking trên 20 chunks ứng viên...
✅ Câu trả lời của hệ thống: 22079986
----------------------------------------
⏳ Đợi 10 giây...

--- Query 4/40 ---
❓ Câu hỏi: Phân khúc của khách hàng là gì?

/tmp/ipykernel_59379/595062362.py:84: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

   reranking trên 20 chunks ứng viên...
✅ Câu trả lời của hệ thống: Dân dụng: các tòa nhà văn phòng
Thi công trưng: Ip lu tl mt s tr
Ngân sách nhà nước: các tòa nhà ủy ban, trung tâm h
----------------------------------------
⏳ Đợi 10 giây...

--- Query 5/40 ---
❓ Câu hỏi: Loại khách hàng là gì?

/tmp/ipykernel_59379/595062362.py:84: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

   reranking trên 20 chunks ứng viên...
✅ Câu trả lời của hệ thống: CÔNG TY CỔ PHẦN MẶT DỰNG CAG
----------------------------------------
⏳ Đợi 10 giây...

--- Query 6/40 ---
❓ Câu hỏi: Ngành nghề hoạt động kinh doanh của khách hàng là gì?

/tmp/ipykernel_59379/595062362.py:84: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

   reranking trên 20 chunks ứng viên...
✅ Câu trả lời của hệ thống: Sản xuất nhôm kính, mặt dựng.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 7/40 ---
❓ Câu hỏi: Mục đích báo cáo là gì?

/tmp/ipykernel_59379/595062362.py:84: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

   reranking trên 20 chunks ứng viên...
✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 8/40 ---
❓ Câu hỏi: Kết quả phân luồng của khách hàng là gì?

/tmp/ipykernel_59379/595062362.py:84: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

   reranking trên 20 chunks ứng viên...
✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 9/40 ---
❓ Câu hỏi: XHTD của khách hàng là gì?, XHTD là xếp hạng tín dụng của khách hàng và thường có các giá trị như Aa3, Baa2, v.v.

/tmp/ipykernel_59379/595062362.py:84: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

   reranking trên 20 chunks ứng viên...
✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 10/40 ---
❓ Câu hỏi: Ngày thành lập công ty là ngày nào?

/tmp/ipykernel_59379/595062362.py:84: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

   reranking trên 20 chunks ứng viên...
✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 11/40 ---
❓ Câu hỏi: Địa chỉ đăng ký kinh doanh của công ty là gì?

/tmp/ipykernel_59379/595062362.py:84: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

   reranking trên 20 chunks ứng viên...
✅ Câu trả lời của hệ thống: Lô CN4 – 2.1, KCN Thạch Thất, thị trấn Quốc Oai, huyện Quốc Oai, thành phố Hà Nội
----------------------------------------
⏳ Đợi 10 giây...

--- Query 12/40 ---
❓ Câu hỏi: Người đại diện theo pháp luật của công ty là ai?

/tmp/ipykernel_59379/595062362.py:84: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

   reranking trên 20 chunks ứng viên...
✅ Câu trả lời của hệ thống: Họ tên: ĐÀO CÔNG DUY
Chức vụ: Tổng Giám đốc
----------------------------------------
⏳ Đợi 10 giây...

--- Query 13/40 ---
❓ Câu hỏi: Khách hàng có kinh doanh ngành nghề có điều kiện không?

/tmp/ipykernel_59379/595062362.py:84: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

   reranking trên 20 chunks ứng viên...
✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 14/40 ---
❓ Câu hỏi: Thông tin chi tiết về ban lãnh đạo công ty là gì. Hãy liệt kê đầy đủ tên các thành viên, chức vụ, tỉ lệ góp vốn nếu có?

/tmp/ipykernel_59379/595062362.py:84: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

   reranking trên 20 chunks ứng viên...
✅ Câu trả lời của hệ thống: - Đào Công Duy: Tổng Giám đốc, 90%
- Thái Thị Kim Dung: 8%
- Đào Công Dũng: 2%
----------------------------------------
⏳ Đợi 10 giây...

--- Query 15/40 ---
❓ Câu hỏi: Thông tin chi tiết về đầu vào sản xuất kinh doanh là gì?

/tmp/ipykernel_59379/595062362.py:84: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

   reranking trên 20 chunks ứng viên...
✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 16/40 ---
❓ Câu hỏi: Thông tin chi tiết về đầu ra sản xuất kinh doanh là gì?

/tmp/ipykernel_59379/595062362.py:84: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

   reranking trên 20 chunks ứng viên...
✅ Câu trả lời của hệ thống: *   **Nhà máy Eurowindow 1:** Chủ yếu thi công các dự án của Vingroup, các tổng thầu lớn (Hòa Bình, BIM group, ..)
*   **Nhà máy Eurowindow 2:** NSNN: Bộ ban ngành, ACV, TKV, bệnh viện; CĐT tư nhân
*   **Nhà máy Eurowindow 3:** NSNN: Bộ ban ngành, trụ sở cơ quan các tỉnh, ACV, bệnh viện; CĐT tư nhân
*   **Nhà máy Eurowindow 4:** Chủ yếu CĐT tư nhân
*   **Nhà máy Eurowindow 5:** Dự án ngoài nước
----------------------------------------
⏳ Đợi 10 giây...

--- Query 17/40 ---
❓ Câu hỏi: Nhận xét về thông tin khách hàng là gì?

/tmp/ipykernel_59379/595062362.py:84: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

   reranking trên 20 chunks ứng viên...
✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 18/40 ---
❓ Câu hỏi: Nhận xét về pháp lý/GPKD có điều kiện là gì?

/tmp/ipykernel_59379/595062362.py:84: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

   reranking trên 20 chunks ứng viên...
✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 19/40 ---
❓ Câu hỏi: Nhận xét về chủ doanh nghiệp/ban lãnh đạo là gì?

/tmp/ipykernel_59379/595062362.py:84: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

   reranking trên 20 chunks ứng viên...
✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 20/40 ---
❓ Câu hỏi: Nhận xét về KYC là gì?

/tmp/ipykernel_59379/595062362.py:84: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

   reranking trên 20 chunks ứng viên...
✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 21/40 ---
❓ Câu hỏi: Lĩnh vực kinh doanh của công ty là gì?

/tmp/ipykernel_59379/595062362.py:84: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

   reranking trên 20 chunks ứng viên...
✅ Câu trả lời của hệ thống: Cửa nhôm – vách kính mặt dụng và Cửa nhôm – vách kính.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 22/40 ---
❓ Câu hỏi: Sản phẩm/dịch vụ của công ty là gì?

/tmp/ipykernel_59379/595062362.py:84: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

   reranking trên 20 chunks ứng viên...
✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 23/40 ---
❓ Câu hỏi: Tỷ trọng doanh thu năm N-1 (%) là bao nhiêu?

/tmp/ipykernel_59379/595062362.py:84: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

   reranking trên 20 chunks ứng viên...
✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 24/40 ---
❓ Câu hỏi: Tỷ trọng doanh thu năm N (%) là bao nhiêu?

/tmp/ipykernel_59379/595062362.py:84: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

   reranking trên 20 chunks ứng viên...
✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 25/40 ---
❓ Câu hỏi: Nhóm mặt hàng của công ty là gì?

/tmp/ipykernel_59379/595062362.py:84: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

   reranking trên 20 chunks ứng viên...
✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 26/40 ---
❓ Câu hỏi: Tỷ trọng doanh thu năm 2023 là bao nhiêu?

/tmp/ipykernel_59379/595062362.py:84: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

   reranking trên 20 chunks ứng viên...
✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 27/40 ---
❓ Câu hỏi: Tỷ trọng doanh thu 10T/2024 là bao nhiêu?

/tmp/ipykernel_59379/595062362.py:84: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

   reranking trên 20 chunks ứng viên...
✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 28/40 ---
❓ Câu hỏi: Mô tả chung về sản phẩm của công ty là gì?

/tmp/ipykernel_59379/595062362.py:84: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

   reranking trên 20 chunks ứng viên...
✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 29/40 ---
❓ Câu hỏi: Mô tả lợi thế cạnh tranh của công ty là gì?

/tmp/ipykernel_59379/595062362.py:84: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

   reranking trên 20 chunks ứng viên...
✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 30/40 ---
❓ Câu hỏi: Mô tả năng lực đấu thầu của công ty là gì?

/tmp/ipykernel_59379/595062362.py:84: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

   reranking trên 20 chunks ứng viên...
✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 31/40 ---
❓ Câu hỏi: Quy trình vận hành (tóm tắt) của công ty là gì?

/tmp/ipykernel_59379/595062362.py:84: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

   reranking trên 20 chunks ứng viên...
✅ Câu trả lời của hệ thống: *   Nhập phôi kính gia công (gia công nhiệt (tôi kính để tăng tính cường lực), dán (mua phim an toàn), lắp kính hộp
*   Nhập NVL (Nhôm đùn sẵn) Sơn tĩnh điện Cắt Lên khung Lên Ulip Giao sản phẩm
----------------------------------------
⏳ Đợi 10 giây...

--- Query 32/40 ---
❓ Câu hỏi: Đầu vào - mặt hàng là gì?

/tmp/ipykernel_59379/595062362.py:84: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

   reranking trên 20 chunks ứng viên...
✅ Câu trả lời của hệ thống: • Nhập phôi kính gia công (gia công nhiệt (tôi kính để tăng tính cường lực), dán (mua phim an toàn), lắp kính hộp
• Nhập NVL (Nhôm đùn sẵn) Sơn tĩnh điện Cắt Lên khung Lên Ulip Giao sản phẩm
----------------------------------------
⏳ Đợi 10 giây...

--- Query 33/40 ---
❓ Câu hỏi: Đầu vào - chi tiết là gì?

/tmp/ipykernel_59379/595062362.py:84: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

   reranking trên 20 chunks ứng viên...
✅ Câu trả lời của hệ thống: *   Nhập phôi kính gia công (gia công nhiệt (tôi kính để tăng tính cường lực), dán (mua phim an toàn), lắp kính hộp
*   Nhập NVL (Nhôm đùn sẵn) Sơn tĩnh điện Cắt Lên khung Lên Ulip Giao sản phẩm
----------------------------------------
⏳ Đợi 10 giây...

--- Query 34/40 ---
❓ Câu hỏi: Đầu vào - phương thức thanh toán là gì?

/tmp/ipykernel_59379/595062362.py:84: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

   reranking trên 20 chunks ứng viên...
✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 35/40 ---
❓ Câu hỏi: Đầu ra - kênh phân phối là gì?

/tmp/ipykernel_59379/595062362.py:84: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

   reranking trên 20 chunks ứng viên...
✅ Câu trả lời của hệ thống: *   Nhà máy Dương 1: Chủ yếu thi công các dự án của Vingroup, các tổng thầu lớn (Hòa Bình, BIM group, ..)
*   Nhà máy Bình Dương 2: NSNN: Bộ ban ngành, ACV, TKV, bệnh viện, CĐT tư nhân
*   Nhà máy Hà Nội: NSNN: Bộ ban ngành, trụ sở cơ quan các tỉnh, ACV, bệnh viện, CĐT tư nhân
*   Nhà máy Long An: Chủ yếu CĐT tư nhân, Dự án ngoài nước
----------------------------------------
⏳ Đợi 10 giây...

--- Query 36/40 ---
❓ Câu hỏi: Đầu ra - tỷ trọng là bao nhiêu?

/tmp/ipykernel_59379/595062362.py:84: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

   reranking trên 20 chunks ứng viên...
✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 37/40 ---
❓ Câu hỏi: Đầu ra - phương thức thanh toán là gì?

/tmp/ipykernel_59379/595062362.py:84: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

   reranking trên 20 chunks ứng viên...
✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 38/40 ---
❓ Câu hỏi: Nhận xét tổng quan về hoạt động kinh doanh là gì?

/tmp/ipykernel_59379/595062362.py:84: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

   reranking trên 20 chunks ứng viên...
✅ Câu trả lời của hệ thống: Doanh thu dự kiến là 950 tỷ, giá vốn là 752 tỷ, chi phí quản lý là 90 tỷ, chi phí lãi vay là 39 tỷ và lợi nhuận là 55 tỷ.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 39/40 ---
❓ Câu hỏi: Phân tích cung cầu ngành là gì?

/tmp/ipykernel_59379/595062362.py:84: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

   reranking trên 20 chunks ứng viên...
✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 40/40 ---
❓ Câu hỏi: Nhận xét về thông tin ngành là gì?

/tmp/ipykernel_59379/595062362.py:84: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

   reranking trên 20 chunks ứng viên...
✅ Câu trả lời của hệ thống: Nhận xét về thông tin ngành:

*   Nhôm thanh được cắt theo kích thước khung kính, khách hàng có 3 nhà máy lắp ráp & thi công.
*   Các nhà máy sản xuất nhôm thanh.
*   Các công ty thương mại chuyên nhập khẩu nhôm thanh (các mã kích thước lớn).
*   Phun in ký trực tiếp với chủ đầu tư (nếu hợp ký với tổng thầu & CA).
*   Dân dụng: các tòa nhà văn phòng.
*   Thi công trưng bày: lắp đặt tại một số trung tâm thương mại.
*   Ngân sách nhà nước: các tòa nhà ủy ban, trung tâm hành chính.
*   Các mã kích thước nhỏ: có thể sản xuất trong nước.
*   Các mã kích thước lớn: trong nước không sản xuất.
*   Với hàng nguồn gốc nhập khẩu, công ty thường mua thông qua các In và chuyển.
*   Kính không màu: có thể nhập.
*   Kính màu: trong nước không sản xuất.
*   Sản phẩm: may đo theo từng dự án (SP đặc thù).
*   Công ty nhập về sản phẩm.
*   Thông thường kính 2 lớp sẽ trích lúp dễ phòng.
*   Các Ngân hàng đang tài trợ.
----------------------------------------


✅ Đã thu thập xong toàn bộ dữ liệu.

,question,answer,contexts
0,Tên đầy đủ của khách hàng là gì?,CÔNG TY CỔ PHẦN MẶT DỰNG CAG,[| | ...
1,Số giấy phép đăng ký kinh doanh của khách hàng...,Số 0101442420 do Phòng Đăng ký kinh doanh – Sở...,[| | ...
2,ID khách hàng là gì?,22079986,[| | ...
3,Phân khúc của khách hàng là gì?,Dân dụng: các tòa nhà văn phòng\nThi công trưn...,[| [Bản tiếng Việt] | [English Version] |\n|--...
4,Loại khách hàng là gì?,CÔNG TY CỔ PHẦN MẶT DỰNG CAG,[| [Bản tiếng Việt] | [English Version] |\n|--...

✅ Đã lưu kết quả vào file: new/output_parsing/generated_data_for_eval(naive_rerank).json

In [ ]:
# ==============================================================================
# CELL MỚI: THỰC HIỆN ĐÁNH GIÁ BẰNG RAGAS
# ==============================================================================
from utils.ragas_evaluation import RagasEvaluator
import pandas as pd
from pathlib import Path
import json
# 1. Khởi tạo Evaluator
# Đảm bảo GOOGLE_API_KEY đã được định nghĩa ở cell trên
GOOGLE_API_KEYS = ["AIzaSyBH8O5IfqYrJ5wtWnmUC21IfMjzJCrTm3I",
                    "AIzaSyDtBIjTSfbvuEsobNwjtdyi9gVpDrCaWPM",
                    "AIzaSyAD_58r3fQhcTOE6qQS1YlR3iJ_ZnGKy10",
                    "AIzaSyAWtCSrLhJDZGF1ArOSS0o7Iy_zMG42810",
                    "AIzaSyCtAz9maZ9usoxEHhhFocHW07WM4IbgOXo",
                    "AIzaSyCI8QGQrVUgr_FrFLttDs0fP4VyJyPXoec",
                    "AIzaSyBPglAFlDOf97drnNAplHIIsjgvsfzezsI",
                    "AIzaSyCaKzwEjW0XxJAuZ9XdzI6rHkifHkA0eNY",
                    "AIzaSyDNosIJZjXd2tzm7_VKxK5uFTBmoPuHXkc"]

# GOOGLE_API_KEYS = ["AIzaSyCtAz9maZ9usoxEHhhFocHW07WM4IbgOXo"]  

evaluator = RagasEvaluator(list_of_api_keys=GOOGLE_API_KEYS)

# load generated data từ file JSON
generated_data_file = Path('new/output_parsing/generated_data_for_eval(naive_rerank).json')
if not generated_data_file.exists():
    print(f"❌ Lỗi: Không tìm thấy file {generated_data_file}. Vui lòng chạy bước thu thập dữ liệu trước.")
else:
    with open(generated_data_file, 'r', encoding='utf-8') as f:
        generated_data_for_eval = json.load(f)
        
# 2. Tải dataset cơ sở (chứa question và ground_truth)
base_data = evaluator.load_base_dataset('/root/chatbot1/chatbot_document/backend/schemas/ragasdf_base.json')

# 3. Chuẩn bị dataset hoàn chỉnh bằng cách kết hợp base_data và generated_data
eval_dataset = evaluator.prepare_evaluation_dataset(
    base_data=base_data,
    generated_data=generated_data_for_eval # Sử dụng kết quả từ cell trước
)

# 4. Xuất file dataset RAGAS hoàn chỉnh ra Excel để kiểm tra
if eval_dataset:
    ragas_df = eval_dataset.to_pandas()
    ragas_df['context_count'] = ragas_df['contexts'].apply(len)
    output_df_path = "new/ragasdf/ragas_dataset_for_evaluation(naive_rerank).xlsx"
    os.makedirs(Path(output_df_path).parent, exist_ok=True)
    ragas_df.to_excel(output_df_path, index=False)
    print(f"💾 Đã xuất file dataset RAGAS hoàn chỉnh ra: {output_df_path}")
    print("Đây là 5 dòng đầu tiên của dataset sẽ được đánh giá:")
    display(ragas_df.head())
    
# 5. Chạy đánh giá
if eval_dataset:
    results_df = evaluator.run_evaluation(eval_dataset)

    if results_df is not None:
        # 6. Hiển thị và lưu báo cáo
        print("\n\n--- 📊 KẾT QUẢ ĐÁNH GIÁ CHI TIẾT ---")
        display(results_df)

        evaluator.save_report(results_df, "/root/chatbot1/chatbot_document/backend/new/evaluation_reports", "ragas_report(naive_rerank).xlsx")
    else:
        print("❌ Đánh giá không trả về kết quả.")
else:
    print("❌ Không thể tạo dataset để đánh giá.")

🚀 Khởi tạo RagasEvaluator (có Retry & Key Switching)...

WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.

✅ LLM và Embeddings đã sẵn sàng.
📋 Đã định nghĩa 12 metrics: ['faithfulness', 'answer_relevancy', 'context_precision', 'context_recall', 'semantic_similarity', 'answer_correctness', 'factual_correctness', 'exact_match', 'bleu_score', 'rouge_score', 'semantic_similarity', 'non_llm_string_similarity']
📁 Đã tạo thư mục báo cáo: evaluation_reports
📂 Đang tải base dataset từ: /root/chatbot1/chatbot_document/backend/schemas/ragasdf_base.json
✅ Tải thành công 40 mẫu.
🔄 Đang chuẩn bị dataset để đánh giá...
✅ Đã chuẩn hóa cột 'contexts' với kiểu dữ liệu: <class 'list'>
✅ Đã tạo thành công dataset với 40 mẫu để đánh giá.
✅ Kiểu dữ liệu của cột 'contexts' đã được xác nhận là: <class 'list'>
✅ Sau khi loại bỏ null/empty, còn 16 mẫu.
✅ Đã thêm cột 'reference' từ ground_truths.
💾 Đã xuất file dataset RAGAS hoàn chỉnh ra: new/ragasdf/ragas_dataset_for_evaluation(naive_rerank).xlsx
Đây là 5 dòng đầu tiên của dataset sẽ được đánh giá:

,question,ground_truths,answer,contexts,reference,__index_level_0__,context_count
0,Tên đầy đủ của khách hàng là gì?,[CÔNG TY CỔ PHẦN MẶT DỰNG CAG],CÔNG TY CỔ PHẦN MẶT DỰNG CAG,[| | ...,CÔNG TY CỔ PHẦN MẶT DỰNG CAG,0,3
1,Số giấy phép đăng ký kinh doanh của khách hàng...,[0101442420],Số 0101442420 do Phòng Đăng ký kinh doanh – Sở...,[| | ...,0101442420,1,3
2,ID khách hàng là gì?,[22079986],22079986,[| | ...,22079986,2,3
3,Phân khúc của khách hàng là gì?,[MM],Dân dụng: các tòa nhà văn phòng\nThi công trưn...,[| [Bản tiếng Việt] | [English Version] |\n|--...,MM,3,3
4,"XHTD của khách hàng là gì?, XHTD là xếp hạng t...",[Aa3],Tôi không tìm thấy thông tin trong tài liệu.,[| [Bản tiếng Việt] | [English Version] |\n|--...,Aa3,8,3

✅ Dataset schema hợp lệ. Columns: ['question', 'ground_truths', 'answer', 'contexts', 'reference', '__index_level_0__']

🔬 Bắt đầu đánh giá RAGAS trên 16 mẫu với 12 metrics...
📋 Metrics: ['faithfulness', 'answer_relevancy', 'context_precision', 'context_recall', 'semantic_similarity', 'answer_correctness', 'factual_correctness', 'exact_match', 'bleu_score', 'rouge_score', 'semantic_similarity', 'non_llm_string_similarity']

--- 🔄 Đang đánh giá dòng 1/16 ---
   Q: Tên đầy đủ của khách hàng là gì?...
    🔄 Metric 1/12: faithfulness
    ✅ faithfulness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/12: answer_relevancy

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 22
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 21
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 21
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 18
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 17
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 17
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 13
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ✅ answer_relevancy: 0.5499842136430825
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/12: context_precision

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 55
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 50
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ✅ context_precision: 0.9999999999
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/12: context_recall
    ✅ context_recall: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/12: semantic_similarity
    ✅ semantic_similarity: 0.9999999999999999
    🔄 Metric 6/12: answer_correctness
    ✅ answer_correctness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 7/12: factual_correctness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 7
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 4
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ✅ factual_correctness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 8/12: exact_match
    ✅ exact_match: 1.0
    🔄 Metric 9/12: bleu_score
    ✅ bleu_score: 1.0000000000000004
    🔄 Metric 10/12: rouge_score
    ✅ rouge_score: 1.0
    🔄 Metric 11/12: semantic_similarity
    ✅ semantic_similarity: 0.9999999999999999
    🔄 Metric 12/12: non_llm_string_similarity
    ✅ non_llm_string_similarity: 1.0
✅ Đánh giá dòng 1 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 2/16 ---
   Q: Số giấy phép đăng ký kinh doanh của khách hàng là gì?...
    🔄 Metric 1/12: faithfulness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 37
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 33
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 29
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ✅ faithfulness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/12: answer_relevancy

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 12
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 11
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 8
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 7
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 4
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 3
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 56
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 56
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 51
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 40
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 39
}
].

    ✅ answer_relevancy: 0.6719130607265376
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/12: context_precision

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 25
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 20
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 16
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 12
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 5
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 59
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 52
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 15
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 25
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ✅ context_precision: 0.9999999999
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/12: context_recall
    ✅ context_recall: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/12: semantic_similarity
    ✅ semantic_similarity: 0.5900985813694843
    🔄 Metric 6/12: answer_correctness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 50
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 46
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 40
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 36
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 32
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 26
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 21
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 8
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 34
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 29
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 39
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 34
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá answer_correctness cho dòng 2: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 31
}
]
    🔄 Metric 7/12: factual_correctness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 30
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 26
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 21
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 14
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 5
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 52
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 43
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 29
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 25
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 47
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá factual_correctness cho dòng 2: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 45
}
]
    🔄 Metric 8/12: exact_match
    ✅ exact_match: 0.0
    🔄 Metric 9/12: bleu_score
    ✅ bleu_score: 0.008130350574508933
    🔄 Metric 10/12: rouge_score
    ✅ rouge_score: 0.04166666666666667
    🔄 Metric 11/12: semantic_similarity
    ✅ semantic_similarity: 0.5900985813694843
    🔄 Metric 12/12: non_llm_string_similarity
    ✅ non_llm_string_similarity: 0.06134969325153372
✅ Đánh giá dòng 2 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 3/16 ---
   Q: ID khách hàng là gì?...
    🔄 Metric 1/12: faithfulness
    ✅ faithfulness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/12: answer_relevancy

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 20
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 19
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 19
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 15
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 10
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 3
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 54
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 47
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 29
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ✅ answer_relevancy: 0.2241125251783769
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/12: context_precision
    ✅ context_precision: 0.99999999995
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/12: context_recall
    ✅ context_recall: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/12: semantic_similarity
    ✅ semantic_similarity: 1.0
    🔄 Metric 6/12: answer_correctness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 10
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 7
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 4
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 59
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 52
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 43
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 22
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 17
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 37
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 1
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 20
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá answer_correctness cho dòng 3: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 18
}
]
    🔄 Metric 7/12: factual_correctness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 18
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 14
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 9
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 2
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 52
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 38
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 22
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 37
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 28
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 25
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá factual_correctness cho dòng 3: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 23
}
]
    🔄 Metric 8/12: exact_match
    ✅ exact_match: 1.0
    🔄 Metric 9/12: bleu_score
    ✅ bleu_score: 0.0
    🔄 Metric 10/12: rouge_score
    ✅ rouge_score: 1.0
    🔄 Metric 11/12: semantic_similarity
    ✅ semantic_similarity: 1.0
    🔄 Metric 12/12: non_llm_string_similarity
    ✅ non_llm_string_similarity: 1.0
✅ Đánh giá dòng 3 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 4/16 ---
   Q: Phân khúc của khách hàng là gì?...
    🔄 Metric 1/12: faithfulness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 10
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 6
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 2
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 55
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 51
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 45
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 29
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 19
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 12
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 25
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá faithfulness cho dòng 4: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 23
}
]
    🔄 Metric 2/12: answer_relevancy

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 21
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 17
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 13
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 9
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 4
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 55
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 38
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 57
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 41
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 26
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá answer_relevancy cho dòng 4: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 24
}
]
    🔄 Metric 3/12: context_precision

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 23
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 19
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 14
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 7
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 4
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 57
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 33
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 23
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 19
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 38
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá context_precision cho dòng 4: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 35
}
]
    🔄 Metric 4/12: context_recall

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 35
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 30
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 26
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 21
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 15
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 3
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 52
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 9
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 10
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 23
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá context_recall cho dòng 4: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 20
}
]
    🔄 Metric 5/12: semantic_similarity
    ✅ semantic_similarity: 0.38030646327347917
    🔄 Metric 6/12: answer_correctness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 17
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 14
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 10
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 5
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 57
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 49
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 41
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 33
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 59
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 20
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá answer_correctness cho dòng 4: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 17
}
]
    🔄 Metric 7/12: factual_correctness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 17
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 13
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 8
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 5
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 54
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 40
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 26
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 45
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 34
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 53
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá factual_correctness cho dòng 4: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 50
}
]
    🔄 Metric 8/12: exact_match
    ✅ exact_match: 0.0
    🔄 Metric 9/12: bleu_score
    ✅ bleu_score: 0.0
    🔄 Metric 10/12: rouge_score
    ✅ rouge_score: 0.0
    🔄 Metric 11/12: semantic_similarity
    ✅ semantic_similarity: 0.38030646327347917
    🔄 Metric 12/12: non_llm_string_similarity
    ✅ non_llm_string_similarity: 0.0
✅ Đánh giá dòng 4 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 5/16 ---
   Q: XHTD của khách hàng là gì?, XHTD là xếp hạng tín dụng của khách hàng và thường có các giá trị như Aa...
    🔄 Metric 1/12: faithfulness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 37
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 33
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 29
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 23
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 12
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 21
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 34
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 57
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 2
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá faithfulness cho dòng 5: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
}
]
    🔄 Metric 2/12: answer_relevancy

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 59
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 59
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 59
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 55
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 54
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 53
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 51
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 49
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 49
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 45
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 44
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 44
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 38
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 37
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 32
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 20
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 19
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 13
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 10
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 48
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 42
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 35
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 24
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 3
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 40
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 30
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 14
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 58
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá answer_relevancy cho dòng 5: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 55
}
]
    🔄 Metric 3/12: context_precision

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 54
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 51
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 48
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 46
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 41
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 32
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 31
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 20
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 9
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 45
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 22
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 35
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá context_precision cho dòng 5: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 33
}
]
    🔄 Metric 4/12: context_recall

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 32
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 28
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 25
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 20
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 14
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 2
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 25
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 50
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 23
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá context_recall cho dòng 5: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 57
}
]
    🔄 Metric 5/12: semantic_similarity
    ✅ semantic_similarity: 0.4144482595235611
    🔄 Metric 6/12: answer_correctness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 56
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 52
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 49
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 44
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 39
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 22
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 51
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 40
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 54
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 44
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá answer_correctness cho dòng 5: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 42
}
]
    🔄 Metric 7/12: factual_correctness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 42
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 37
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 33
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 28
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 17
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 9
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 28
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 34
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 54
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá factual_correctness cho dòng 5: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 52
}
]
    🔄 Metric 8/12: exact_match
    ✅ exact_match: 0.0
    🔄 Metric 9/12: bleu_score
    ✅ bleu_score: 0.0
    🔄 Metric 10/12: rouge_score
    ✅ rouge_score: 0.0
    🔄 Metric 11/12: semantic_similarity
    ✅ semantic_similarity: 0.4144482595235611
    🔄 Metric 12/12: non_llm_string_similarity
    ✅ non_llm_string_similarity: 0.0
✅ Đánh giá dòng 5 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 6/16 ---
   Q: Ngày thành lập công ty là ngày nào?...
    🔄 Metric 1/12: faithfulness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 39
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 36
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 31
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 25
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 20
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 10
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 49
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 9
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 28
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 26
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá faithfulness cho dòng 6: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 24
}
]
    🔄 Metric 2/12: answer_relevancy

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 23
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 23
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 23
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 20
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 19
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 18
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 16
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 14
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 13
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 11
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 8
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 8
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 6
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 3
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 49
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 48
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 42
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 30
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 17
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 14
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 3
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 24
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 19
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 17
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 51
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 40
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá answer_relevancy cho dòng 6: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 38
}
]
    🔄 Metric 3/12: context_precision

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 37
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 33
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 28
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 21
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 17
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 10
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 9
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 56
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 37
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 32
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 16
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 48
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 49
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá context_precision cho dòng 6: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 46
}
]
    🔄 Metric 4/12: context_recall

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 45
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 41
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 36
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 31
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 22
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 15
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 38
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 3
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 23
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 14
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá context_recall cho dòng 6: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 12
}
]
    🔄 Metric 5/12: semantic_similarity
    ✅ semantic_similarity: 0.438320099484923
    🔄 Metric 6/12: answer_correctness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 9
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 5
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 1
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 56
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 47
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 28
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 1
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 56
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 19
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 13
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá answer_correctness cho dòng 6: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 11
}
]
    🔄 Metric 7/12: factual_correctness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 9
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 5
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 57
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 46
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 26
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 13
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 1
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 50
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 23
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá factual_correctness cho dòng 6: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 21
}
]
    🔄 Metric 8/12: exact_match
    ✅ exact_match: 0.0
    🔄 Metric 9/12: bleu_score
    ✅ bleu_score: 0.0
    🔄 Metric 10/12: rouge_score
    ✅ rouge_score: 0.0
    🔄 Metric 11/12: semantic_similarity
    ✅ semantic_similarity: 0.438320099484923
    🔄 Metric 12/12: non_llm_string_similarity
    ✅ non_llm_string_similarity: 0.0
✅ Đánh giá dòng 6 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 7/16 ---
   Q: Địa chỉ đăng ký kinh doanh của công ty là gì?...
    🔄 Metric 1/12: faithfulness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 8
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 4
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 59
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 54
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 49
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 43
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 32
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 7
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 10
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 36
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá faithfulness cho dòng 7: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 34
}
]
    🔄 Metric 2/12: answer_relevancy

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 32
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 32
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 32
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 29
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 28
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 27
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 24
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 24
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 23
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 18
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 18
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 17
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 10
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 9
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 8
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 59
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 53
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 48
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 34
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 25
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 23
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 21
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 6
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 29
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 27
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá answer_relevancy cho dòng 7: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 25
}
]
    🔄 Metric 3/12: context_precision

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 23
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 23
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 19
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 15
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 10
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 59
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 49
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 36
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 34
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 24
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 52
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 47
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 44
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 14
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 12
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá context_precision cho dòng 7: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 9
}
]
    🔄 Metric 4/12: context_recall

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 9
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 5
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 2
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 57
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 46
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 26
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 4
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 19
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 52
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 37
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá context_recall cho dòng 7: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 34
}
]
    🔄 Metric 5/12: semantic_similarity
    ✅ semantic_similarity: 1.0
    🔄 Metric 6/12: answer_correctness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 32
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 27
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 24
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 17
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 7
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 3
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 54
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 49
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 47
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá answer_correctness cho dòng 7: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 44
}
]
    🔄 Metric 7/12: factual_correctness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 43
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 38
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 34
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 31
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 21
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 15
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 59
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 50
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 17
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 48
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá factual_correctness cho dòng 7: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 46
}
]
    🔄 Metric 8/12: exact_match
    ✅ exact_match: 1.0
    🔄 Metric 9/12: bleu_score
    ✅ bleu_score: 1.0000000000000004
    🔄 Metric 10/12: rouge_score
    ✅ rouge_score: 1.0
    🔄 Metric 11/12: semantic_similarity
    ✅ semantic_similarity: 1.0
    🔄 Metric 12/12: non_llm_string_similarity
    ✅ non_llm_string_similarity: 1.0
✅ Đánh giá dòng 7 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 8/16 ---
   Q: Người đại diện theo pháp luật của công ty là ai?...
    🔄 Metric 1/12: faithfulness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 32
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 28
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 24
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 17
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 5
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 45
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 36
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 58
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 18
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 41
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá faithfulness cho dòng 8: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 38
}
]
    🔄 Metric 2/12: answer_relevancy

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 37
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 37
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 37
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 33
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 33
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 32
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 30
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 28
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 28
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 24
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 23
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 22
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 18
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 16
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 14
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 9
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 59
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 39
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 38
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 34
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 57
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 51
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 25
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 18
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 13
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 9
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 38
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá answer_relevancy cho dòng 8: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 35
}
]
    🔄 Metric 3/12: context_precision

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 34
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 33
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 31
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 25
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 22
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 10
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 5
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 55
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 28
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 16
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 8
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 11
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá context_precision cho dòng 8: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 8
}
]
    🔄 Metric 4/12: context_recall

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 8
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 4
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 59
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 51
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 44
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 39
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 20
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 13
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 8
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 52
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá context_recall cho dòng 8: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 49
}
]
    🔄 Metric 5/12: semantic_similarity
    ✅ semantic_similarity: 0.7969774567338391
    🔄 Metric 6/12: answer_correctness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 47
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 43
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 38
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 32
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 25
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 13
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 59
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 39
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 31
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 29
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá answer_correctness cho dòng 8: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 27
}
]
    🔄 Metric 7/12: factual_correctness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 26
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 22
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 18
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 14
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 4
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 46
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 40
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 10
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 38
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 51
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá factual_correctness cho dòng 8: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 49
}
]
    🔄 Metric 8/12: exact_match
    ✅ exact_match: 0.0
    🔄 Metric 9/12: bleu_score
    ✅ bleu_score: 0.12605968092174913
    🔄 Metric 10/12: rouge_score
    ✅ rouge_score: 0.4210526315789474
    🔄 Metric 11/12: semantic_similarity
    ✅ semantic_similarity: 0.7969774567338391
    🔄 Metric 12/12: non_llm_string_similarity
    ✅ non_llm_string_similarity: 0.2790697674418605
✅ Đánh giá dòng 8 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 9/16 ---
   Q: Khách hàng có kinh doanh ngành nghề có điều kiện không?...
    🔄 Metric 1/12: faithfulness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 35
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 31
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 26
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 21
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 14
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 9
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 53
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 44
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 10
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 45
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá faithfulness cho dòng 9: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 43
}
]
    🔄 Metric 2/12: answer_relevancy

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 42
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 41
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 41
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 39
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 38
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 37
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 35
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 33
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 33
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 30
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 28
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 28
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 21
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 21
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 21
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 14
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 3
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 1
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 52
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 42
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 37
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 28
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 7
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 54
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 41
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 40
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 36
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 26
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 26
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá answer_relevancy cho dòng 9: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 24
}
]
    🔄 Metric 3/12: context_precision
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 22
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 19
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 16
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 10
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 10
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 58
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 43
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 38
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 39
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 35
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 14
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá context_precision cho dòng 9: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 12
}
]
    🔄 Metric 4/12: context_recall

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 11
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 7
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 3
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 58
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 50
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 38
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 29
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 4
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 13
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 9
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá context_recall cho dòng 9: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 7
}
]
    🔄 Metric 5/12: semantic_similarity
    ✅ semantic_similarity: 0.4436944308523454
    🔄 Metric 6/12: answer_correctness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 5
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 1
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 57
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 54
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 50
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 37
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 25
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 42
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 37
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 40
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá answer_correctness cho dòng 9: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 37
}
]
    🔄 Metric 7/12: factual_correctness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 37
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 33
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 28
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 22
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 20
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 4
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 40
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 15
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 35
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 59
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá factual_correctness cho dòng 9: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 56
}
]
    🔄 Metric 8/12: exact_match
    ✅ exact_match: 0.0
    🔄 Metric 9/12: bleu_score
    ✅ bleu_score: 0.0
    🔄 Metric 10/12: rouge_score
    ✅ rouge_score: 0.0
    🔄 Metric 11/12: semantic_similarity
    ✅ semantic_similarity: 0.4436944308523454
    🔄 Metric 12/12: non_llm_string_similarity
    ✅ non_llm_string_similarity: 0.0
✅ Đánh giá dòng 9 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 10/16 ---
   Q: Thông tin chi tiết về ban lãnh đạo công ty là gì. Hãy liệt kê đầy đủ tên các thành viên, chức vụ, tỉ...
    🔄 Metric 1/12: faithfulness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 44
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 41
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 38
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 32
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 24
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 8
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 5
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 35
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 31
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá faithfulness cho dòng 10: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 29
}
]
    🔄 Metric 2/12: answer_relevancy

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 27
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 27
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 27
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 24
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 23
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 23
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 20
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 19
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 18
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 13
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 13
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 13
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 8
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 7
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 5
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 59
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 58
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 58
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 47
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 34
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 33
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 52
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 39
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 18
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 14
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 5
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 56
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá answer_relevancy cho dòng 10: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 54
}
]
    🔄 Metric 3/12: context_precision

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 54
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 53
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 50
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 46
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 41
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 38
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 29
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 16
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 11
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 45
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 2
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 35
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá context_precision cho dòng 10: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 33
}
]
    🔄 Metric 4/12: context_recall

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 32
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 27
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 24
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 17
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 6
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 54
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 50
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 20
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 2
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 1
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá context_recall cho dòng 10: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 59
}
]
    🔄 Metric 5/12: semantic_similarity
    ✅ semantic_similarity: 0.7196958273949716
    🔄 Metric 6/12: answer_correctness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 51
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 48
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 43
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 38
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 33
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 25
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 7
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 15
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 43
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 44
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá answer_correctness cho dòng 10: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 42
}
]
    🔄 Metric 7/12: factual_correctness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 41
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 37
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 33
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 26
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 21
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 7
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 44
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 33
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 58
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 45
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá factual_correctness cho dòng 10: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 42
}
]
    🔄 Metric 8/12: exact_match
    ✅ exact_match: 0.0
    🔄 Metric 9/12: bleu_score
    ✅ bleu_score: 0.0036317732883193897
    🔄 Metric 10/12: rouge_score
    ✅ rouge_score: 0.5384615384615384
    🔄 Metric 11/12: semantic_similarity
    ✅ semantic_similarity: 0.7196958273949716
    🔄 Metric 12/12: non_llm_string_similarity
    ✅ non_llm_string_similarity: 0.19999999999999996
✅ Đánh giá dòng 10 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 11/16 ---
   Q: Thông tin chi tiết về đầu vào sản xuất kinh doanh là gì?...
    🔄 Metric 1/12: faithfulness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 24
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 20
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 15
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 12
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 6
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 55
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 22
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 17
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 14
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 12
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá faithfulness cho dòng 11: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 9
}
]
    🔄 Metric 2/12: answer_relevancy

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 9
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 8
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 8
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 5
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 4
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 3
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 1
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 59
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 59
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 55
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 55
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 54
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 50
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 50
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 45
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 45
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 38
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 28
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 26
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 21
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 19
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 55
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 54
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 26
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 19
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 11
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 5
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá answer_relevancy cho dòng 11: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 3
}
]
    🔄 Metric 3/12: context_precision

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 2
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 58
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 54
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 51
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 48
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 39
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 35
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 33
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 21
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 52
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 28
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 51
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 2
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá context_precision cho dòng 11: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
}
]
    🔄 Metric 4/12: context_recall

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 59
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 55
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 52
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 47
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 43
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 28
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 11
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 17
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 36
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 45
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá context_recall cho dòng 11: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 42
}
]
    🔄 Metric 5/12: semantic_similarity
    ✅ semantic_similarity: 0.3287032038185591
    🔄 Metric 6/12: answer_correctness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 39
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 35
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 31
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 25
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 18
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 3
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 46
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 36
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 39
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 35
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá answer_correctness cho dòng 11: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 33
}
]
    🔄 Metric 7/12: factual_correctness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 32
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 28
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 23
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 18
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 10
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 58
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 44
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 57
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 5
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 38
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá factual_correctness cho dòng 11: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 36
}
]
    🔄 Metric 8/12: exact_match
    ✅ exact_match: 0.0
    🔄 Metric 9/12: bleu_score
    ✅ bleu_score: 0.018382465348186564
    🔄 Metric 10/12: rouge_score
    ✅ rouge_score: 0.18421052631578946
    🔄 Metric 11/12: semantic_similarity
    ✅ semantic_similarity: 0.3287032038185591
    🔄 Metric 12/12: non_llm_string_similarity
    ✅ non_llm_string_similarity: 0.1497584541062802
✅ Đánh giá dòng 11 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 12/16 ---
   Q: Thông tin chi tiết về đầu ra sản xuất kinh doanh là gì?...
    🔄 Metric 1/12: faithfulness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 21
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 17
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 13
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 8
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 4
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 44
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 20
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 17
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 43
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 6
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá faithfulness cho dòng 12: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 3
}
]
    🔄 Metric 2/12: answer_relevancy

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 3
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 2
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 2
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 59
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 58
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 57
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 54
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 53
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 53
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 48
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 47
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 47
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 43
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 40
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 40
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 33
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 32
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 25
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 24
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 17
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 3
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 54
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 41
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 39
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 24
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 51
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 50
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá answer_relevancy cho dòng 12: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 47
}
]
    🔄 Metric 3/12: context_precision

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 46
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 43
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 43
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 39
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 36
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 31
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 18
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 5
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 57
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 55
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 36
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 10
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 29
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá context_precision cho dòng 12: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 27
}
]
    🔄 Metric 4/12: context_recall

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 26
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 22
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 18
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 11
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 6
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 49
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 34
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 12
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 11
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá context_recall cho dòng 12: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 58
}
]
    🔄 Metric 5/12: semantic_similarity
    ✅ semantic_similarity: 0.3134284446937665
    🔄 Metric 6/12: answer_correctness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 51
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 47
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 43
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 38
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 30
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 21
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 53
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 43
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 3
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá answer_correctness cho dòng 12: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 1
}
]
    🔄 Metric 7/12: factual_correctness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 1
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 57
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 51
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 47
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 36
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 30
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 23
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 19
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 52
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 25
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá factual_correctness cho dòng 12: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 23
}
]
    🔄 Metric 8/12: exact_match
    ✅ exact_match: 0.0
    🔄 Metric 9/12: bleu_score
    ✅ bleu_score: 0.004461680717178894
    🔄 Metric 10/12: rouge_score
    ✅ rouge_score: 0.0
    🔄 Metric 11/12: semantic_similarity
    ✅ semantic_similarity: 0.3134284446937665
    🔄 Metric 12/12: non_llm_string_similarity
    ✅ non_llm_string_similarity: 0.06045340050377834
✅ Đánh giá dòng 12 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 13/16 ---
   Q: Lĩnh vực kinh doanh của công ty là gì?...
    🔄 Metric 1/12: faithfulness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 6
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 3
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 59
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 54
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 47
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 29
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 59
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 30
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 27
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 28
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá faithfulness cho dòng 13: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 25
}
]
    🔄 Metric 2/12: answer_relevancy

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 24
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 24
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 24
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 20
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 19
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 19
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 17
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 16
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 15
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 10
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 10
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 9
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 4
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 4
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 2
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 57
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 56
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 53
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 52
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 46
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 30
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 26
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 12
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 10
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 1
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 14
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 13
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 12
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá answer_relevancy cho dòng 13: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 11
}
]
    🔄 Metric 3/12: context_precision
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 10
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 6
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 1
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 57
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 46
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 41
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 35
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 16
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 12
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 15
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 7
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 34
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá context_precision cho dòng 13: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 31
}
]
    🔄 Metric 4/12: context_recall

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 31
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 26
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 22
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 18
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 9
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 57
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 54
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 38
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 35
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 53
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá context_recall cho dòng 13: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 51
}
]
    🔄 Metric 5/12: semantic_similarity
    ✅ semantic_similarity: 0.4269171815934031
    🔄 Metric 6/12: answer_correctness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 49
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 45
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 42
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 37
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 30
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 21
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 57
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 51
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 7
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 51
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá answer_correctness cho dòng 13: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 49
}
]
    🔄 Metric 7/12: factual_correctness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 48
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 44
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 38
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 33
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 28
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 18
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 28
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 9
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 53
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá factual_correctness cho dòng 13: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 50
}
]
    🔄 Metric 8/12: exact_match
    ✅ exact_match: 0.0
    🔄 Metric 9/12: bleu_score
    ✅ bleu_score: 0.0
    🔄 Metric 10/12: rouge_score
    ✅ rouge_score: 0.12903225806451613
    🔄 Metric 11/12: semantic_similarity
    ✅ semantic_similarity: 0.4269171815934031
    🔄 Metric 12/12: non_llm_string_similarity
    ✅ non_llm_string_similarity: 0.14814814814814814
✅ Đánh giá dòng 13 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 14/16 ---
   Q: Sản phẩm/dịch vụ của công ty là gì?...
    🔄 Metric 1/12: faithfulness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 38
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 34
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 31
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 25
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 18
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 13
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 57
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 7
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 41
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 24
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá faithfulness cho dòng 14: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 22
}
]
    🔄 Metric 2/12: answer_relevancy

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 22
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 21
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 21
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 19
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 17
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 17
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 14
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 13
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 13
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 9
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 8
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 7
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 3
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 2
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 1
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 57
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 54
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 53
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 43
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 40
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 40
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 34
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 17
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 53
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 51
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 25
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá answer_relevancy cho dòng 14: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 23
}
]
    🔄 Metric 3/12: context_precision

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 21
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 21
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 19
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 14
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 7
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 3
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 58
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 54
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 49
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 28
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 3
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 59
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 3
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 28
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá context_precision cho dòng 14: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 26
}
]
    🔄 Metric 4/12: context_recall

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 26
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 22
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 18
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 12
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 3
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 51
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 29
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 47
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 18
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá context_recall cho dòng 14: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 15
}
]
    🔄 Metric 5/12: semantic_similarity
    ✅ semantic_similarity: 0.2527020544501609
    🔄 Metric 6/12: answer_correctness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 13
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 9
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 4
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 53
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 34
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 10
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 31
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 41
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 45
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá answer_correctness cho dòng 14: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 43
}
]
    🔄 Metric 7/12: factual_correctness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 41
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 35
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 32
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 27
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 21
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 16
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 57
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 52
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 49
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 54
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 50
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 48
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 42
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 33
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 14
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 48
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 44
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 40
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 35
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 31
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 21
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 3
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 43
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 52
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 2
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 13
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá factual_correctness cho dòng 14: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 11
}
]
    🔄 Metric 8/12: exact_match
    ✅ exact_match: 0.0
    🔄 Metric 9/12: bleu_score
    ✅ bleu_score: 0.0
    🔄 Metric 10/12: rouge_score
    ✅ rouge_score: 0.2857142857142857
    🔄 Metric 11/12: semantic_similarity
    ✅ semantic_similarity: 0.2527020544501609
    🔄 Metric 12/12: non_llm_string_similarity
    ✅ non_llm_string_similarity: 0.21739130434782605
✅ Đánh giá dòng 14 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 15/16 ---
   Q: Đầu vào - mặt hàng là gì?...
    🔄 Metric 1/12: faithfulness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 59
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 55
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 51
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 47
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 42
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 36
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 22
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 11
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 7
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 54
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá faithfulness cho dòng 15: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 52
}
]
    🔄 Metric 2/12: answer_relevancy

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 50
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 50
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 47
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 45
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 43
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 41
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 37
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 37
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 33
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 27
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 57
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 46
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 1
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 52
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá answer_relevancy cho dòng 15: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 50
}
]
    🔄 Metric 3/12: context_precision

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 49
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 46
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 40
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 33
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 23
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 5
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 37
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 11
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 35
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 48
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá context_precision cho dòng 15: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 46
}
]
    🔄 Metric 4/12: context_recall

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 45
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 41
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 37
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 31
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 19
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 6
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 49
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 53
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 31
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 54
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá context_recall cho dòng 15: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 51
}
]
    🔄 Metric 5/12: semantic_similarity
    ✅ semantic_similarity: 0.6123810210044843
    🔄 Metric 6/12: answer_correctness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 48
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 44
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 39
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 33
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 24
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 8
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 37
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 13
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 45
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 1
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá answer_correctness cho dòng 15: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 59
}
]
    🔄 Metric 7/12: factual_correctness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 58
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 53
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 49
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 45
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 36
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 27
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 5
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 56
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 51
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 46
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 37
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 24
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 17
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 55
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 39
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 46
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá factual_correctness cho dòng 15: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 44
}
]
    🔄 Metric 8/12: exact_match
    ✅ exact_match: 0.0
    🔄 Metric 9/12: bleu_score
    ✅ bleu_score: 0.017342679817088317
    🔄 Metric 10/12: rouge_score
    ✅ rouge_score: 0.136986301369863
    🔄 Metric 11/12: semantic_similarity
    ✅ semantic_similarity: 0.6123810210044843
    🔄 Metric 12/12: non_llm_string_similarity
    ✅ non_llm_string_similarity: 0.09473684210526312
✅ Đánh giá dòng 15 hoàn tất.
⏳ Chờ 8.0s trước khi xử lý dòng tiếp theo...

--- 🔄 Đang đánh giá dòng 16/16 ---
   Q: Đầu vào - chi tiết là gì?...
    🔄 Metric 1/12: faithfulness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 30
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 26
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 20
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 13
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 4
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 55
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 44
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 55
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 3
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 24
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá faithfulness cho dòng 16: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 21
}
]
    🔄 Metric 2/12: answer_relevancy

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 20
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 20
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 20
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 16
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 15
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 15
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 12
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 10
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 10
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 8
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 5
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 2
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 56
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 52
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 45
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 27
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 26
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 35
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 29
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 25
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 17
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 3
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá answer_relevancy cho dòng 16: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
}
]
    🔄 Metric 3/12: context_precision

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 59
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 55
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 49
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 43
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 43
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 35
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 16
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 53
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 29
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 25
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 11
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá context_precision cho dòng 16: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 9
}
]
    🔄 Metric 4/12: context_recall

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 8
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 3
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 1
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 54
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 43
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 27
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 1
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 5
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 59
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 25
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá context_recall cho dòng 16: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 23
}
]
    🔄 Metric 5/12: semantic_similarity
    ✅ semantic_similarity: 0.5737442699953004
    🔄 Metric 6/12: answer_correctness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 18
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 14
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 9
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 4
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 42
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 26
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 35
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 26
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 53
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá answer_correctness cho dòng 16: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 50
}
]
    🔄 Metric 7/12: factual_correctness

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 50
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 46
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 41
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 36
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 30
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 22
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 2
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 32
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 11
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 8
🔄 Đã chuyển sang API key index 8: AIzaSyDN...uHXkc
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 26
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 0
🔄 Đã chuyển sang API key index 0: AIzaSyBH...rTm3I
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ❌ Lỗi đánh giá factual_correctness cho dòng 16: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 24
}
]
    🔄 Metric 8/12: exact_match
    ✅ exact_match: 0.0
    🔄 Metric 9/12: bleu_score
    ✅ bleu_score: 0.00959641509636166
    🔄 Metric 10/12: rouge_score
    ✅ rouge_score: 0.29565217391304355
    🔄 Metric 11/12: semantic_similarity
    ✅ semantic_similarity: 0.5737442699953004
    🔄 Metric 12/12: non_llm_string_similarity
    ✅ non_llm_string_similarity: 0.2628865979381443
✅ Đánh giá dòng 16 hoàn tất.

--- ✅ Tất cả các dòng đã được đánh giá. Tổng hợp kết quả... ---
📊 Kết quả có 16 dòng và 11 cột metrics.


--- 📊 KẾT QUẢ ĐÁNH GIÁ CHI TIẾT ---

,faithfulness,answer_relevancy,context_precision,context_recall,semantic_similarity,answer_correctness,factual_correctness,exact_match,bleu_score,rouge_score(mode=fmeasure),non_llm_string_similarity
0,1.0,0.549984,1.0,1.0,1.000000,1.0,1.0,1.0,1.000000,1.000000,1.000000
1,1.0,0.671913,1.0,1.0,0.590099,0.0,0.0,0.0,0.008130,0.041667,0.061350
2,1.0,0.224113,1.0,1.0,1.000000,0.0,0.0,1.0,0.000000,1.000000,1.000000
3,0.0,0.000000,0.0,0.0,0.380306,0.0,0.0,0.0,0.000000,0.000000,0.000000
4,0.0,0.000000,0.0,0.0,0.414448,0.0,0.0,0.0,0.000000,0.000000,0.000000
5,0.0,0.000000,0.0,0.0,0.438320,0.0,0.0,0.0,0.000000,0.000000,0.000000
6,0.0,0.000000,0.0,0.0,1.000000,0.0,0.0,1.0,1.000000,1.000000,1.000000
7,0.0,0.000000,0.0,0.0,0.796977,0.0,0.0,0.0,0.126060,0.421053,0.279070
8,0.0,0.000000,0.0,0.0,0.443694,0.0,0.0,0.0,0.000000,0.000000,0.000000
9,0.0,0.000000,0.0,0.0,0.719696,0.0,0.0,0.0,0.003632,0.538462,0.200000
10,0.0,0.000000,0.0,0.0,0.328703,0.0,0.0,0.0,0.018382,0.184211,0.149758
11,0.0,0.000000,0.0,0.0,0.313428,0.0,0.0,0.0,0.004462,0.000000,0.060453
12,0.0,0.000000,0.0,0.0,0.426917,0.0,0.0,0.0,0.000000,0.129032,0.148148
13,0.0,0.000000,0.0,0.0,0.252702,0.0,0.0,0.0,0.000000,0.285714,0.217391
14,0.0,0.000000,0.0,0.0,0.612381,0.0,0.0,0.0,0.017343,0.136986,0.094737
15,0.0,0.000000,0.0,0.0,0.573744,0.0,0.0,0.0,0.009596,0.295652,0.262887

📁 Đã đảm bảo thư mục tồn tại: /root/chatbot1/chatbot_document/backend/new/evaluation_reports
📊 Tìm thấy 12 metrics trong kết quả: ['faithfulness', 'answer_relevancy', 'context_precision', 'context_recall', 'semantic_similarity', 'answer_correctness', 'factual_correctness', 'exact_match', 'bleu_score', 'rouge_score(mode=fmeasure)', 'semantic_similarity', 'non_llm_string_similarity']
📊 Báo cáo đã được lưu tại: /root/chatbot1/chatbot_document/backend/new/evaluation_reports/ragas_report(naive_rerank).xlsx
📋 Điểm số trung bình:
   faithfulness: 0.1875
   answer_relevancy: 0.0904
   context_precision: 0.1875
   context_recall: 0.1875
   semantic_similarity: 0.5807
   answer_correctness: 0.0625
   factual_correctness: 0.0625
   exact_match: 0.1875
   bleu_score: 0.1367
   rouge_score(mode=fmeasure): 0.3145
   non_llm_string_similarity: 0.2796

## No rerank + child/parent

In [5]:
# ==============================================================================
# MỤC ĐÍCH: CHẠY PIPELINE RAG (PARENT/CHILD CHUNKING, KHÔNG RERANKING)
# ==============================================================================

import os
import json
from pathlib import Path
from typing import List, Tuple
import time
import uuid
import numpy as np
import pandas as pd
from langchain.schema import Document
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_google_genai import ChatGoogleGenerativeAI
# from sentence_transformers import CrossEncoder # <<< THAY ĐỔI 1: Không cần reranker nữa >>>
# from utils.api_key_manager import ApiKeyManager
from qdrant_client import QdrantClient
from qdrant_client.http.models import Distance, VectorParams, PointStruct

# --- CẤU HÌNH ---
DELAY_BETWEEN_CALLS = 10
QDRANT_HOST = "localhost"  
QDRANT_PORT = 6333      
COLLECTION_NAME = "norerank_child_chunks_eval_notebook"
GOOGLE_API_KEY = "AIzaSyCI8QGQrVUgr_FrFLttDs0fP4VyJyPXoec"

# --- KHỞI TẠO CÁC MODEL ---
print("🧠 Đang khởi tạo các model RAG...")
embedding_model = HuggingFaceEmbeddings(
    model_name="jinaai/jina-embeddings-v3",
    model_kwargs={"device": "cpu", "trust_remote_code": True}
)
llm_client = ChatGoogleGenerativeAI(model="gemini-2.0-flash", google_api_key=GOOGLE_API_KEY, temperature=0)
# reranker_model = CrossEncoder('BAAI/bge-reranker-large', device='cpu') # <<< THAY ĐỔI 1: Đã loại bỏ >>>
qdrant_client = QdrantClient(host=QDRANT_HOST, port=QDRANT_PORT)
print("✅ Các model RAG đã sẵn sàng.")


# --- CÁC HÀM TRỢ GIÚP ---
def clear_qdrant_collection():
    try: qdrant_client.delete_collection(collection_name=COLLECTION_NAME)
    except Exception: pass

def setup_qdrant_collection(embedding_dim: int):
    try:
        qdrant_client.recreate_collection(
            collection_name=COLLECTION_NAME,
            vectors_config=VectorParams(size=embedding_dim, distance=Distance.COSINE)
        ); return True
    except Exception as e:
        print(f"❌ Lỗi khi setup Qdrant collection: {e}"); return False

def store_child_chunks_in_qdrant(child_chunks: List[Document], child_embeddings: np.ndarray):
    points = [PointStruct(id=str(uuid.uuid4()), vector=emb.tolist(), payload=chunk.metadata) for chunk, emb in zip(child_chunks, child_embeddings)]
    qdrant_client.upsert(collection_name=COLLECTION_NAME, points=points, wait=True)
    print(f"✅ Đã lưu {len(points)} child chunks vào Qdrant.")

def setup_small_to_big_data_with_qdrant(markdown_content: str):
    print("--- Bước 1: Chuẩn bị dữ liệu Small-to-Big với Qdrant ---")
    parent_splitter = RecursiveCharacterTextSplitter(chunk_size=2000, chunk_overlap=200)
    child_splitter = RecursiveCharacterTextSplitter(chunk_size=400, chunk_overlap=50)
    parent_chunks = parent_splitter.create_documents([markdown_content])
    print(f"✅ Đã tạo {len(parent_chunks)} parent chunks.")
    all_child_chunks = []
    for i, p_chunk in enumerate(parent_chunks):
        child_texts = child_splitter.split_text(p_chunk.page_content)
        for text in child_texts:
            all_child_chunks.append(Document(page_content=text, metadata={"parent_id": i, "parent_content": p_chunk.page_content}))
    print(f"✅ Đã tạo {len(all_child_chunks)} child chunks.")
    sample_embedding = embedding_model.embed_query("test")
    if not setup_qdrant_collection(len(sample_embedding)): return None, False
    print("🧠 Đang embedding các child chunks...")
    child_contents = [c.page_content for c in all_child_chunks]
    child_embeddings = np.array(embedding_model.embed_documents(child_contents))
    print("✅ Embedding child chunks hoàn tất!")
    store_child_chunks_in_qdrant(all_child_chunks, child_embeddings)
    return parent_chunks, True

# <<< THAY ĐỔI 2: VIẾT LẠI HOÀN TOÀN HÀM RETRIEVE ĐỂ KHÔNG DÙNG RERANKER >>>
def retrieve_context_list_no_rerank(query: str, top_k_final: int = 3, retrieve_k_children: int = 15) -> List[str]:
    """
    Tìm kiếm các child chunk, sau đó lấy ra các parent chunk duy nhất
    dựa trên thứ tự điểm tương đồng vector ban đầu.
    """
    query_embedding = embedding_model.embed_query(query)
    # 1. Lấy ra danh sách child chunks đã được sắp xếp theo độ tương đồng
    search_results = qdrant_client.search(
        collection_name=COLLECTION_NAME,
        query_vector=query_embedding,
        limit=retrieve_k_children,
        with_payload=True
    )
    
    final_docs = []
    seen_parents = set() # Dùng set để đảm bảo parent chunk là duy nhất

    # 2. Lặp qua kết quả đã sắp xếp
    for hit in search_results:
        parent_content = hit.payload.get("parent_content")
        if parent_content and parent_content not in seen_parents:
            # Nếu parent chưa được thêm, thêm vào kết quả
            final_docs.append(parent_content)
            seen_parents.add(parent_content)
            
            # 3. Dừng lại khi đã có đủ số lượng context mong muốn
            if len(final_docs) >= top_k_final:
                break
    
    return final_docs

def answer_with_context(query: str, context_list: List[str]) -> str:
    """Hàm này giữ nguyên."""
    full_context_str = "\n\n---\n\n".join(context_list)
    prompt_template = f"""Bạn là một trợ lý AI chuyên nghiệp, chỉ trả lời dựa trên context được cung cấp.
Trả lời câu hỏi một cách ngắn gọn và chính xác. Nếu không có thông tin trong context, hãy nói "Tôi không tìm thấy thông tin trong tài liệu."
Context:\n---\n{full_context_str}\n---\nCâu hỏi: {query}\nTrả lời:"""
    response = llm_client.invoke(prompt_template)
    return response.content

# --- CHẠY PIPELINE VÀ THU THẬP DỮ LIỆU ---
generated_data_for_eval = [] 
markdown_file_path = Path('output_parsing/parsed_output.md')

if not markdown_file_path.exists():
    print(f"❌ Lỗi: Không tìm thấy file {markdown_file_path}. Vui lòng chạy bước parsing trước.")
else:
    with open(markdown_file_path, 'r', encoding='utf-8') as f:
        markdown_content = f.read()

    clear_qdrant_collection()
    parent_chunks, success = setup_small_to_big_data_with_qdrant(markdown_content)
    
    if not success:
        print("❌ Không thể setup dữ liệu với Qdrant. Dừng chương trình.")
    else:
        with open('/root/chatbot1/chatbot_document/backend/schemas/ragasdf_base.json', 'r', encoding='utf-8') as f:
            template4_queries_data = json.load(f)
        template4_queries = [item['question'] for item in template4_queries_data]

        print(f"\n\n=== 🚀 BẮT ĐẦU CHẠY RAG (PARENT/CHILD, NO RERANKING) TRÊN {len(template4_queries)} CÂU HỎI ===")
        
        for i, query in enumerate(template4_queries, 1):
            print(f"\n--- Query {i}/{len(template4_queries)} ---")
            print(f"❓ Câu hỏi: {query}")
            
            # <<< THAY ĐỔI 3: GỌI HÀM MỚI KHÔNG CÓ RERANKING >>>
            context_list = retrieve_context_list_no_rerank(query)
            answer = answer_with_context(query, context_list) 
            
            print(f"✅ Câu trả lời của hệ thống: {answer}")
            
            generated_data_for_eval.append({
                "question": query, "answer": answer, "contexts": context_list 
            })
            
            print("-" * 40)
            if i < len(template4_queries):
                print(f"⏳ Đợi {DELAY_BETWEEN_CALLS} giây...")
                time.sleep(DELAY_BETWEEN_CALLS)

        print("\n\n✅ Đã thu thập xong toàn bộ dữ liệu.")
        display(pd.DataFrame(generated_data_for_eval).head())
        
        output_file = Path('new/output_parsing/generated_data_for_eval(norerank_childparent).json')
        output_file.parent.mkdir(parents=True, exist_ok=True)
        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump(generated_data_for_eval, f, ensure_ascii=False, indent=4)
        print(f"✅ Đã lưu kết quả vào file: {output_file}")

🧠 Đang khởi tạo các model RAG...

WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
WARNING:transformers_modules.jinaai.xlm-roberta-flash-implementation.2b6bc3f30750b3a9648fe9b63448c09920efe9be.modeling_xlm_roberta:flash_attn is not installed. Using PyTorch native attention implementation.
/tmp/ipykernel_59379/3004721572.py:37: UserWarning: Qdrant client version 1.15.1 is incompatible with server version 1.7.2. Major versions should match and minor version difference must not exceed 1. Set check_compatibility=False to skip version check.
  qdrant_client = QdrantClient(host=QDRANT_HOST, port=QDRANT_PORT)

✅ Các model RAG đã sẵn sàng.
--- Bước 1: Chuẩn bị dữ liệu Small-to-Big với Qdrant ---
✅ Đã tạo 12 parent chunks.
✅ Đã tạo 62 child chunks.

/tmp/ipykernel_59379/3004721572.py:48: DeprecationWarning: `recreate_collection` method is deprecated and will be removed in the future. Use `collection_exists` to check collection existence and `create_collection` instead.
  qdrant_client.recreate_collection(

🧠 Đang embedding các child chunks...
✅ Embedding child chunks hoàn tất!
✅ Đã lưu 62 child chunks vào Qdrant.


=== 🚀 BẮT ĐẦU CHẠY RAG (PARENT/CHILD, NO RERANKING) TRÊN 40 CÂU HỎI ===

--- Query 1/40 ---
❓ Câu hỏi: Tên đầy đủ của khách hàng là gì?

/tmp/ipykernel_59379/3004721572.py:89: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: CÔNG TY CỔ PHẦN MẶT DỰNG CAG
----------------------------------------
⏳ Đợi 10 giây...

--- Query 2/40 ---
❓ Câu hỏi: Số giấy phép đăng ký kinh doanh của khách hàng là gì?

/tmp/ipykernel_59379/3004721572.py:89: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Số 0101442420 do Phòng Đăng ký kinh doanh – Sở Kế hoạch và Đầu tư thành phố Hà Nội cấp, đăng ký lần đầu ngày 19/01/2004, đăng ký thay đổi lần thứ 8 ngày 12/04/2023
----------------------------------------
⏳ Đợi 10 giây...

--- Query 3/40 ---
❓ Câu hỏi: ID khách hàng là gì?

/tmp/ipykernel_59379/3004721572.py:89: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: 22079986
----------------------------------------
⏳ Đợi 10 giây...

--- Query 4/40 ---
❓ Câu hỏi: Phân khúc của khách hàng là gì?

/tmp/ipykernel_59379/3004721572.py:89: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 5/40 ---
❓ Câu hỏi: Loại khách hàng là gì?

/tmp/ipykernel_59379/3004721572.py:89: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: CÔNG TY CỔ PHẦN MẶT DỰNG CAG
----------------------------------------
⏳ Đợi 10 giây...

--- Query 6/40 ---
❓ Câu hỏi: Ngành nghề hoạt động kinh doanh của khách hàng là gì?

/tmp/ipykernel_59379/3004721572.py:89: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 7/40 ---
❓ Câu hỏi: Mục đích báo cáo là gì?

/tmp/ipykernel_59379/3004721572.py:89: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 8/40 ---
❓ Câu hỏi: Kết quả phân luồng của khách hàng là gì?

/tmp/ipykernel_59379/3004721572.py:89: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 9/40 ---
❓ Câu hỏi: XHTD của khách hàng là gì?, XHTD là xếp hạng tín dụng của khách hàng và thường có các giá trị như Aa3, Baa2, v.v.

/tmp/ipykernel_59379/3004721572.py:89: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 10/40 ---
❓ Câu hỏi: Ngày thành lập công ty là ngày nào?

/tmp/ipykernel_59379/3004721572.py:89: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: 19/01/2004
----------------------------------------
⏳ Đợi 10 giây...

--- Query 11/40 ---
❓ Câu hỏi: Địa chỉ đăng ký kinh doanh của công ty là gì?

/tmp/ipykernel_59379/3004721572.py:89: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Lô CN4 – 2.1, KCN Thạch Thất, thị trấn Quốc Oai, huyện Quốc Oai, thành phố Hà Nội
----------------------------------------
⏳ Đợi 10 giây...

--- Query 12/40 ---
❓ Câu hỏi: Người đại diện theo pháp luật của công ty là ai?

/tmp/ipykernel_59379/3004721572.py:89: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Họ tên: ĐÀO CÔNG DUY
Chức vụ: Tổng Giám đốc
----------------------------------------
⏳ Đợi 10 giây...

--- Query 13/40 ---
❓ Câu hỏi: Khách hàng có kinh doanh ngành nghề có điều kiện không?

/tmp/ipykernel_59379/3004721572.py:89: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 14/40 ---
❓ Câu hỏi: Thông tin chi tiết về ban lãnh đạo công ty là gì. Hãy liệt kê đầy đủ tên các thành viên, chức vụ, tỉ lệ góp vốn nếu có?

/tmp/ipykernel_59379/3004721572.py:89: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: - ĐÀO CÔNG DUY, Tổng Giám đốc, 90%
- Thái Thị Kim Dung, 8%
- Đào Công Dũng, 2%
----------------------------------------
⏳ Đợi 10 giây...

--- Query 15/40 ---
❓ Câu hỏi: Thông tin chi tiết về đầu vào sản xuất kinh doanh là gì?

/tmp/ipykernel_59379/3004721572.py:89: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 16/40 ---
❓ Câu hỏi: Thông tin chi tiết về đầu ra sản xuất kinh doanh là gì?

/tmp/ipykernel_59379/3004721572.py:89: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 17/40 ---
❓ Câu hỏi: Nhận xét về thông tin khách hàng là gì?

/tmp/ipykernel_59379/3004721572.py:89: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tên khách hàng là CÔNG TY CỔ PHẦN MẶT DỰNG CAG, ID khách hàng là 22079986, Giấy CNĐKDN số 0101442420 do Phòng Đăng ký kinh doanh – Sở Kế hoạch và Đầu tư thành phố Hà Nội cấp ngày 19/01/2004, đăng ký thay đổi lần thứ 8 ngày 12/04/2023, địa chỉ liên hệ tại Lô CN4 – 2.1, KCN Thạch Thất, thị trấn Quốc Oai, huyện Quốc Oai, thành phố Hà Nội, người đại diện theo pháp luật là ông ĐÀO CÔNG DUY chức vụ Tổng Giám đốc.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 18/40 ---
❓ Câu hỏi: Nhận xét về pháp lý/GPKD có điều kiện là gì?

/tmp/ipykernel_59379/3004721572.py:89: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 19/40 ---
❓ Câu hỏi: Nhận xét về chủ doanh nghiệp/ban lãnh đạo là gì?

/tmp/ipykernel_59379/3004721572.py:89: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 20/40 ---
❓ Câu hỏi: Nhận xét về KYC là gì?

/tmp/ipykernel_59379/3004721572.py:89: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 21/40 ---
❓ Câu hỏi: Lĩnh vực kinh doanh của công ty là gì?

/tmp/ipykernel_59379/3004721572.py:89: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 22/40 ---
❓ Câu hỏi: Sản phẩm/dịch vụ của công ty là gì?

/tmp/ipykernel_59379/3004721572.py:89: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 23/40 ---
❓ Câu hỏi: Tỷ trọng doanh thu năm N-1 (%) là bao nhiêu?

/tmp/ipykernel_59379/3004721572.py:89: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 24/40 ---
❓ Câu hỏi: Tỷ trọng doanh thu năm N (%) là bao nhiêu?

/tmp/ipykernel_59379/3004721572.py:89: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 25/40 ---
❓ Câu hỏi: Nhóm mặt hàng của công ty là gì?

/tmp/ipykernel_59379/3004721572.py:89: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 26/40 ---
❓ Câu hỏi: Tỷ trọng doanh thu năm 2023 là bao nhiêu?

/tmp/ipykernel_59379/3004721572.py:89: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 27/40 ---
❓ Câu hỏi: Tỷ trọng doanh thu 10T/2024 là bao nhiêu?

/tmp/ipykernel_59379/3004721572.py:89: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 28/40 ---
❓ Câu hỏi: Mô tả chung về sản phẩm của công ty là gì?

/tmp/ipykernel_59379/3004721572.py:89: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Công ty sản xuất nhôm thanh theo các mã kích thước khác nhau, kính không màu và kính màu (1 lớp màu bên ngoài). Sản phẩm được may đo theo từng dự án. Thông thường kính 2 lớp sẽ được dùng.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 29/40 ---
❓ Câu hỏi: Mô tả lợi thế cạnh tranh của công ty là gì?

/tmp/ipykernel_59379/3004721572.py:89: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 30/40 ---
❓ Câu hỏi: Mô tả năng lực đấu thầu của công ty là gì?

/tmp/ipykernel_59379/3004721572.py:89: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Công ty có thể phát hành bảo lãnh các gói thầu cho các CĐT thuộc offering FMCG - TPK Thương mại dược, VTTB Y tế.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 31/40 ---
❓ Câu hỏi: Quy trình vận hành (tóm tắt) của công ty là gì?

/tmp/ipykernel_59379/3004721572.py:89: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 32/40 ---
❓ Câu hỏi: Đầu vào - mặt hàng là gì?

/tmp/ipykernel_59379/3004721572.py:89: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Nhôm thanh và kính.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 33/40 ---
❓ Câu hỏi: Đầu vào - chi tiết là gì?

/tmp/ipykernel_59379/3004721572.py:89: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tổng nguồn vốn cần sử dụng: 800 tỷ
Vốn tự có: 150 tỷ
Vốn vay: 400 tỷ
Vốn khác: 250 tỷ
Doanh thu (dự kiến): 950 tỷ
Giá vốn: 752 tỷ
Chi phí quản lý: 90 tỷ
Chi phí lãi vay: 39 tỷ
Lợi nhuận: 55 tỷ
----------------------------------------
⏳ Đợi 10 giây...

--- Query 34/40 ---
❓ Câu hỏi: Đầu vào - phương thức thanh toán là gì?

/tmp/ipykernel_59379/3004721572.py:89: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 35/40 ---
❓ Câu hỏi: Đầu ra - kênh phân phối là gì?

/tmp/ipykernel_59379/3004721572.py:89: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 36/40 ---
❓ Câu hỏi: Đầu ra - tỷ trọng là bao nhiêu?

/tmp/ipykernel_59379/3004721572.py:89: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 37/40 ---
❓ Câu hỏi: Đầu ra - phương thức thanh toán là gì?

/tmp/ipykernel_59379/3004721572.py:89: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 38/40 ---
❓ Câu hỏi: Nhận xét tổng quan về hoạt động kinh doanh là gì?

/tmp/ipykernel_59379/3004721572.py:89: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Doanh thu dự kiến là 950 tỷ, giá vốn là 752 tỷ, chi phí quản lý là 90 tỷ, chi phí lãi vay là 39 tỷ, và lợi nhuận là 55 tỷ. Nguồn trả nợ từ hoạt động kinh doanh, nợ gốc trả cuối kỳ, nợ lãi trả hàng tháng.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 39/40 ---
❓ Câu hỏi: Phân tích cung cầu ngành là gì?

/tmp/ipykernel_59379/3004721572.py:89: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------
⏳ Đợi 10 giây...

--- Query 40/40 ---
❓ Câu hỏi: Nhận xét về thông tin ngành là gì?

/tmp/ipykernel_59379/3004721572.py:89: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_results = qdrant_client.search(

✅ Câu trả lời của hệ thống: Tôi không tìm thấy thông tin trong tài liệu.
----------------------------------------


✅ Đã thu thập xong toàn bộ dữ liệu.

,question,answer,contexts
0,Tên đầy đủ của khách hàng là gì?,CÔNG TY CỔ PHẦN MẶT DỰNG CAG,[2. Thông tin bên bảo đảm (nếu bên bảo đảm là ...
1,Số giấy phép đăng ký kinh doanh của khách hàng...,Số 0101442420 do Phòng Đăng ký kinh doanh – Sở...,[2. Thông tin bên bảo đảm (nếu bên bảo đảm là ...
2,ID khách hàng là gì?,22079986,[2. Thông tin bên bảo đảm (nếu bên bảo đảm là ...
3,Phân khúc của khách hàng là gì?,Tôi không tìm thấy thông tin trong tài liệu.,[| | Sunspace | CAG ...
4,Loại khách hàng là gì?,CÔNG TY CỔ PHẦN MẶT DỰNG CAG,[2. Thông tin bên bảo đảm (nếu bên bảo đảm là ...

✅ Đã lưu kết quả vào file: new/output_parsing/generated_data_for_eval(norerank_childparent).json

In [ ]:
# ==============================================================================
# CELL MỚI: THỰC HIỆN ĐÁNH GIÁ BẰNG RAGAS
# ==============================================================================
from utils.ragas_evaluation import RagasEvaluator
import pandas as pd
from pathlib import Path
import json
# 1. Khởi tạo Evaluator
# Đảm bảo GOOGLE_API_KEY đã được định nghĩa ở cell trên
GOOGLE_API_KEYS = ["AIzaSyBH8O5IfqYrJ5wtWnmUC21IfMjzJCrTm3I",
                    "AIzaSyDtBIjTSfbvuEsobNwjtdyi9gVpDrCaWPM",
                    "AIzaSyAD_58r3fQhcTOE6qQS1YlR3iJ_ZnGKy10",
                    "AIzaSyAWtCSrLhJDZGF1ArOSS0o7Iy_zMG42810",
                    "AIzaSyCtAz9maZ9usoxEHhhFocHW07WM4IbgOXo",
                    "AIzaSyCI8QGQrVUgr_FrFLttDs0fP4VyJyPXoec",
                    "AIzaSyBPglAFlDOf97drnNAplHIIsjgvsfzezsI",
                    "AIzaSyCaKzwEjW0XxJAuZ9XdzI6rHkifHkA0eNY",
                    "AIzaSyDNosIJZjXd2tzm7_VKxK5uFTBmoPuHXkc"]

evaluator = RagasEvaluator(list_of_api_keys=GOOGLE_API_KEYS)

# load generated data từ file JSON
generated_data_file = Path('output_parsing/generated_data_for_eval(norerank_childparent).json')
if not generated_data_file.exists():
    print(f"❌ Lỗi: Không tìm thấy file {generated_data_file}. Vui lòng chạy bước thu thập dữ liệu trước.")
else:
    with open(generated_data_file, 'r', encoding='utf-8') as f:
        generated_data_for_eval = json.load(f)
        
# 2. Tải dataset cơ sở (chứa question và ground_truth)
base_data = evaluator.load_base_dataset('/root/chatbot1/chatbot_document/backend/schemas/ragasdf_base.json')

# 3. Chuẩn bị dataset hoàn chỉnh bằng cách kết hợp base_data và generated_data
eval_dataset = evaluator.prepare_evaluation_dataset(
    base_data=base_data,
    generated_data=generated_data_for_eval # Sử dụng kết quả từ cell trước
)

# 4. Xuất file dataset RAGAS hoàn chỉnh ra Excel để kiểm tra
if eval_dataset:
    ragas_df = eval_dataset.to_pandas()
    ragas_df['context_count'] = ragas_df['contexts'].apply(len)
    output_df_path = "new/ragasdf/ragas_dataset_for_evaluation(norerank_childparent).xlsx"
    os.makedirs(Path(output_df_path).parent, exist_ok=True)
    ragas_df.to_excel(output_df_path, index=False)
    print(f"💾 Đã xuất file dataset RAGAS hoàn chỉnh ra: {output_df_path}")
    print("Đây là 5 dòng đầu tiên của dataset sẽ được đánh giá:")
    display(ragas_df.head())
    
# 5. Chạy đánh giá
if eval_dataset:
    results_df = evaluator.run_evaluation(eval_dataset)

    if results_df is not None:
        # 6. Hiển thị và lưu báo cáo
        print("\n\n--- 📊 KẾT QUẢ ĐÁNH GIÁ CHI TIẾT ---")
        display(results_df)

        evaluator.save_report(results_df, "/root/chatbot1/chatbot_document/backend/new/evaluation_reports", "ragas_report(norerank_childparent).xlsx")
    else:
        print("❌ Đánh giá không trả về kết quả.")
else:
    print("❌ Không thể tạo dataset để đánh giá.")

🚀 Khởi tạo RagasEvaluator (có Retry & Key Switching)...

flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.

✅ LLM và Embeddings đã sẵn sàng.
📋 Đã định nghĩa 12 metrics: ['faithfulness', 'answer_relevancy', 'context_precision', 'context_recall', 'semantic_similarity', 'answer_correctness', 'factual_correctness', 'exact_match', 'bleu_score', 'rouge_score', 'semantic_similarity', 'non_llm_string_similarity']
📁 Đã tạo thư mục báo cáo: evaluation_reports
📂 Đang tải base dataset từ: /root/chatbot1/chatbot_document/backend/schemas/ragasdf_base.json
✅ Tải thành công 40 mẫu.
🔄 Đang chuẩn bị dataset để đánh giá...
✅ Đã chuẩn hóa cột 'contexts' với kiểu dữ liệu: <class 'list'>
✅ Đã tạo thành công dataset với 40 mẫu để đánh giá.
✅ Kiểu dữ liệu của cột 'contexts' đã được xác nhận là: <class 'list'>
✅ Sau khi loại bỏ null/empty, còn 16 mẫu.
✅ Đã thêm cột 'reference' từ ground_truths.
💾 Đã xuất file dataset RAGAS hoàn chỉnh ra: new/ragasdf/ragas_dataset_for_evaluation(norerank_childparent).xlsx
Đây là 5 dòng đầu tiên của dataset sẽ được đánh giá:

,question,ground_truths,answer,contexts,reference,__index_level_0__,context_count
0,Tên đầy đủ của khách hàng là gì?,[CÔNG TY CỔ PHẦN MẶT DỰNG CAG],CÔNG TY CỔ PHẦN MẶT DỰNG CAG,[1. Thông tin khách hàng\nTên khách hàng: | CÔ...,CÔNG TY CỔ PHẦN MẶT DỰNG CAG,0,3
1,Số giấy phép đăng ký kinh doanh của khách hàng...,[0101442420],Số 0101442420 do Phòng Đăng ký kinh doanh – Sở...,[1. Thông tin khách hàng\nTên khách hàng: | CÔ...,0101442420,1,3
2,ID khách hàng là gì?,[22079986],22079986,[1. Thông tin khách hàng\nTên khách hàng: | CÔ...,22079986,2,3
3,Phân khúc của khách hàng là gì?,[MM],MM,"[| | • Diện tích: 10,000 ...",MM,3,3
4,"XHTD của khách hàng là gì?, XHTD là xếp hạng t...",[Aa3],XHTD của khách hàng là Aa3.,[1. Thông tin khách hàng\nTên khách hàng: | CÔ...,Aa3,8,3

✅ Dataset schema hợp lệ. Columns: ['question', 'ground_truths', 'answer', 'contexts', 'reference', '__index_level_0__']

🔬 Bắt đầu đánh giá RAGAS trên 16 mẫu với 12 metrics...
📋 Metrics: ['faithfulness', 'answer_relevancy', 'context_precision', 'context_recall', 'semantic_similarity', 'answer_correctness', 'factual_correctness', 'exact_match', 'bleu_score', 'rouge_score', 'semantic_similarity', 'non_llm_string_similarity']

--- 🔄 Đang đánh giá dòng 1/16 ---
   Q: Tên đầy đủ của khách hàng là gì?...
    🔄 Metric 1/12: faithfulness
    ✅ faithfulness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 2/12: answer_relevancy

Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 45
}
].
Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 45
}
].
Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 45
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 1
🔄 Đã chuyển sang API key index 1: AIzaSyDt...CaWPM
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 2
🔄 Đã chuyển sang API key index 2: AIzaSyAD...GKy10
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ✅ answer_relevancy: 0.4464239336956468
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 3/12: context_precision

Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 25
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 3
🔄 Đã chuyển sang API key index 3: AIzaSyAW...42810
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 20
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 4
🔄 Đã chuyển sang API key index 4: AIzaSyCt...bgOXo
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ✅ context_precision: 0.99999999995
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 4/12: context_recall

Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 6
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 5
🔄 Đã chuyển sang API key index 5: AIzaSyCI...PXoec
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ✅ context_recall: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 5/12: semantic_similarity
    ✅ semantic_similarity: 0.9999999999999999
    🔄 Metric 6/12: answer_correctness

Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 51
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 6
🔄 Đã chuyển sang API key index 6: AIzaSyBP...zezsI
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới

Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 45
}
].

  ⚠️ Lỗi Quota được phát hiện.
🔄 Đã chuyển sang API key index: 7
🔄 Đã chuyển sang API key index 7: AIzaSyCa...A0eNY
  🔧 Đã chuyển từ key cũ sang key mới
  ✅ Đã tạo lại client với API key mới
    ✅ answer_correctness: 1.0
    ⏳ Chờ 8.0s để tránh rate limit...
    🔄 Metric 7/12: factual_correctness

Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 200
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 30
}
].

KeyboardInterrupt: